### ISSUE TITLE
ROOT/config is a directory

### ISSUE THREAD

**Issue by HelLViS69** [openid/AppAuth-Android#100]
Hi,
I'm imported the project into Android Studio and it doesn't build.
It complains at line 26:
def grgit = org.ajoberstar.grgit.Grgit.open(dir: '.')
What should I do?

Moreover, for every Gradle command, lint is saying "cannot resolve symbol"

**Comment by iainmcgin** [comment]
There's something weird happening with either the way your build environment is set up, or with retrieving dependencies. Grgit is used to generate version numbers for built binaries based on the state of the repository. It's optional that this work correctly, so I can put better error handling into the build scripts, but I'd like to get a better understanding of what is actually broken in your environment first.

**Comment by iainmcgin** [comment]
Closing due to lack of follow-up from reporter.
