### ISSUE TITLE
Can't get TokenActivity to work with custom IdP

### ISSUE THREAD

**Issue by ndorigatti** [openid/AppAuth-Android#101]
Hello all,
I've downloaded and run locally mitreid server, and I'm trying to integrate it with this app, following the instructions, but I have issues with TokenActivity, to be more specific I get the snackbar saying:
"Token refresh Failed"
and debugging I found out that there is an "AuthorizationException" whose json is:
{"type":0,"code":3,"errorDescription":"Network error"}

The issue is on token request (I debugged it), because i can see the login and the redirect works correctly (I see the app going on the web server apps list), but token won't work.
I don't think it is an issue of a mitre configuration (but it could be?),

The grant type is set to: "authorization code" and "refresh", under response type, "code" "token" and "id_token" are enabled.

What else can I do? the token endpoint is correct, but is not working!

**Comment by ndorigatti** [comment]
I found the issue:
The library sends the clientID and clientSecret ONLY when and if provided in the DynamicRegistration url. In my case i Could not provide dynamic registration because I was testing locally in my pc, so i had to change the library and allow a customized client secret setter.
Anyway I could not get user info, i think the library is not complete...

**Comment by allek5** [comment]
I'm having the same error trying to make it work with Dropbox. 
Can you please explain how did you solve the problem?

**Comment by ndorigatti** [comment]
@allek5 Well I just "hacked" the code in AuthState there is the method "getClientSecret" and at line 632 there is the method getClientAuthentication() which takes the clientsecret (if any) and acts like that

**Comment by allek5** [comment]
Thx, it helped.

**Comment by iainmcgin** [comment]
I think this bug is probably obsoleted by the current demo app changes, and it is now possible to directly specify a client authentication when making token requests. Issue #179 tracks closing the last hole, providing a client authentication object as part of `performActionWithFreshTokens`.
