### ISSUE TITLE
Detecting user initiated closing of the authorization flow.

### ISSUE THREAD

**Issue by mattinger** [openid/AppAuth-Android#102]
Is there a way to determine if the user closed the authorization flow, either via the close button on the chrome custom tab, or by hitting the android back button.

I'm trying to implement a re-auth flow in case of token refresh failure.  If that happens, i'd like the user to reauth and if successful stay where they are.  If they close it themselves, i want to just close all the open activities on the app.

**Comment by iainmcgin** [comment]
This isn't implemented in the library at present as we don't have a convenient place to monitor events from the opened custom tab. The situation is also more complex when using an intent for the system browser, as there is no such event to capture. I had planned to return to this and devise a solution to handle this (as it exists in the iOS variant of the library) but haven't had time yet. I'd be happy to discuss solutions and accept contributions to solve this problem.

**Comment by mattinger** [comment]
I did look at the code, and noticed the "startActivity" call in AuthorizationService.  I'm wondering if we instead call startActivityForResult, if both the chrome custom tab and the system browser would send a result back.  It's unclear to me, however, what that result would look like in terms of hitting the close button as opposed to the window closing on a redirect.  I suppose that would really be browser dependent.

**Comment by iainmcgin** [comment]
Unfortunately I don't believe custom tabs return results in this way, and the defined callbacks don't appear to indicate when a tab is dismissed. I think the only option is to store some information in the invoking activity such that when a onStart / onResume occurs, we could determine whether an authorization flow was in progress. Returning to the original activity would likely mean the tab was closed, and we could take some remedial action at that point. I'm not sure if that kind of behavior belongs in the library or not; I'll need to experiment.

**Comment by mattinger** [comment]
I figured that might be the case.  We're working with our oauth team to implement a custom prompt=reauth flow so that we can use a webview and pass a login_id_hint or something to it, and not have to shared the cookies with the chrome browser itself.  This can be closed if you feel it's not realistically implementable.

**Comment by iainmcgin** [comment]
I'll leave it open until I mull over the problem some more; I'll also talk to the Chrome team as providing some kind of callback for closing the tab seems legitimately useful.

**Comment by iainmcgin** [comment]
This is now fixed by #109 - we can fire a different intent for the user canceling the authorization flow.
