### ISSUE TITLE
Cross-Client authorization

### ISSUE THREAD

**Issue by roccozanni** [openid/AppAuth-Android#107]
Hi, 
I'm trying to use this library as a replacement for the official Google Sign-In SDK on Android, because when you try to login to a Youtube account, it doesn't support channel selection.

With the Sign-In SDK you can also request an authorization code for a server-side token, by specifying the client_id of your server application. This way, the app will initiate the login process, get the authorization code, send it to the server that will complete the exchange and store the long-term token on the database.  This is a strong requirement for us, because all the processing is made on the server-side. 

I'm trying to make this work by following the documentation here: https://developers.google.com/identity/protocols/CrossClientAuth but it does't seem to work, like this is a mechanism that can be used only in the official Sign-In SDK and not by 3rd party apps that just implements the OAuth2 protocol. 

What's your thoughts about this?

Thanks
Rocco

**Comment by iainmcgin** [comment]
There shouldn't be any problem in performing a code authorization flow for your server using AppAuth or with Google as the identity provider. I believe you should issue an authorization request as follows:

```
// fetch the Google config into a field, say mGoogleConfig
AuthorizationServiceConfiguration.fetchFromIssuer(Uri.parse("https://accounts.google.com/"),
    new RetrieveConfigurationCallback() { ... });

AuthorizationService authService = new AuthorizationService(this);
authService.performAuthorizationRequest(
    new AuthorizationRequest.Builder(
        mGoogleConfig,
        SERVER_CLIENT_ID,
        "code",
        REDIRECT_URI)
        // set any extra properties, like scopes required, etc.
        .build(),
   resultHandlerIntent);
```

A successful response should contain the code which you can send to your server, which can then exchange the code for a refresh token.

@WilliamDenniss anything I've missed here?

**Comment by roccozanni** [comment]
@iainmcgin @WilliamDenniss this is something I already tried. In order to use the server app client_id, I also had to add 

```
com.googleusercontent.apps.<id>:/oauth2redirect
```

to the list of the server app valid redirect urls. This is not a big deal BUT it doesn't work, after selecting the account and granting the permissions, the browser shows a 500 error page by google, probably because having registered the server app as a "web" client and not a "native" one, the login flow refuses to trigger a redirect to something that is not an http/https url.

I spent some time analyzing what the Google SDK does on iOS, where the login process is web-based and I can see the parameters added to the oauth url. I see that they add parameter called `audience` that contains the client_id of the server-side app, so I tried to replicate it here using the `setAdditionalParameters()` method but it still doesn't work, because when I try to exchange the code on the server side I get an "unauthorized client" error, like if the `audience` parameter has been totally ignored.

**Comment by roccozanni** [comment]
I did some step forward but I fear the news aren't good. I continued analyzing the behavior of the google sdk for ios and what I discovered is that after the code has been obtained, the sdk does a token exchange request:

`POST /oauth2/v4/token`

with these parameters:
```
audience:<server_client_id>.apps.googleusercontent.com
client_id:<client_id>.apps.googleusercontent.com
code:<code obtained at step1>
grant_type:authorization_code
redirect_uri:<client_redirect_uri>
```

and the response contains a `server_code` parameter that you have to send to your backend to do the final token exchange.

Unfortunately, this `server_code` parameter is included only if the given `cliend_id` belongs to an app registered on the google api console as `iOS`.

At this stage I fear this is something they put in place for iOS only and there is no easy way to overcome this limitation in a clean way.

**Comment by iainmcgin** [comment]
William and I both work for Google's identity team, so there is no need to speculate as to why things are the way they are - we can provide definitive answers :)

The flow you are describing on iOS is designed to allow a single flow to grant refresh tokens to both the native app and server. If you don't need tokens for the client, this isn't the flow you want.

Can you tell me more about why the flow I described didn't work? After making the authorization request you should receive a code which you can send to your server and exchange. What part of the process fails, and with what error message? Can you share any code?

**Comment by WilliamDenniss** [comment]
Ah, so you're trying to authorize both your client and server at the same time. This is not very well documented, as it's a custom extension to OAuth.  Another approach would be just to get the code for your server directly, without needing to obtain one for your client as well – but since that's what you're doing lets try to get that working.

Since as you found this only works with the app registered as an `iOS` client, you can actually just register your Android app as an `iOS` client. Specify your package name as the bundle ID, and it should work in AppAuth for Android just the same, as both platforms support custom URI scheme redirects in the same way. Then you can make that additional token call :)

Seems like we should enable that feature on Android though too, so that registration workaround becomes unnecessary.

**Comment by roccozanni** [comment]
Well, I'm not trying to speculate but as a developer, when I face an issue it's part of my job to analyze things to understand how they work, because in the end I have to deliver a working product. 

Eventually I did as William suggested, getting the code from the server directly by triggering a server-side authorization flow in a chrome custom tab that on completion redirects to my app using a custom scheme url. This is sub-optimal because we don't get a token that we can use also on the client-side we can overcome this issue providing apis that proxy the calls to the youtube ones.

IMHO the best way to definitely solve the issue will be to provide Youtube channel selection support directly into the native SDK, because the native SDK provides a better UX to the end user and reduces the implementation effort, but if this is not possible for some reason, then allowing an iOS-like solution will definitely help.

Thanks,
Rocco

**Comment by iainmcgin** [comment]
William and I are going to provide task-oriented documentation for AppAuth on Android and iOS in the future to help resolve questions like this. The flow I originally described is intended to work, and my interpretation of your earlier descriptions of the problem made it sound as though you do not actually require a refresh token for your client, but only for your server.

If you can provide code for what you tried so we can more clearly understand what went wrong, this will help us to document common pitfalls.

**Comment by iainmcgin** [comment]
Closing as mostly resolved, just lacking some additional info for documentation purposes.

**Comment by chadanuk** [comment]
Hi, @iainmcgin @WilliamDenniss, @roccozanni 

I'm currently encountering this exact issue and can't find much more information around how to solve it. 

Brief summary of purpose:
Android App with sign in for app (AppAuth). Get access token from google and then with response,send to an oauth server using google for authentication.

Currently we're not matching the client_id as we can't get the following to work.

I'm currently trying the 'iOS client_id' with audience as an AdditionalParameter:
```java
Map<String, String> additionalParameters = Collections.singletonMap("audience", webClientId);

builder.setAdditionalParameters(additionalParameters);
```

I'm not getting anything different in the access token (I'm expecting either the aud/azp parameter in the token to be the web client id?

Any pointers/ideas would be massively appreciated!

**Comment by iainmcgin** [comment]
@chadanuk sending an `audience` parameter as part of the authorization code exchange is a non-standard extension that Google uses for its own purposes in the iOS SDK, and it only works when the `client_id` is registered as an iOS client. Based on your description, you're probably using an Android client ID for your app, as you should be.

Unfortunately, there aren't many good options available to simultaneously authorize a native app and it's backend with separate client IDs. You can either share the same refresh token between app and backend, or you can just authorize your backend and relay all requests through it. I recommend the latter, as it is slightly better from a security standpoint, but this isn't always a viable approach for all apps.

**Comment by chadanuk** [comment]
@iainmcgin We have come to a solution on this which could be worth documenting...!

Basically, rather than relying on building the token request from the authorization request repsonse. 

We create a new one and add the audience as . an additional parameter here. Part of the confusion came from working out which request to add the parameter onto (googles docs aren't clear until you realise this!). Once we figured that out it became more obvious what to do. 

Code beloq for reference.

```java
AuthorizationService authService = new AuthorizationService(this.cordova.getActivity());

            Map<String, String> additionalParameters = Collections.singletonMap("audience", mWebClientId);

            TokenRequest tokenRequest =new TokenRequest.Builder(
                    response.request.configuration,
                    response.request.clientId)
                    .setGrantType(GrantTypeValues.AUTHORIZATION_CODE)
                    .setRedirectUri(response.request.redirectUri)
                    .setScope("openid email")
                    .setCodeVerifier(response.request.codeVerifier)
                    .setAuthorizationCode(response.authorizationCode)
                    .setAdditionalParameters(additionalParameters)
                    .build();
```
