### ISSUE TITLE
Expose custom tab intent builder

### ISSUE THREAD

**Issue by jamesrpluscitizen** [openid/AppAuth-Android#110]
Currently the CustomTabsIntent.Builder is not exposed and accessible in AuthorizationService.

Would like to be able to provide my own instance of the builder to customize the look and feel of the chrome tab as per [https://github.com/GoogleChrome/custom-tabs-client/blob/master/Using.md#ui-customization](url)

**Comment by iainmcgin** [comment]
You can pass your own CustomTabIntent to performAuthorizationRequest, which will let you do what you want. The demo also shows you how to do this, as it changes the color of the custom tab.

**Comment by jamesrpluscitizen** [comment]
Aha, thank you.
