### ISSUE TITLE
Provide a way to disable SSL validation

### ISSUE THREAD

**Issue by mattinger** [openid/AppAuth-Android#115]
In certain debug environments, there is a need to disable SSL cert and host verification.  App auth currently does not expose a way to alter the HttpUrlConnection to do this.  As a result, one would have to set the system default via HttpsURLConnection.setDefaultHostNameVerifier and setDefaultSSLSocketFatory methods, which would affect the entire system.

It would be nice to have a way to set these a given AuthorizationService instance and if set, use those on the constructed HttpsURLConnection.

**Comment by mattinger** [comment]
I've been looking at the code, and it seems like AuthorizationService would be relatively straightforward change, but AuthorizationServiceConfiguration would be a bit more involved.

**Comment by iainmcgin** [comment]
Providing a Factory for the creation of HttpUrlConnection seems reasonable, particularly as it would also provide a means to do certificate pinning (the opposite of what you're asking for :smile:). It can also be dangerous however, so we'll want to be careful in documenting the usage of this feature, in that it can ruin the security measures in the rest of the library.
