### ISSUE TITLE
Support "nonce" OpenID Connect auth request parameter

### ISSUE THREAD

**Issue by iainmcgin** [openid/AppAuth-Android#12]
> OPTIONAL. String value used to associate a Client session with an ID Token, and to mitigate replay attacks. The value is passed through unmodified from the Authentication Request to the ID Token. Sufficient entropy MUST be present in the nonce values used to prevent attackers from guessing values. For implementation notes, see [Section 15.5.2](https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes).

[Section 3.2.2.1](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest), "Authentication Request" specifies that this parameter is REQUIRED for implicit flow authentication requests (those with response type `id_token` or `id_token token`).

**Comment by jeffpfoster** [comment]
Got any notes on implementing this.  I am working on a project that will require this.  I'm going to have to add it to the code so I can add this and send you a pull request if I get it implemented cleanly

**Comment by Lutando** [comment]
Something like a UUID or a value generated from a crypto random number generator suffices as a nonce . 

The nonce exists in the request url query string.

**Comment by iainmcgin** [comment]
Fixed by #385.
