### ISSUE TITLE
0.4.0 version App crashing when I set default browser as Samsung Internet

### ISSUE THREAD

**Issue by Mayranit** [openid/AppAuth-Android#124]
Hi ,

I upgraded library to version 0.4.0, and created a  AuthorizationService object as below.

```java
packageInfo = pm.getPackageInfo("com.android.chrome",PackageManager.GET_SIGNATURES);
BrowserDescriptor browserDescriptor = new BrowserDescriptor(packageInfo,true);
authService = new AuthorizationService(this,createConfiguration(browserDescriptor));

 private AppAuthConfiguration createConfiguration(
            @Nullable BrowserDescriptor browser) {
        AppAuthConfiguration.Builder builder = new AppAuthConfiguration.Builder();

        if (browser != null) {
            builder.setBrowserMatcher(new ExactBrowserMatcher(browser));
        }

        return builder.build();
    }
```

Then used this authService object to call performAuthorizationRequest method. Once it goes to performAuthorizationRequest method in AuthorizationService class , It is throwing activity not found exception. 

Note : When I change the default browser to Chrome, everything works fine. 

Any changes to library log properties ? I set "setprop log.tag.AppAuth VERBOSE" in adb shell, but could not find any logs.

**Comment by iainmcgin** [comment]
It looks like this is a bug, likely one that has existed for a while on M+ devices that we hadn't noticed before due to the previous browser selection behavior. I was missing an additional flag when querying for installed browsers, and as a result if a default browser is set on the device then only that browser would be used. See #125 for the fix, I'll try and cut a 0.4.1 release with this fix today.

**Comment by Mayranit** [comment]
Hi McGinniss,

any update on 0.4.1 release date ? Thanks

**Comment by iainmcgin** [comment]
Hey @Mayranit,

Apologies for the delay, 0.4.1 is now released.

**Comment by Mayranit** [comment]
Hello @iainmcgin ,

I updated library and checked for this particular scenario, Works fine for me. Thanks for the update.
