### ISSUE TITLE
Logout Android app from IdentityServer4

### ISSUE THREAD

**Issue by madhuteja** [openid/AppAuth-Android#127]
I have an Android app developed in JAVA. For this app I am using the [IdentityServer4](https://github.com/IdentityServer/IdentityServer4) as my STS and everything is working fine. But i couldn't find any implementation to logout in AppAuth library. Can anyone help me on this? I really need the logout option in my app, so the users can logout from the app when ever they want and log back in again.
Any ideas, samples would be greatly appreciated.

**Comment by iainmcgin** [comment]
"Logout" is usually as simple as just discarding the refresh token or `AuthState` object you are retaining. If, however, you are looking for "single sign-out" which also signs the user out of the web and other apps using the same account, see #50 - this is not yet a standardized feature in OpenID Connect, so we do not yet wish to include direct support for this in the library. However, with some refactoring, I should be able to make it easier to write an extension library to support this.

**Comment by akshuu** [comment]
@iainmcgin  Is there an API in the library to invalidate the Refresh token/Authstate or should we do it in our App?

**Comment by iainmcgin** [comment]
No, there is nothing in the library to do this because there is no standard mechanism to do this - it's provider specific.

**Comment by akshuu** [comment]
no, i meant how do i invalidate the Refresh tokens(from the App-Auth library)

**Comment by iainmcgin** [comment]
As I said, there is no way to invalidate them. All you can do is stop retaining a copy of the AuthState object.
