### ISSUE TITLE
Release schedule question

### ISSUE THREAD

**Issue by witrisna** [openid/AppAuth-Android#136]
May I know the next release schedule for Android AppAuth?

**Comment by iainmcgin** [comment]
I normally cut new releases on an as-needed basis, as we haven't had much time to push forwards on new features over the last few months. Is there a particular change or feature you are waiting for in an official release?

**Comment by witrisna** [comment]
I am looking for the feature in pull request [133]("https://github.com/openid/AppAuth-Android/pull/133).
Please let me know if you have any questions.

**Comment by iainmcgin** [comment]
It looks like there are a few pending issues that people really want in a new release, so I'll incorporate changes and push a new 0.5.0 release by the end of this week.

**Comment by iainmcgin** [comment]
0.5.0 has now been released.
