### ISSUE TITLE
Online Javadoc appears out of date

### ISSUE THREAD

**Issue by 3flex** [openid/AppAuth-Android#140]
http://openid.github.io/AppAuth-Android/docs/latest/ appears to be out of date, and doesn't show docs for many recently added classes.

**Comment by iainmcgin** [comment]
I keep forgetting to push updated docs when I make new releases; I really should automate this. I'll update it manually when I push the next release (0.5.0).

**Comment by klim76** [comment]
0.5.1 already ...

**Comment by 3flex** [comment]
I'm not sure what has to be included in the artifact build, but javadoc.io can automatically host for you. Can add this badge to the README and then wouldn't have to worry about it:

[![Javadocs](http://javadoc.io/badge/net.openid/appauth.svg)](http://javadoc.io/doc/net.openid/appauth)

The markup is: `[![Javadocs](http://javadoc.io/badge/net.openid/appauth.svg)](http://javadoc.io/doc/net.openid/appauth)`

Something is apparently missing from what's loaded to Maven so it currently doesn't show anything.

**Comment by iainmcgin** [comment]
@3flex excellent tip! It looks like we're probably just missing the Javadoc JAR. I'll try and generate and upload this as part of the next release.

**Comment by iainmcgin** [comment]
Update on this: we need to push everything to Maven Central for javadoc.io to work; I've got approval to do this from Sonatype but I need to ensure our Maven POM is compliant.

**Comment by iainmcgin** [comment]
0.7.0 has been sync'd to Maven Central, so the Javadoc is now available via javadoc.io:

http://javadoc.io/doc/net.openid/appauth/
