### ISSUE TITLE
Order of README is confusing to me

### ISSUE THREAD

**Issue by 3flex** [openid/AppAuth-Android#141]
I'm suggesting a re-ordering of some sections of the README to make it a little easier to follow for new users, as I had a bit of trouble last week when I first started looking at this library. I think this order may help it flow better:

* Basic usage (this is a new section header)
  * Configuration
  * Authorizing
  * Handling the Redirect
  * Tracking authorization state
* Advanced usage (this is a new section header)
  * Client configuration (new section, containing the `AppAuthConfiguration` example that's currently in the Configuration section)
  * Dynamic Client Registration

I'm not sure whether the "making API calls" section should be in Basic or Advanced usage (I'm leaning towards advanced, but that's only because the OAuth implementation on the server I'm connecting to is basic and doesn't support refresh tokens). I'm leaning towards "advanced" for that reason - refresh tokens are optional part of the specification and shouldn't be part of the "basic usage" section which shows what would be required for any barebones implementation.

I'm happy to whip up a PR for this based on any feedback people have. Thanks!

**Comment by iainmcgin** [comment]
It's been a while since I've reviewed the README to make sure it still makes sense, so when I get a chance I'll go through it and incorporate your changes where it makes sense. Thanks!

**Comment by iainmcgin** [comment]
The main README has now been updated, hopefully it is much clearer now. Please open another issue if there are specific sections you'd like me to revise.
