### ISSUE TITLE
appauth.keystore is not generated

### ISSUE THREAD

**Issue by ontherunvaro** [openid/AppAuth-Android#145]
I'm trying to follow these instructions:
https://github.com/openid/AppAuth-Android/blob/master/app/README.md

In them, the following is explained:
`After building the app (./gradlew assembleDebug), the appauth.keystore file contains the certificate...`

However, after running `./gradlew assembleDebug` successfully, there is no `appauth.keystore` file in the project (checked by running `find`).

**Comment by iainmcgin** [comment]
Whoops, I broke this when pulling in some build file cleanup from another project I'm working on. Will fix.

**Comment by iainmcgin** [comment]
This is now fixed.
