### ISSUE TITLE
Support "ui_locales" OpenID Connect auth request parameter

### ISSUE THREAD

**Issue by iainmcgin** [openid/AppAuth-Android#16]
[OpenID Connect Core 1.0, Section 3.1.2.1](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), `ui_locales` parameter:

> OPTIONAL. End-User's preferred languages and scripts for the user interface, represented as a space-separated list of [BCP47 [RFC5646]](https://tools.ietf.org/html/rfc5646) language tag values, ordered by preference. For instance, the value "fr-CA fr en" represents a preference for French as spoken in Canada, then French (without a region designation), followed by English (without a region designation). An error SHOULD NOT result if some or all of the requested locales are not supported by the OpenID Provider.

**Comment by agologan** [comment]
Available since `v0.9.0`. Closing.
