### ISSUE TITLE
Browser compatibility ?

### ISSUE THREAD

**Issue by mark-urbanthings** [openid/AppAuth-Android#161]
I've implemented authentication in an app and in the simulator all works great. However when I tried it on a device (Samsung S6) it got stuck redirecting back to the app from the browser authentication - the redirect intent never reached the app. With some experimentation I got it working by whitelisting browsers to just CHROME_BROWSER, FIREFOX_BROWSER and SAMSUNG_BROWSER (so blacklisting the _CUSTOM_TAB browsers). Can someone explain what the issue is and whether limiting like this is going to cause any issues on devices without these browsers? Anything else I should be doing? Thanks...

**Comment by iainmcgin** [comment]
There was a bug in the Samsung Browser (see #116) that may be responsible for your woes, though I thought it had been fixed. I don't have a Samsung test device to hand. 

Blacklisting the browser may cause some issues with user signed-in state. AppAuth retrieves a list of browsers from the OS ordered by user preference, which typically means their default browser first, then all others in some pseudo-random order. It then looks down that list in order for the first browser that supports custom tabs and matches the browser filter; failing that, it returns the first browser.

On many Samsung devices, both SBrowser and Chrome will be installed. If you blacklist custom tabs on just SBrowser, I would expect AppAuth to launch the authorization flow in a Chrome custom tab. If the user normally uses SBrowser, then they may not be signed in to their account in Chrome, and have to sign in again. You could avoid this by writing a BrowserMatcher that returns false for any BrowserDescriptor that has `useCustomTab` set to true. This will then launch the user's default browser without use of a custom tab.

If you don't expect the user would have signed in to the service you are authorizing against, then just blacklisting custom tab usage on SBrowser should be sufficient.

**Comment by mark-urbanthings** [comment]
Thanks for the input!
