### ISSUE TITLE
Add the ability to warm up the custom tab for Authorization Requests

### ISSUE THREAD

**Issue by WilliamDenniss** [openid/AppAuth-Android#162]
Custom Tabs offer a [warm up](https://developer.android.com/reference/android/support/customtabs/CustomTabsClient.html#warmup(long)) feature. We should expose this in AppAuth to allow developers to warm-up authorization requests.

**Comment by iainmcgin** [comment]
By default, we create a CustomTabsClient instance when creating an AuthorizationService and warm it up, and each call to performAuthorizationService will use a [CustomTabsIntent](https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.html) attached to a new [CustomTabsSession](https://developer.android.com/reference/android/support/customtabs/CustomTabsSession.html). This gets most of the benefit of ensuring the browser is already instantiated, but it's missing the final optimization of suggesting a URL that is likely to be loaded, if known. We could do this by exposing more of the innards of [CustomTabManager](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/CustomTabManager.java).
