### ISSUE TITLE
Configuring demo App

### ISSUE THREAD

**Issue by ve7jtb** [openid/AppAuth-Android#167]
in build.gradle you have the comment 
// replace the below string with your own Google client ID. Make sure this is consistent
        // with the values used in idp_configs.xml

By experimentation I determined that you intended that to be the custom scheme of the redirect_uri and not the client ID.

Saying something like Replace this with the leftmost part (scheme) of the redirect_uri. 
eg 'com.googleusercontent.apps.(your client id)'  No trailing : or /

John B.

**Comment by iainmcgin** [comment]
Agreed, I think #163 will probably cover this by making the demo app less google-flavored once merged.

**Comment by iainmcgin** [comment]
#185 has stripped the demo app of Google specific references, and has hopefully made configuration much simpler. If you find anything else, let me know.
