### ISSUE TITLE
TokenRequestTask does not have an Accept: applicaiton/json header

### ISSUE THREAD

**Issue by wolfordj** [openid/AppAuth-Android#174]
It appears that the TokenRequestTask will only parse a JSON body. However, APIs like GitHub only return a JSON token if the Accept: application/json header is present, otherwise it returns a url encoded body. It seems that if only JSON is acceptable, this header should be added or at least the ability to add custom headers if needed.

**Comment by iainmcgin** [comment]
We used to set this header as it is relatively harmless. It looks like we accidentally removed it in #41, I will reinstate it.

Side note: GitHub is not OAuth2 spec compliant; this header really shouldn't be necessary. They also use a non-standard format for the scope string. So, be wary that you may bump into other instances of where GitHub integration doesn't work well using AppAuth - we can tolerate making small changes to support them, but won't support completely off-spec behavior. We have contacted GitHub previously about these issues, they acknowledge them, but it has not been a priority for them to fix them.

**Comment by iainmcgin** [comment]
Ah, also worth noting: you can actually already set extra headers and generally modify the requests sent in two ways:

1. Provide an AppAuthConfiguration with a custom ConnectionBuilder to AuthorizationService.
2. Provide a custom ClientAuthentication when performing the token request.

Both are abuses of the API, but if you need a quick fix until I roll a new version of AppAuth, these are available to you.
