### ISSUE TITLE
Dismiss custom chrome tabs on user action

### ISSUE THREAD

**Issue by akoskeszeg** [openid/AppAuth-Android#177]
We are using AppAuth-Android in our application to handle authentication. Currently we are using it to authenticate and not for authorization so we don't have approval page. After a successful authentication the custom chrome tabs dismissed and the redirect activity is called with the redirect uri.

Our problem is when a user is prompted to save his password by Chrome, the user hasn't got the time to respond.  

Any thoughts how can we get any information when 'save password alert' has been prompted?

Is it even possible to get these kind of information from custom chrome tabs?

Thanks.

**Comment by iainmcgin** [comment]
No, you can't receive any web-related events from within the custom tab - it is opaque for security reasons. There's not anything you can do about this from within your app, all you can do is try and add steps to the web flow while the custom tab is still active. For instance, show a "welcome back" page with a button to return to the app that forwards the auth response - requiring this explicit action would give the user time to see any possible prompt to save a credential, before continuing.

**Comment by akoskeszeg** [comment]
That was my gut feeling. Thanks for the clarification.
