### ISSUE TITLE
dealing with the lack of client secret for refresh token

### ISSUE THREAD

**Issue by panva** [openid/AppAuth-Android#178]
Hello,

attempting to use AppAuth for android i ran into several issues with my server implementation. First off, my server supports PKCE but does not enforce it for application_type native clients, since my assumption was that clients supporting PKCE are protecting their requests with code challenge IN ADDITION to regular secret and otherwise oauth2 handling applies as a fallback([rfc7636#section-5](https://tools.ietf.org/html/rfc7636#section-5))

Now seeing a pretty awesome (thank you!) AppAuth-Android implementation it looks like my IN ADDITION assumption is wrong since without dynamic registration there is no way to configure a secret in your library. So my thinking is i will still validate client_secret in my server when one is provided, but otherwise assume code_verifier should be present and verified appropriately.

This pretty much deals with grant_type=authorization_code token requests, but what about refresh_token? There is no secret and there is no mention of, in the spec or in the code, of sending the previous code_verifier again with the refresh token request.

Obviously securing refresh token call with client secret brings no security, so might as well just verify that the provided native client_id belongs to the provided refresh token and be done with it(respond with tokens). But couldn't/shouldn't the same code_challenge and code_challenge method be used for the refresh token grant authorization?

So my question is, how is grant_type=refresh_token actually secured when no secret and no code verifier is sent?

**Comment by panva** [comment]
@iainmcgin this answers my questions, thank you.

**Comment by panva** [comment]
I may be out of line here to ask, but just quickly going through token binding it seems impossible to implement for AS behind TLS offloading servers/proxies such as nginx, caddy, heroku router or aws API gateway that does not have a direct connection with the client but rather with aforementioned proxy.

**Comment by iainmcgin** [comment]
I'm not sure, Dirk Balfanz would definitely be the person to ask - I'll see if I can solicit an opinion from him. It may require that the SSL Terminator is able to carry additional state through to the authorization server that it could use to validate the client.

**Comment by panva** [comment]
Why is the handling different for dynamic registration clients (sends client_secret using the right auth method) from static client, that do not support client secret and hence auth method at all?

Server side this creates quite a lot of hassle, making PKCE implementation not a simple extension, but rather a bunch of condition checks when client authentication can be deffered to pkce, even messier with refresh_token when there is no additional parameter in the body to detect used PKCE. Relaxing a bunch of MUSTs in OIDC etc.

Since auth method and secret handling is in the library already, why can't it just be configured for pre-existing clients?

**Comment by iainmcgin** [comment]
I may not be understanding your question correctly, but you can pass a ClientAuthentication instance to performTokenRequest to add headers and request parameters. This also means you can directly pass an instance of [ClientSecretBasic](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/ClientSecretBasic.java) or [ClientSecretPost](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/ClientSecretPost.java) in order to do send a client secret from a static client. We really don't recommend or advertise this, as such secrets are easily extracted from APKs.

**Comment by iainmcgin** [comment]
Oh, if there are real inconsistencies in the behavior between iOS and Android variants of AppAuth, please do let myself or @WilliamDenniss know. The feature sets are drifting due to the different pace and focus of each library, but we do try to ensure they produce the same behavior for the features they have in common.

**Comment by panva** [comment]
Yes I can pass an instance to authentication request, i figured out as much. But then it is missing for performActionWithFreshTokens, making a combination of client_secret_post defined on the server and refreshTokenAdditionalParams with client_secret the only option.

**Comment by iainmcgin** [comment]
Ah, now that seems to be a genuine oversight. We should allow passing a ClientAuthentication instance to performActionWithFreshTokens - I'll open an issue for that.

**Comment by panva** [comment]
Well, that would for sure make it easier to explain to my RPs developers, thank you!

I have one additional quirk to pick up (with Android only since client_secret_basic is not supported by iOS), when client_secret_basic is used, should client_id still be submitted in the post body?

> https://tools.ietf.org/html/rfc6749#section-2.3
> The client MUST NOT use more than one authentication method in each request.

At least in my server implementation encountering an authorization header and client_id or secret in the body throws an error, enforcing this MUST NOT.

**Comment by iainmcgin** [comment]
The spec doesn't appear to be particularly clear on this point, though I think I agree with your conclusion that we should not be sending client_id if we are using a client secret.

From [Section 4.1.3](https://tools.ietf.org/html/rfc6749#section-4.1.3) on auth code exchange:

> client_id: REQUIRED, if the client is not authenticating with the authorization server as described in Section 3.2.1.

... where [Section 3.2.1](https://tools.ietf.org/html/rfc6749#section-3.2.1) says:

> A client MAY use the "client_id" request parameter to identify itself when sending requests to the token endpoint.  In the "authorization_code" "grant_type" request to the token endpoint, an unauthenticated client MUST send its "client_id" to prevent itself from inadvertently accepting a code intended for a client with a different "client_id".

So, if we're currently sending client_id when client authentication is in use, I think that's a bug. If that's what you're seeing in testing, please open an issue for it.

**Comment by b---c** [comment]
Just wanted to note that there is some work being done in the IETF with respect to how token binding can work when an AS or other app are deployed behind TLS offloading servers/proxies. The draft is ["HTTPS Token Binding with TLS Terminating Reverse Proxies"](https://tools.ietf.org/html/draft-campbell-tokbind-ttrp-01), which "defines common HTTP header fields that enable a TLS terminating reverse proxy to convey information about the validated Token Binding Message sent by the client to a backend server, which enables that backend server to bind, or verify the binding of, cookies and other security tokens to the client's Token Binding key."
