### ISSUE TITLE
Does it work with 2-legged OAuth (implicit grant) ?

### ISSUE THREAD

**Issue by morphine9** [openid/AppAuth-Android#183]
Finding a strange situation where in 2-legged oauth, the intent that "TokenActivity" receives for a successful authorization call only contains serialized request and not the response.

Debugging [here in AuthorizationManagementActivity](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationManagementActivity.java#L294) when you log the serialized response it only contains request code and not the successful response (we can compare the successful response from logging the `responseUri` which is supplied as the parameter)

**Comment by iainmcgin** [comment]
The library is not designed for the implicit flow, which has poor usability characteristics for native apps - as it only provides access tokens, acquiring new tokens will always require using a custom tab.

Having said this, it may be possible to get the implicit flow to work. We don't currently attempt to parse the fragment, where the response would be contained. I have also not tested whether fragments are actually provided as part of the intent when an app intercepts an http(s) URL.

**Comment by morphine9** [comment]
Thanks.
