### ISSUE TITLE
Correct minSdkVersion

### ISSUE THREAD

**Issue by govorovsky** [openid/AppAuth-Android#186]
Documentation says that minSdkVersion for library is 16
> AppAuth supports Android API 16 (Jellybean) and above. 

but in build.gradle file it is set to 15 
> project.ext.minSdkVersion = 15

so, library can be successfully included in project with minSdk 15 and no warning will appear.
Which definition is correct? Can AppAuth be used in project with minSdk 15 ?

**Comment by iainmcgin** [comment]
I actually just fixed this with #185. API 15 came from the minSdk for the Chrome custom tab library, but in reality, there are no browsers that support custom tabs that run on anything below 16.
