### ISSUE TITLE
Master branch cannot be compiled due to Jack

### ISSUE THREAD

**Issue by ndorigatti** [openid/AppAuth-Android#190]
I could not find a solution so I had to get back to tag 0.5.1 (which is worse than this version), because there is no way to compile the app.
Android studio complains about jack files and jack dirs in intermediate folders (can't understand what is wrong, it says that index file does not exists).

Disabling Jack does not solve (code is Java8 focused).
jackInProcess does not help
Using Android studio 2.3 stable and build tools 25.0.2

Any help on this please?
I think the support of jack is not a very good idea, since it is still experimental and this project should help on having a Working example of OpenId authentication... 🤕

**Comment by iainmcgin** [comment]
Sorry you're having problems. Jack is no longer experimental, so it would be worth trying to diagnose this issue further and report a bug to the Jack team if necessary.

Please see the [troubleshooting section](https://source.android.com/source/jack.html#jack_troubleshooting) of the Android docs to see if any of those suggestions help. If not, please do a clean build from the command line and send me the build log:

```
./gradlew -d -s clean check assemble
```

**Comment by ndorigatti** [comment]
ah ha, i didn't know about the "promotion" of Jack! Thanks for pointing it out! 
I moved back to an older version of the sample app, but I will get back and try to execute command line commands (Android Studio Clean UI task did not fix the issue)

**Comment by iainmcgin** [comment]
You would be able to get the output I need from within Android studio, it's just easier to copy it out of the command line output so I can see what's happening.

**Comment by ndorigatti** [comment]
Should we re-start the discussion? 
http://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html?m=1

Just joking, but it's a today update

**Comment by iainmcgin** [comment]
Well, just when I think I know what's going on, the situation changes:

https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html?m=1

Jack is deprecated, so I'll strip it out of the demo for the 0.6.0 release.

**Comment by ndorigatti** [comment]
I would wait for the update supporting j8 natively, otherwise you have to convert java 8 code too!
I hope it will take no longer than 2 weeks

**Comment by iainmcgin** [comment]
I can probably put in retrolambda until the official support comes, I have no idea how long it will take :/
