### ISSUE TITLE
Issue with access denied during build

### ISSUE THREAD

**Issue by vikasmarath** [openid/AppAuth-Android#195]
Hi

I get an error in gradle stating access denied for the folder config

Error:(26, 0) D:\AppAuth-Android-master\config (Access is denied)
<a href="openFile:D:\AppAuth-Android-master\build.gradle">Open File</a>

**Comment by iainmcgin** [comment]
Can you run

`gradlew.bat clean check`

From the command line and provide me the full output log?

**Comment by salorwang** [comment]
@iainmcgin 
i met the same problem yet. 
[idea.txt](https://github.com/openid/AppAuth-Android/files/852331/idea.txt)

**Comment by vikasmarath** [comment]
Thanks i could solve thos problem, when pulled the code from git rather than the zip download of code

**Comment by iainmcgin** [comment]
@salorwang your log does seem to indicate you don't have the complete set of sources required to build the demo app. Either clone the repository using git, or download the complete sources:

https://github.com/openid/AppAuth-Android/archive/master.zip

**Comment by rahulsingh0089** [comment]
See the complete log after download and import in android studio then also getting the same error access denied config  folder:
AppAuth-Android-master\config (Access is denied)
[idealog.txt](https://github.com/openid/AppAuth-Android/files/863602/idealog.txt)

**Comment by ramireddy41** [comment]
Thanks @vikasmarath I also could solve thos problem, when pulled the code from git rather than the zip download of code
