### ISSUE TITLE
Google complains "authorization requests in embedded browsers will be blocked" despite using AppAuth

### ISSUE THREAD

**Issue by dg76** [openid/AppAuth-Android#196]
Hi!

Thank you for developing this library! I came here and started to use the library due to Google's changes of the OAuth authentication process and their recommendation to use this library:

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

However despite using this library and seeing that the "Browser" app is opened, I get a warning on some devices saying "Notice for developers: authorization requests in embedded browsers will be blocked on April 20, 2017".

It seems to me that it incorrectly thinks I would be using an embedded browser whereas I am using the system browser (e.g. on a Samsung Galaxy Nexus with Android 4.3).

Do you know anything about this? Will it still think that an embedded browser is used on April 20th and then block the access despite the system's browser is used (and not an embedded browser)?

I know that it is probably a problem on Google's servers and not a problem of this library but maybe you have heard something about it or maybe some Google developers are working on this library here, too?

BTW, it works fine when installing Google Chrome on the device.

Thank you very much!

Kind regards

Dominique

**Comment by ve7jtb** [comment]
Yes that is a problem on the google side with matching browser strings.

Perhaps Ian or William can pass that along to the correct people.

Thanks for reporting it.

John B.

**Comment by iainmcgin** [comment]
I'm working with the WebView deprecation engineers on this. We detect WebViews based on the user agent string and some additional headers, we are likely just miscategorizing the system browser on your device as a web view.

**Comment by iainmcgin** [comment]
We have determined that the package name associated with the stock browser on Nexus devices specifically was missed from the whitelist. A fix for this is in the pipeline, we expect it will be live in production next week. I'll close this issue now, please reopen if the issue persists after 2017-03-24.

**Comment by dg76** [comment]
It works fine now for the "Samsung Galaxy Nexus with Android 4.3" but the warning is still displayed on an Android emulator with the "Android 4.0.3 (with Google APIs)" system image. Can this be fixed, too?

Thank you very much!

Kind regards

Dominique
