### ISSUE TITLE
Config Access denied

### ISSUE THREAD

**Issue by rahulsingh0089** [openid/AppAuth-Android#202]
After importing app-auth aap in nadroid studio then getting error ---
AppAuth-Android-master\config (Access is denied)

Please check, why we getting this problem.

**Comment by iainmcgin** [comment]
Duplicate of #195.

**Comment by rahulsingh0089** [comment]
See the complete log

[idealog.txt](https://github.com/openid/AppAuth-Android/files/863601/idealog.txt)
