### ISSUE TITLE
Getting Issue fro Config access denied

### ISSUE THREAD

**Issue by rahulsingh0089** [openid/AppAuth-Android#204]
See the complete log after download and import in android studio then also getting the same error access denied config folder:
AppAuth-Android-master\config (Access is denied)
[idealog.txt](https://github.com/openid/AppAuth-Android/files/863675/idealog.txt)

**Comment by iainmcgin** [comment]
Does that config directory exist, and is it accessible by the user you are running Android studio as?

**Comment by rahulsingh0089** [comment]
Yes config directory is exist and it contains one checkstyle sub-folder and all gradle files. I am using android studio 2.3 and gradle 3.3 .

**Comment by krantivijay** [comment]
I am also having the same issue.

**Comment by krantivijay** [comment]
Please suggest how to resolve this..

**Comment by iainmcgin** [comment]
I've never seen the issue myself, everyone affected appears to be developing on Windows. I'll see if I can reproduce on a Windows machine myself.

**Comment by rahulsingh0089** [comment]
Plz help us as soon as possible because its urgent? I am using windows 7 Professional.

**Comment by iainmcgin** [comment]
Why is it urgent? You only need to be able to build AppAuth from source if you are planning to make contributions; otherwise, you can just add a gradle dependency on the library.

**Comment by iainmcgin** [comment]
I can't reproduce this issue - just tried using the following steps on Windows 10:

- Installing Android Studio 2.3 
- Cloned the repository: `git clone https://github.com/openid/AppAuth-Android.git appauth`
- Imported the imported project into Android studio.

Everything works fine. So, this appears to be issues specific to your own development environment that we can't help with.
