### ISSUE TITLE
Doesn't work on Note 3

### ISSUE THREAD

**Issue by dg76** [openid/AppAuth-Android#205]
Hi!

I have tried the latest version, 0.5.1, with several users with several different devices. It seems to work fine for all of them except for a person with a Samsung Note 3 with Android 5.0. She said it worked fine on her tablet with Android 4.4. but on her Samsung Note 3 with Android 5.0 a Google start page (I think she means the Google search page) appears after tapping the "Allow" button. I.e. it seems to stay in the browser. Have you heard about this problem? Can it be fixed?

Thank you very much!

Kind regards

Dominique

**Comment by iainmcgin** [comment]
This usually happens if a custom scheme redirect fails: after a short timeout if the browser tab is not closed, the authorization page redirects to the google search home page. I would look at the logs on the device to see exactly what is happening.

**Comment by dg76** [comment]
I don't have the device myself, it is a user of my application who has the problem. Do you mean the system log ("adb logcat")? Is there a way to retrieve it without using the developer tools? As far as I remember newer Android versions restricted the access to it.

**Comment by iainmcgin** [comment]
You would need access to the system logs from adb logcat, so if you don't have access to the device, there's not a lot you can do. Without more information as to why the redirect is not being processed, I also can't help any further. If you manage to get logs from the device, please reopen this issue.
