### ISSUE TITLE
Missing support for client secret

### ISSUE THREAD

**Issue by suparng-medallia** [openid/AppAuth-Android#208]
I couldn't find any documentation on this. In iOS, I am able to perform an authorization request which requires client secret. However, the same functionality seems to be missing from Android.

**Comment by iainmcgin** [comment]
You can provide a ClientAuthentication instance in your call to performTokenRequest to provide a client secret, though do this at your own risk: client secrets _should not be used_ from mobile applications as they are easily extracted. At best, it weakens your security.
