### ISSUE TITLE
Leaking activity reference from CustomTabManager

### ISSUE THREAD

**Issue by morphine9** [openid/AppAuth-Android#209]
I do call AuthorizationService.dispose() in ondestroy().
Kindly suggest.

![auth3rdparty](https://cloud.githubusercontent.com/assets/836651/24530132/c77754c8-1564-11e7-8a39-9ebea3581564.jpeg)

**Comment by iainmcgin** [comment]
I'll change the reference to the context in CustomTabManager to a WeakReference.

**Comment by iainmcgin** [comment]
Should be fixed by #211.
