### ISSUE TITLE
Support "claims_locales" OpenID Connect auth request parameter

### ISSUE THREAD

**Issue by iainmcgin** [openid/AppAuth-Android#21]
[OpenID Connect Core 1.0, Section 5.2](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsLanguagesAndScripts), `claims_locales` parameter:

> OPTIONAL. End-User's preferred languages and scripts for Claims being returned, represented as a space-separated list of [BCP47 [RFC5646]](https://tools.ietf.org/html/rfc5646) language tag values, ordered by preference. An error SHOULD NOT result if some or all of the requested locales are not supported by the OpenID Provider.

**Comment by agologan** [comment]
Available in `v0.10.0`. Closing.
