### ISSUE TITLE
Closing the chrome browser doesn't pass any AuthorizationException to the Activity

### ISSUE THREAD

**Issue by suparng-medallia** [openid/AppAuth-Android#212]
In iOS, closing the safariViewController by tapping on Done issues an error with Error Code USER_CANCELED_AUTH_FLOW. However, closing the chrome browser by tapping on X button in Android does not pass any exception. The final activity receives both AuthorizationResponse and AuthorizationException as null.

Currently, I assume that if both the values are null in onCreate, then the user/program cancelled the auth flow.

**Comment by iainmcgin** [comment]
You can specify a different intent to be invoked on cancelation - that might give you what you need.
