### ISSUE TITLE
Kitkat Emulator (API 19) - No chrome browser, app chooser pop up

### ISSUE THREAD

**Issue by morphine9** [openid/AppAuth-Android#213]
Is there a way to not have the app chooser pop up (with browser option and app option) when the user completes the authentication ?
![appchooser](https://cloud.githubusercontent.com/assets/836651/24824057/7159a5d0-1bba-11e7-9869-a9ca2b6ac145.jpg)

**Comment by iainmcgin** [comment]
KitKat doesn't support App Links, so if your redirect URI is http(s) based then you will always see this picker. I would recommend using a custom scheme instead for this environment.
