### ISSUE TITLE
AuthException always when coming from RedirectUriReceiverActivity

### ISSUE THREAD

**Issue by dejoe-infrrd** [openid/AppAuth-Android#217]
The application has a custom URI structure something like this app://login as the redirectUri.
 I have mentioned this in the manifest to specify that scheme and host is for the ReceiverActivity.
But when I try to do
`AuthorizationResponse response = AuthorizationResponse.fromIntent(getIntent());
  AuthorizationException ex = AuthorizationException.fromIntent(getIntent()); `

The response is always null even though the request params are correct.
This is the redirectUri `
app://login#code=c3eaf063553b927d0ba4fe9e7ba4727966eed65b5fd3736bd7c62696e459eb84&id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjVhMjhlYzhiMzJhMmNlOWQwNGIxZTNlZjJiODZlNjRiIiwidHlwIjoiSldUIn0.eyJuYmYiOjE0OTI1NzkzNzgsImV4cCI6MTQ5MjU3OTY3OCwiaXNzIjoiaHR0cHM6Ly90ZXN0aWRlbnRpdHkuaG9tZWdlbml1cy5jb20iLCJhdWQiOiJjb20ucmVkYmVsbHJlLnZlc3RhIiwibm9uY2UiOiJlYjE1ZDIyZC1lMjQ5LTQ0NjktOGI2Zi1jOWE3YzQwN2EwMjUiLCJpYXQiOjE0OTI1NzkzNzgsImNfaGFzaCI6IjBZS3pGQnludmhBY19Id253Q0dVY2ciLCJzaWQiOiIwYzE4ZmZhNjc5YzY3MzQ0YThiOTZmN2Q2MmIxMmVhNSIsInN1YiI6ImE3Yzk5N2NmLTBjZDMtNDBjMy1iNzgxLTc3MjQzNDEyYWMyMCIsImF1dGhfdGltZSI6MTQ5MjU3OTAxMCwiaWRwIjoibG9jYWwiLCJhbXIiOlsicHdkIl19.TVjJahQZH2DFY5COI-Gu7OTyZn9xf3GMuNZzcWNbA-gK2ns969KG87T53j6ShcboTqKcrz4CvlGtBr7RhQjPKGVL7CFQ6r1bYTVflmOu8RRVKxijy8ojlaBAJ43ArhbJ-ZioLsjLgbEt29ljzl61KbXnv3CtG-LqTXDzDq77NINScVprEPhMBJiAWT-ZDo5jUvLrgluBst0xqgsIkCOaIA2puuBivTrEM9fovyX_iwVb9PashgMa32yC1fz77REpBNzLhIyQdQc6m8L123ORqguxQDirjQ6y4FGBaB_2HwA9xw4mZACJkU8OEXrReKUlBRzJNDMCL6zRXGV-s5CSww&scope=openid%20user%20api&state=s9DTQRaES3gksFBI5cv68Q&session_state=MzHeIc_DBw0BgeyuPiayl5oObjf92SIBmEvZ_HesP5w.70a45d8f1a940446ddd1295f5c23d4bb`

If I replace the # after login to `app://login?code=....` , the authResponse is not null anymore. Is there any other fix for this other than replacing the '#' with a '?'?

**Comment by iainmcgin** [comment]
It sounds like you're trying to use the hybrid flow, which passes the response as a fragment rather than a query. We don't support this, and we are not sure if it is worth adding support for. See #75.

**Comment by ve7jtb** [comment]
The redirect Uri is for the "code id_token" response_type.
If you change that to code then you get the id_token from the token endpoint.  

When using PKCE this prevents id_tokens from leaking. 

If you must pass the id_token on the front channel you could try using the post response mode that would encode the id_token in the form body.    I haven't tried it so it may break horribly as well.

Best solution is use the code response type.   Is there some reason the IdP you are using doesn't support that?

John B.
