### ISSUE TITLE
Application moves to background when customtab responds with 302

### ISSUE THREAD

**Issue by ealogar** [openid/AppAuth-Android#220]
When the application launches the customtab to get the authorization code and the IDP (other than google) responds directly with a 302 redirect (no interaction of user) the application moves to background (not closed). This is the situation where you have already been authenticated in the IDP and a valid cookie exists.
If you click the app, the code is obtained and the request token renewed ... It would be great if the behaviour were to not moving the main app to background.
Any help or workaround would be appreciated

**Comment by iainmcgin** [comment]
Is your redirect URI a custom scheme or an https app link? Chrome typically _requires_ that a user click occur to reliably redirect back to the app. However, I'm a little confused by your description that the token is received anyway, once you switch to the app. Can you record a video of the flow to demonstrate the issue?

**Comment by ve7jtb** [comment]
Are you using custom scheme redirect URI or app links?

**Comment by ealogar** [comment]
Thanks for your quickly answer.

I am using app link as custom redirect uri. If i use google as idp, everything is working fine but always a use click is required. With my own idp no use click happens when the use is already authenticated. 

I will try to investigate more about the redirect uri but I remark the fact that the first time (when the user types password) the redirect back to application works well.

It seems that the main application moves to background (not killed) and the custom tab after the redirect 302 not give back the control well. Any ideas of move the main app to front. I have added a callback in CustomTabManager to detect the browser_tab close event. It would be nice if at that point I could do something. I am new making android apps and can not figure out how to make.

If i have time i make a video

**Comment by iainmcgin** [comment]
What you are describing is a known restriction in Chrome - redirects to deep links _must_ occur from a user action, like clicking on a button or link. If they do not, then Chrome retains control of the deep link. I've described this a few times in previous issues (e.g. [here](https://github.com/openid/AppAuth-Android/issues/187#issuecomment-285546334)).

The simplest fix is to set up an interstitial page for your redirect, that captures the authorization response and displays a "welcome back" type prompt with a button to return to the app. I have a demo of this here:

https://github.com/iainmcgin/AppAuth-Demo
