### ISSUE TITLE
Please copy this code, switch to your application and paste it there:

### ISSUE THREAD

**Issue by s-gagandeep** [openid/AppAuth-Android#222]
hello i am trying to integrate google calender using AppAuth and 
getting "Please copy this code, switch to your application and paste it there:"
Earlier i am using Webview and in onPageFinished, i retreive this token and again load browser using this token, but how can i proceed using AppAuth.
Thanks

**Comment by iamshubh** [comment]
Hey @s-gagandeep I am facing this particular issue, you found any way to resolve it
