### ISSUE TITLE
Not redirected when using browsers other than chrome(custom tab)

### ISSUE THREAD

**Issue by vikasmarath** [openid/AppAuth-Android#223]
Hi 
I am unable to login successfully using other browsers such as firefox or opera when using yahoo and outlook domains
The last screen the i can see is the user consent screen, once i click on allow, then a blank page is displayed
Below are the configurations i use with clientid and secert key, which i have not mentioned below

Outlook 
{
  "redirect_uri": "https://login.microsoftonline.com/common/oauth2/nativeclient",
  "authorization_scope": "wl.offline_access wl.imap wl.emails",
  "discovery_uri": "",
  "authorization_endpoint_uri": "https://login.live.com/oauth20_authorize.srf",
  "token_endpoint_uri": "https://login.live.com/oauth20_token.srf",
  "registration_endpoint_uri": "",
  "https_required": true
}
Yahoo
{
  "redirect_uri": "https://localhost/",
  "authorization_scope": "mail-x sdps-w",
  "discovery_uri": "",
  "authorization_endpoint_uri": "https://api.login.yahoo.com/oauth2/request_auth",
  "token_endpoint_uri": "https://api.login.yahoo.com/oauth2/get_token",
  "registration_endpoint_uri": "",
  "https_required": true
}

Please let me know if any particular changes needs to be made

**Comment by iainmcgin** [comment]
The redirect URIs look incorrect in both cases. You should use a domain which you control, and the redirect URI must be registered as a deep link to your app (see [here](https://github.com/openid/AppAuth-Android/blob/master/app/AndroidManifest.xml#L65) in the demo app). Also be aware that deep links do not work well on other browsers, particularly prior to Android M. To handle these cases, have a page served by your web server for the redirect URI that can redirect to a custom scheme that your app registers.

**Comment by vikasmarath** [comment]
In my application i use the below activity with the redirect-uri as mention for outlook, but still the redirect does not happen

But when its with the custom tab chrome this redirect works.

<activity android:name="application-packagename.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="https"
                  android:host="login.microsoftonline.com/"
                  android:path="common/oauth2/nativeclient>
            </intent-filter>
        </activity>

**Comment by iainmcgin** [comment]
Don't try and register a Microsoft domain as your redirect URI. Use your own domain, and as mentioned in my last response, have a custom scheme redirect as a backup.

**Comment by vikasmarath** [comment]
For example i changed the my files as below

json file
"redirect_uri": "https://appauth.demo-app.io/oauth2redirect",
  "authorization_scope": "wl.offline_access wl.imap wl.emails",
  "discovery_uri": "",
  "authorization_endpoint_uri": "https://login.live.com/oauth20_authorize.srf",
  "token_endpoint_uri": "https://login.live.com/oauth20_token.srf",
  "registration_endpoint_uri": "",
  "https_required": true

manifest file
 data android:scheme="https"
                  android:host="appauth.demo-app.io"
                  android:path="/oauth2redirect"/

I get an error in the browser "We're unable to complete your request"

**Comment by vikasmarath** [comment]
with the above changes i could somehow manage to reach a screen which says
Authorization response received
Reurn to app - Button(which is not functional)

**Comment by iainmcgin** [comment]
It doesn't sound like you know what the redirect URI is for. Please go read about OAuth2.

**Comment by vikasmarath** [comment]
I need help to understand how exactly the redirect-uri works and how do we create a custom redirect uri
