### ISSUE TITLE
Having trouble implementing login

### ISSUE THREAD

**Issue by raqueljb** [openid/AppAuth-Android#237]
Hi everyone,
I am trying to use the example app to implement the login on my OAuth2 server (Keycloak).
I  am not sure on what to write in the .json file, specifically, in "authorization_endpoint_uri","token_endpoint_uri" and "registration_endpoint_uri".
Could somebody explain to me which would be those URL?

This is my config file so far. When I try to log in, it appears my administrator login page.
```
{
  "client_id": "PowerApp",
  "redirect_uri": "https://appauth.demo-app.io/oauth2redirect",
  "authorization_scope": "openid email profile",
  "discovery_uri": "",
  "authorization_endpoint_uri": "http://192.168.1.108:8080/auth",
  "token_endpoint_uri": "http://192.168.1.108:8080/auth",
  "registration_endpoint_uri": "http://192.168.1.108:8080/auth",
  "https_required": false
}
```

Thank you!

**Comment by iainmcgin** [comment]
You'll need to consult the documentation for KeyCloak - [this StackOverflow question](https://stackoverflow.com/questions/28658735/what-are-keycloaks-oauth2-openid-connect-endpoints) is probably also helpful.
