### ISSUE TITLE
Google Disallowed UserAgent

### ISSUE THREAD

**Issue by Rajeshr34** [openid/AppAuth-Android#242]
Status:
--------------
Outlook Works. (With/Without Chrome)
Google Works. (Only With/Chrome)

Suppose if i try Oauth (no chrome) using default brower it shows disallowed_useragent. how can i fix this issue.

# Attaching Image (Without Chrome)
![8b9a37e0-9d4e-480c-bb84-4c5f4759e85c](https://user-images.githubusercontent.com/6398275/27529430-14dc7e30-5a72-11e7-8171-7e97c9a84c0f.jpg)

# With Chrome:
![d1b045a6-6ec5-4bcb-aeca-49a01168d0e1](https://user-images.githubusercontent.com/6398275/27529485-4f62a85e-5a72-11e7-9d5e-9a50f290853d.jpg)

**Comment by iainmcgin** [comment]
If you could give me some more information on the system browser I can inform the maintainers of the Google authorization endpoints of this misclassification. Specifically:

- Browser package name and version
- Device model
- Installed OS version

There isn't any way to fix this on your end, other than blacklisting this browser and/or asking the user to install a different browser.

**Comment by Rajeshr34** [comment]
Browser: net.openid.appauth.browser.AnyBrowserMatcher (AnyBrowserMatcher.INSTANCE)
OS: 7.1.1
```
{
  "client_id": "",
  "redirect_uri": "net.openid.appauthdemo:/oauth2redirect",
  "authorization_scope": "https://mail.google.com https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/userinfo.email",
  "discovery_uri": "https://accounts.google.com/.well-known/openid-configuration",
  "authorization_endpoint_uri": "https://accounts.google.com/o/oauth2/v2/auth",
  "token_endpoint_uri": "https://www.googleapis.com/oauth2/v4/token",
  "registration_endpoint_uri": "",
  "https_required": true
}
```

**Comment by iainmcgin** [comment]
That doesn't tell me which browser is actually being used, only what your matcher and client configuration are.

**Comment by iainmcgin** [comment]
Closing due to lack of response.
