### ISSUE TITLE
Always asking for log in after killing the app and opening(not storing authorized state)

### ISSUE THREAD

**Issue by prashanthd** [openid/AppAuth-Android#246]
Hi,
In your android sample after log in successful it is directing to Token activity. But when I close the app and open again it is again asking for log in. Following condition is always failing. I checking in your sdk it is maintaining state in shared pref but  why it is not working.

` if (mAuthStateManager.getCurrent().isAuthorized()
                && !mConfiguration.hasConfigurationChanged()) {
            Log.i(TAG, "User is already authenticated, proceeding to token activity");
            startActivity(new Intent(this, TokenActivity.class));
            finish();
            return;
        }`

**Comment by tikurahul** [comment]
We leave it to the app to decide on how best to serialize `AuthState`, so you can use something like https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthState.java#L639 to write it to `SharedPreferences` or something similar.

**Comment by iainmcgin** [comment]
@tikurahul I think @prashanthd means that the demo app is not correctly handling saved state. This is likely a bug in the demo app; I'll investigate when I get some time.

**Comment by prashanthd** [comment]
@iainmcgin  you are right. Thanks for the update

**Comment by cheercroaker** [comment]
Hi, I experienced the same issue with the demo app and by investigating I saw that state was indeed not correctly saved in the AuthStateManager#writeState method (it was only handling removal).

By saving state correctly, the AuthState#isAuthorized method will behave as expected, so the user do not have to log in again. I was about to submit a pull request but good news is that recent #243 already fixes this :smile:

**Comment by iainmcgin** [comment]
Fix is merged; closing this.
