### ISSUE TITLE
Https redirect_uri URL not triggered inside CCT

### ISSUE THREAD

**Issue by lbalmaceda** [openid/AppAuth-Android#248]
Hello.
I'm trying the sample using [Auth0](https://auth0.com) in a device with Chrome installed. When I launch the authentication a Chrome Custom Tab opens with the `authorization_endpoint_uri` URL set in the configuration JSON, along with the extra parameter `connection=facebook` to indicate the service that I want to use a specific provider instead of showing a widget to choose it from. My `redirect_uri` URL has the same scheme (`https`) and host (`lucianop2.auth0.com`) as the authorize URL, but a different path (`/callback`). As soon as the OAuth flow redirects to the `redirect_uri` the page fails to load with a `Cannot GET /callback` message. **This is happening if the user is already logged in into that provider (i.e. facebook).** If it's a new account or the user logs in that moment, then the redirect works well. Chrome seems to consume that URL instead of checking for an app capable of handling it and launching an explicit intent. I've tried in API versions 16, 19, 23 and 25. Using `AppLinks` doesn't change anything, the error is the same. 

The issue gets weirder when you [remove/comment the connection parameter](https://github.com/lbalmaceda/AppAuth-Android/blob/master/app/java/net/openid/appauthdemo/LoginActivity.java#L446) as that indicates Auth0 to show a widget to choose the provider to log in from. In this case, clicking the `facebook` button works well, even if you're already logged in. I've talked with them and the whole flow it's the same whether you show the widget and click a provider or send the connection parameter.

I've created a [fork](https://github.com/lbalmaceda/AppAuth-Android) for you to clone and try to reproduce the error easily. Things I've changed: [manifest](https://github.com/lbalmaceda/AppAuth-Android/blob/master/app/AndroidManifest.xml#L67-L74) and [config json](https://github.com/lbalmaceda/AppAuth-Android/blob/master/app/res/raw/auth_config.json), along with the extra parameter indicated above.

Two last things to mention:
1. Using a custom scheme (i.e. "myapp" instead of "https") and updating the intent-filter and configuration JSON, seems to work well. But I'm trying to use https and App-Links so this shouldn't be a limitation.
2. When you see the `Cannot GET /callback` message in the CCT, clicking the overflow menu icon and choosing "Open in Chrome" seems to trigger the intent and open the app.

GIF:

http://g.recordit.co/dqAewsiv1Q.gif

Any help or point to it will be appreciated.
Cheers.

**Comment by iainmcgin** [comment]
This sounds like a common issue with app link redirects in Chrome - an explicit user action (typically, a click) is required in order for Chrome to send the URI to an installed app. If the redirect happens automatically without user interaction, Chrome will attempt to render the URI itself.

The workaround I have been suggesting to users of the library is to create a simple interstitial page on their callback URI, which shows a "return to app" button, and have this button redirect to another callback URI that the app has registered. This page will only be shown when the authorization occurs automatically, and will force the user to click on something in order for Chrome to send the redirect to the app.

**Comment by lbalmaceda** [comment]
It makes sense to not redirect to an app outside the browser without a user gesture if the host hasn't been verified. I've found this (old) [article](https://paul.kinlan.me/deep-app-linking-on-android-and-chrome/) that points the changes introduced by chrome lately on the deep-link matter. 

What it doesn't make sense is that even with a successful app-links verification, a https `redirect_uri` doesn't work using CCT (without user interaction) but it does using Chrome or another browser. Personally, I don't like the extra page workaround as I'd prefer that the user doesn't need to click anywhere on the page to take the authentication back to the app. But since the issue seems to persist even with app-links, the only workaround I have left is to use custom schemes for any API level. I've also read that some people perform a "virtual click" on a link to the intent from the web side to trigger the "manual redirect" behavior, but it seems too hacky for me. 👎 

Any clues on why app-links doesn't work (without user interaction) in CCT?

**Comment by iainmcgin** [comment]
The original explanation I got from the Chrome team was that this was for security / privacy reasons, though I don't know why it's inconsistent with the behavior in the main Chrome browser. When I next sync up with the Chrome engineers I'll ask for them to provide more information, and to fix it to be consistent either way.

**Comment by lbalmaceda** [comment]
Thanks!! Please update me when you have more info on this. You can close the issue if you like. 
Cheers.
