### ISSUE TITLE
How do you enable logging?

### ISSUE THREAD

**Issue by biscon** [openid/AppAuth-Android#249]
How do you enable logging? preferably of everything, but particularly wirelogging. I want to see the authentication request etc

**Comment by iainmcgin** [comment]
The library logs things to the "AppAuth" tag, so you can run this command to show everything we log:

```
adb shell setprop log.tag.AppAuth VERBOSE
```

The best way I know to get wire level logs is to use a proxy like [Charles](https://www.charlesproxy.com/) - there's no straightforward way to enable logging for the default HTTPUrlConnection implementation. You can replacement the implementation with okhttp which has better wire logging options, but that requires code changes.

Iain

**Comment by tikurahul** [comment]
You could use Stetho(https://code.facebook.com/posts/393927910787513/stetho-a-new-debugging-platform-for-android)

**Comment by JohnGilbertson** [comment]
The logging available isn't all that helpful for diagnosing the cause of errors. 

For instance I'm getting a "JSON deserialization error", which is fair enough, but utterly unhelpful in knowing what's actually going wrong, and where.

Is the server badly configured and responding with a 200 but plain text error reporting? Is there simply a badly encoded double quote that could be reported to the vendor? Is the remote end just returning blank?

**Comment by iainmcgin** [comment]
We'd be happy to take PRs that help improve logging for developers. Generally, we have been conservative about logging things like request and response bodies, as this can leak tokens and personally identifying information. On older versions of Android, it's possible to scrape the system logs from an installed app to steal and abuse this information.
