### ISSUE TITLE
Codelab interactive tutorial not working anymore when upgrading appauth to last version

### ISSUE THREAD

**Issue by sloosh** [openid/AppAuth-Android#250]
Hi guys,

I am following the codelab interactive tutorial, which is great to understand how things are working.
But I try to update it with the last appauth library version 0.6.1 instead of 0.2.0, my goal is then to integrate it into my app.
Here are the steps I am doing to upgrade:
 - In build.gradle: update library version to 0.6.1 instead of 0.2.0
 - In manifest: add tools:node="replace" to the RedirectUriReceiverActivity definition
 - In MainActivity: update AuthorizationServiceConfiguration definition with null parameter for registrationEndpoint, update AuthorizationRequest response type to ResponseTypeValues.CODE, replace authState.toJsonString with authState.jsonSerializeString, replace authState.fromJson with authState.jsonDeserialize

The project compiles and run, but the auth does not work anymore with 0.6.1, while everything was working perfectly with 0.2.0.
There is no error, after login is processed the login screen closes and goes back to the app main activity, but the auth is not performed anymore.

Is there anything else missing here ? 
Could you please help me to fix this so I could start to integrate it with my app ?
Thanks.

**Comment by sloosh** [comment]
It works with version 0.4.0 with all above steps done, but do not work with 0.6.1.

**Comment by sloosh** [comment]
Works up to version 0.4.1, the problem appears from 0.5.0.

**Comment by gwharvey** [comment]
The solution to this is a pull request in google code labs.  

https://github.com/googlecodelabs/appauth-android-codelab/pull/4/files

In MainActivity AuthorizeListener onClick
-      Intent postAuthorizationIntent = new Intent(action);
 +      Intent postAuthorizationIntent = new Intent(view.getContext(), MainActivity.class);
 +      postAuthorizationIntent.setAction(action);

**Comment by tim4dev** [comment]
0.7.0 worked ! thx

**Comment by sloosh** [comment]
Works great, thanks !
