### ISSUE TITLE
AuthState.update should not be called in an error state

### ISSUE THREAD

**Issue by gkggk** [openid/AppAuth-Android#255]
I am calling this method to generate new access token from refresh token by calling following method 

```java
performTokenRequest(
    mAppAuth.createTokenRefreshRequest(),
    clientAuthentication,
    new AuthorizationService.TokenResponseCallback() {
      @Override
      public void onTokenRequestCompleted(
          @Nullable TokenResponse tokenResponse, 
          @Nullable AuthorizationException e) {
            mAppAuth.update(response, ex)
      }
    });
```
This is working fine for one hour. But after access token expiry, it is throwing the following error.

```
AuthState.update should not be called in an error state 
(AuthorizationException: {"type":2,"code":2000,"error":"invalid_request","errorUri":""}), 
call update with the result of the fresh authorization response first
```

Is there anything I am missing? TIA

**Comment by iainmcgin** [comment]
There's not enough context here to be able to help.

- What is the IDP you are integrating with?
- Is the initial authorization request correctly producing a refresh token, or just an access token?

**Comment by iainmcgin** [comment]
Closing due to lack of update

**Comment by FilipMarusca** [comment]
running into the same problem. any update?

**Comment by FilipMarusca** [comment]
AuthState.update should not be called in an error state (AuthorizationException: {"type":2,"code":2002,"error":"invalid_grant","errorUri":""}), call updatewith the result of the fresh authorization response first

**Comment by FilipMarusca** [comment]
found the problem: I was using an old refresh token because I was not persisting the new refresh token.

**Comment by shishirshettygit** [comment]
> found the problem: I was using an old refresh token because I was not persisting the new refresh token.

I am saving the Refresh Token in the SharedPreference, and I am getting AuthorizationException: {"type":2,"code":2001,"error":"invalid_client","errorUri":""}

What could possibly go wrong?

**Comment by wyllyamjesus-hotmart** [comment]
I have same problem. Any update?
