### ISSUE TITLE
RedirectUriReceiverActivity not called with https link

### ISSUE THREAD

**Issue by danmaia17** [openid/AppAuth-Android#259]
Hi,

Is the firt time that i`m implementing this, so i'm trying to login following the documentation, but is not working. My url redirecty is: [https://pwc.abcdev.net/login](url)

My AndroidManifest.xml is:

```xml
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
  <intent-filter>
    <action android:name="android.intent.action.VIEW" /> 
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="https"
        android:host="pwc.abcdev.net"
        android:path="/login"/>
  </intent-filter>
</activity>
```

I can receive a return with this url?

Can anybody help me?

Thanks.

**Comment by iainmcgin** [comment]
Take a look at https://github.com/iainmcgin/AppAuth-Demo for a demo which uses app links to capture responses. There are many caveats to making this work:

1. They only work reliably and securely on Android M+.
1. The app link must be correctly registered; see the documentation for app links [here](https://developer.android.com/training/app-links/index.html).
1. The user must click on something for the app link to be triggered; if the redirect is automatic / triggered by Javascript, the browser will not hand off the link to the registered application.

Generally, I'd recommend sticking with custom scheme based redirects for broader compatibility across all current versions of Android. It will be at least another 2-3 years before we can rely on app links.
