### ISSUE TITLE
Move to 26.0.2 support libraries

### ISSUE THREAD

**Issue by JessHolle** [openid/AppAuth-Android#264]
I notice that the latest code has moved to 26.0.1 support libraries for 0.8.0.

That's great, as one can then easily use the release with 26.0.1 support libraries in the rest of the project.

Unfortunately, 26.0.2 libraries just came out today -- and since 0.8.0 has not yet been released it would be great to jump to 26.0.2.

**Comment by iainmcgin** [comment]
Sure, I upgrade the dependencies whenever I can. In the short term you should at least be able to override the dependency version via Gradle or whatever build system you are doing. I'm on vacation right now, but I'll update the library to the latest dependencies again when I'm back on Sept 14th.

**Comment by iainmcgin** [comment]
Updated to 26.1.0 in #267.
