### ISSUE TITLE
chrometabs redirection

### ISSUE THREAD

**Issue by cupcakeelements** [openid/AppAuth-Android#268]
This is a question -  

In https://developer.chrome.com/multidevice/android/intents it says that schemes such as `paulsawesomeapp://page1` will no longer be supported and we should use `intent://scan/#Intent;scheme=zxing;package=com.google.zxing.client.android;end` for deep linking, should I change my redirect_url to the new method ??  how does it still work in case of "AppAuth-Android" ??

**Comment by iainmcgin** [comment]
That page is referring to a different mechanism for launching an app that we do not use - specifically, it is referring to opening an app by creating an `<iframe src="app-url">` element in a page. It is the use of this iframe based trick which is no longer supported.

AppAuth-Android works by having an app register that it handles URL patterns based on a custom scheme, such that redirects or opening of links based on that pattern will be handled by the app. With newer versions of Android, apps can also register to handle "https://some-domain.com" links in a secure way, which will eventually be the recommended way of operating once older versions of Android cease to be pertinent.
