### ISSUE TITLE
Will this work with custom Android OS device which does not have Play services

### ISSUE THREAD

**Issue by shraddha1112** [openid/AppAuth-Android#269]
Hello,
We have a panel which runs on custom Android OS. Which does device authenticaiton via webView but as per this: https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

The authentication via webview has been deprecated. So i wanted to confirm if using this library will serve my purpose of validating and authenticating user for with gmail.
Note: Our device does not have play services
Regards,
Shraddha

**Comment by WilliamDenniss** [comment]
I believe it should work on a device without Play Services, it will use whatever browser the user has installed. Let us know if you run into any troubles!
