### ISSUE TITLE
User info endpoint configuration is only possible through the discovery url

### ISSUE THREAD

**Issue by ketola** [openid/AppAuth-Android#270]
Currently the user info endpoint is not in the Configuration class, instead it is read from the AuthorizationDiscoveryConfiguration in TokenActivity:

`userInfoEndpoint = new URL(discovery.getUserinfoEndpoint().toString());`

Because of this, user info cannot be accessed if the server does not support discovery.

As a fix, the user info endpoint could be added to the Configuration class and it would be read either from the discovery url or from the auth_config.json configuration file.

**Comment by joaogvfelix** [comment]
ketola how do you solve the problem? I have the same.

**Comment by ketola** [comment]
I implemented the possibility to configure the user info endpoint. I didn't propose it as a fix as there were no comments to my suggestion. But I created a pull request of it now and you can find it here. With this fix I can configure the user info endpoint in the configuration file: https://github.com/openid/AppAuth-Android/pull/308

**Comment by agologan** [comment]
Closing as change was merged. Thank you for your contribution.
