### ISSUE TITLE
Getting error for custom tabs when adding this plugin in gradle

### ISSUE THREAD

**Issue by shraddha1112** [openid/AppAuth-Android#274]
Hello,
I have added this plugin in gradle as follows:
`    compile 'net.openid:appauth:0.7.0'
`

But i am getting following error:
Error:Failed to resolve: com.android.support:customtabs:25.3.1

I have added jcenter in repositories.

Please help.
Regards,
Shraddha

**Comment by iainmcgin** [comment]
Add the google maven repo to your project, or update your Android SDK such that you have the 25.3.1 support libraries installed.

**Comment by shraddha1112** [comment]
Thanks

**Comment by shraddha1112** [comment]
It is working now as expected.
