### ISSUE TITLE
AppAuth-Android saving credentials in AccountManager :Question

### ISSUE THREAD

**Issue by cupcakeelements** [openid/AppAuth-Android#278]
I have an android app which uses AppAuth-Android library to authenticate with my identityservers.I get the access/refresh tokens along with the authstate.According to AppAuth-Android github questions suggestions are that we persist only the authstate via sharedPreference and also that we can use the "performActionwithFreshTokens" method to prevent accesstoken expiry.

I would like to use accountmanager for persistence so that if i need to share these states i can do it as well with another of our apps.

Is it possible to save the access/refresh token and write a syncadapter for refresh tokens on a timely basis using something like below.

`performTokenRequest(
mAppAuth.createTokenRefreshRequest(),
clientAuthentication,
new AuthorizationService.TokenResponseCallback() {
  @Override
  public void onTokenRequestCompleted(
      @Nullable TokenResponse tokenResponse, 
      @Nullable AuthorizationException e) {
        mAppAuth.update(response, ex)
  }
});`

**Comment by iainmcgin** [comment]
You can store your authorization state however you like, SharedPreferences is just one of the simplest ways to do it. We don't provide any built in persistence mechanism in the library as there are so many viable options; we leave it to the consumer of the library (you) to write the code for storing AuthState in your preferred way.

**Comment by cupcakeelements** [comment]
thank u , i am doubtful regarding which approach to take , which would you recommend 
persisting authstate and transfering it via accountmanager or  persisting  access/refresh tokens and use that with performtokenrequest.

**Comment by cupcakeelements** [comment]
thank you closing issue
