### ISSUE TITLE
Clarification of instructions for "Configuring Google Sign In"

### ISSUE THREAD

**Issue by rebeckag** [openid/AppAuth-Android#28]
I followed the instructions in app/README.md for configuring the demo app included in this repository with Google Sign-In and found some things that maybe could be made clearer:

* The enabling Google services page for Google Sign-In expects the SHA1 fingerprint of the certificate, while the command shown for extracting fingerprints picks SHA256 (via `grep SHA256`). The command from e.g. https://support.google.com/cloud/answer/6158849?hl=en#android should be shown/linked instead.
* There is no mention of having to change the value of `google_enabled` in res/values/idp_configs.xml to `true` (kind of obvious, but I missed it the first time I edited the file).

**Comment by iainmcgin** [comment]
Thanks for reporting this - please let me know if you think 0be6bf2 provides sufficient clarification.

**Comment by rebeckag** [comment]
Looks good, thanks!
