### ISSUE TITLE
Certificate dialog programatically handle

### ISSUE THREAD

**Issue by shraddha1112** [openid/AppAuth-Android#280]
Hello,
I am getting attached dialog when I redirect user to google auth screen. How can I hide and allow same programatically?

![setuppage_4](https://user-images.githubusercontent.com/572124/31326786-05205dae-ace8-11e7-8b5f-c5731f1e7260.png)

I am using following code:
`   AuthorizationRequest.Builder authRequestBuilder =new AuthorizationRequest.Builder(  
                serviceConfig,// the authorization service configuration  
                "xxx",// the client ID, typically pre-registered and static  
                ResponseTypeValues.CODE,// the response_type value: we want a code  
                redirectUri);// the redirect URI to which the auth response is sent    
        AuthorizationRequest authRequest = authRequestBuilder  
                .setScope("https://www.googleapis.com/auth/calendar")  
                //.setScope("https://www.googleapis.com/auth/calendar.readonly")  
                .setLoginHint("jdoe@user.example.com") 
                .setCodeVerifier(null)  
                .build();    
        authService= new AuthorizationService(this);  
       Intent intent = new Intent(this, xxx.class);  
           intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);  
        intent.putExtra(Constants.KEY_GOOGLE_IS_AUTHORIZED, true);  
//           // This will instruct SetupCalendar if it was launched from Wizard mode or not
            intent.putExtra(SetupRoomScheduler.FROM_ROOM_SCHEDULER_EXTRA, false);  
        authService.performAuthorizationRequest(
                authRequest,
                PendingIntent.getActivity(this, authRequest.hashCode(), intent, 0));` 

Please help,
Regards,
Shraddha

**Comment by iainmcgin** [comment]
This is not an issue related to AppAuth, and you can't programmatically override security warnings in the browser.
