### ISSUE TITLE
How to forget last session?

### ISSUE THREAD

**Issue by raflop** [openid/AppAuth-Android#289]
Hi,

I have a question, I use AppAuth-Android in my app, everything works well, but I don't know how to perform in app logout - i just want to AppAuth forgot last user logged in - because now it's automatically logging him back without asking for credentials so there is different user can't login.

I looking for something like deleting cookie in browser, I guess it should be done using AuthState but I didn't figure it out.

What should I do to achieve this goal?

Best regards

**Comment by v-mas** [comment]
library by itself does not have logout mechanism, you can check example application code that manages logout: https://github.com/openid/AppAuth-Android/blob/master/app/java/net/openid/appauthdemo/TokenActivity.java#L387

it basically remove old old AuthState keeping just server configuration (so it would not need to download it again)

**Comment by raflop** [comment]
Thank you I will check it

**Comment by raflop** [comment]
I checked a demo code, and previously I used the same approach, which only clears AuthState in the app.
If I'm not wrong clearing AuthState doesn't make anything with CustomTab used by library, and cookies stored in CustomTab can't be cleared that way, and they even shouldn't be.

Finally, after reading OpenId specification I understood  that I should use "prompt" option in the request (http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)
Options like login or select_account should allow force user to login again using different account even if he has a cookie in the browser.

Notice for others server must be configured to support that, eg IdentityServer 4 have two options Nonce and Login,

@v-mas Thank you, for help

**Comment by hebrides** [comment]
to test in demo app, add "prompt" to **auth_config.json**: 

```
{
  "client_id": "native.code",
  ...
  "prompt": "login",
  ...
  "https_required": true
}
```

mPrompt to **Configuration.java**:
```
private String mPrompt;
...
@NonNull
public String getPrompt() { return mPrompt; }
```

```
private void readConfiguration() throws InvalidConfigurationException {
...
  mPrompt = getConfigString("prompt");
...
}
```

add to builder in **LoginActiviy.java**:
```
private void createAuthRequest(@Nullable String loginHint) {
...
  if(mConfiguration.getPrompt() != null) {
    authRequestBuilder.setPrompt(mConfiguration.getPrompt());
  }
...
}

**Comment by Guy783** [comment]
Here is what I did.

https://github.com/openid/AppAuth-iOS/issues/530#issuecomment-628159766

**Comment by drdla49** [comment]
Hi, I set prompt login, but the last session is still valid. It does not work for Google login. For my direct login, it works. But if I try to log in with Google, there is always an old session and I cannot choose another Google account. Do you have any advice? Thanks

**Comment by Guy783** [comment]
Yeah so in the link below I wrote a `OIDExternalUserAgentASWebAuthenticationSession` the key line of code is `authenticationViewController.prefersEphemeralWebBrowserSession = true` it allows you to open a private browser.  

https://gist.github.com/Guy783/446b4921cf0894f031eacbd641122928

**Comment by MariaTod** [comment]
> Yeah so in the link below I wrote a `OIDExternalUserAgentASWebAuthenticationSession` the key line of code is `authenticationViewController.prefersEphemeralWebBrowserSession = true` it allows you to open a private browser.
> 
> https://gist.github.com/Guy783/446b4921cf0894f031eacbd641122928

Your solution is only for iOS. This is the AppAuth-Android space. 
How can this be achieved on Android??

It seems there is NO similar way to achieve what `prefersEphemeralWebBrowserSession = true` does on iOS.

Please help, I set prompt=login and it ONLY works when I try to login again for the same customer (using the same login_hint) BUT when I try to login with other customer it gives an error in the CustomTab: `Browser is already logged into a session.  Please log out of the session before creating a new one.`

**Comment by svenjacobs** [comment]
Has anyone ever found a solution to this? We're facing the same issue.

After a user logged out and we reset `AuthState` to the initial state, we want to be able to log in with a **different** user. However, even with `setPrompt("login")` set on `AuthorizationRequest.Builder` our Keycloak only accepts the previously used credentials. Contrary to iOS, we don't have the possibility to clear any cookies/sessions of the Chrome Custom Tab which is used for the login flow.

**Comment by svenjacobs** [comment]
We found a solution. Actually we forgot to call the ["end session"](https://github.com/openid/AppAuth-Android?tab=readme-ov-file#ending-current-session) endpoint when logging out the user within the app. Now with this flow in place, the SDK calls the end session endpoint within the Chrome Custom Tab so the session is properly cleared.

**Comment by SebastianRask** [comment]
To anyone finding this in the future, it is now possible to create ephemeral sessions with Chrome Custom Tabs. 
It is supported from `androidx.browser:browser:1.9.0-alpha01` and Chrome Version 130. 

You can implement it like so with AppAuth: 
```
val authService: AuthorizationService = ...
val intent = CustomTabsIntent.Builder()
    .setEphemeralBrowsingEnabled(true)
    .build()
authService.getAuthorizationRequestIntent(it, intent)
```

Read more [here](https://developer.chrome.com/docs/android/custom-tabs/guide-ephemeral-tab)

**Comment by svenjacobs** [comment]
> To anyone finding this in the future, it is now possible to create ephemeral sessions with Chrome Custom Tabs.

Thanks for the information! [Auth Tab](https://developer.chrome.com/docs/android/custom-tabs/guide-auth-tab) sounds very interesting and is also coming with the `1.9.0` release of `androidx.browser`.

**Comment by VitaSokolova** [comment]
That indeed sounds interesting, but I can't find a quick way to check it, because in `AuthorizationService``AuthTabIntent` is not supported, only CustomTabs:
```
public Intent getAuthorizationRequestIntent(
            @NonNull AuthorizationRequest request,
            @NonNull CustomTabsIntent customTabsIntent)
```
