### ISSUE TITLE
Adding additional IDP

### ISSUE THREAD

**Issue by rebeckag** [openid/AppAuth-Android#29]
I'm trying to get the demo app up and running against an IDP/OP in my domain (so not Google Sign-In).
How do I specify the redirect URI in idp_configs.xml/idp_configs_optional.xml, such that the authentication response is delivered through an Intent (similar to the case for Google Sign-In)?
The example documentation only shows an HTTP-url as redirect_uri, which I think assumes another web server receiving the response and not the demo app?
Do I need to add another intent filter in the manifest, similar to https://github.com/openid/AppAuth-Android/blob/c75b8f1824ea962a048166f380a0d56207fc62ad/app/AndroidManifest.xml#L33-L38?

**Comment by WilliamDenniss** [comment]
Yes, you need to add another intent filter for the scheme of your OAuth client's redirect URI.

I've clarified this in pull request #30, staged here: https://github.com/WilliamDenniss/AppAuth-Android/tree/master/app

**Comment by rebeckag** [comment]
Thanks, pull request #30 clarifies it a lot! :)
