### ISSUE TITLE
Facing problem in refresh token

### ISSUE THREAD

**Issue by DevItAndroidTeam** [openid/AppAuth-Android#294]
Hello,
I am facing problem while refresh id_token. I am not getting full id_token instead it gives half id_token. Means third part of signature is not available when refresh token.
Can you please help me how to get full id_token if user refresh token.

**Comment by iainmcgin** [comment]
I'm not sure I understand your question, what do you mean by a "half id_token"? Also, could you share more information about what IDP you are integrating with, what requests you are sending, etc.

**Comment by iainmcgin** [comment]
Closing due to lack of information.
