### ISSUE TITLE
How to use "https://login.microsoftonline.com/{tenant}/oauth2/v2.0 ?"

### ISSUE THREAD

**Issue by DevItAndroidTeam** [openid/AppAuth-Android#295]
I want to use https://login.microsoftonline.com/{tenant}/oauth2/v2.0/ instead of "https://login.microsoftonline.com/%1$s/v2.0/.well-known/openid-configuration?" so is this possible to use with this library? @iainmcgin  Can you help on this?

**Comment by iainmcgin** [comment]
Are they not the same? The OpenID configuration (at least for the "common" tenant) points to those OAuth2 endpoints for authorization and token exchange:

https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

```javascript
{
  "authorization_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
  "token_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
  // ...
}
```

**Comment by stnor** [comment]
See #300 for some code and issue.

**Comment by iainmcgin** [comment]
Closing as #300 provides more information.
