### ISSUE TITLE
Error when no default browser is defined

### ISSUE THREAD

**Issue by pmhsfelix** [openid/AppAuth-Android#3]
I've found what seems to be an error on the `BrowserPackageHelper` when no default browser is defined.
I get a `java.lang.NullPointerException` on the `isFullBrowser` method because the `ResolveInfo` is not null however the `ResolveInfo.filter` is null.
This seems to be the documented behaviour for the `PackageManager.resolveActivity` method when more than one option exists (i.e. no default)- ["If multiple matching activities are found and there is no default set, returns a ResolveInfo containing something else, such as the activity resolver."](http://developer.android.com/reference/android/content/pm/PackageManager.html#resolveActivity(android.content.Intent,%20int))

**Comment by iainmcgin** [comment]
@pmhsfelix can you verify that this fixes the issue on your device? I tested this on a device I had with no default browser set, where I was seeing the issue you described, and it seems to fix it. Please re-open if you find any further issues.
