### ISSUE TITLE
Configuring code_verifier length.

### ISSUE THREAD

**Issue by ebridges** [openid/AppAuth-Android#301]
We're working with an OAuth server the requires the `code_verifier` to be the [maximum length](https://tools.ietf.org/html/rfc7636#page-8) of 128 chars.

`CodeVerifierUtil` has a hardcoded default of 64 set in [`DEFAULT_CODE_VERIFIER_ENTROPY`](https://github.com/openid/AppAuth-Android/blob/bf33daf9e8ad57639e685037fdcb7bebdcda8815/library/java/net/openid/appauth/CodeVerifierUtil.java#L58).

Can this be made configurable?  Are you open to PRs for that?

As an approach I was thinking of adding an additional `Builder` constructor like [the existing one](https://github.com/openid/AppAuth-Android/blob/bf33daf9e8ad57639e685037fdcb7bebdcda8815/library/java/net/openid/appauth/AuthorizationRequest.java#L563), which takes an additional `int` parameter and passes it to `CodeVerifierUtil#generateRandomCodeVerifier()`.  Is that an acceptable approach?

Thanks

**Comment by ebridges** [comment]
Alternatively, I guess I could add it as an additional configuration parameter in `AuthorizationServiceConfiguration`

**Comment by iainmcgin** [comment]
You can just call `CodeVerifierUtil.generateRandomCodeVerifier` yourself and provide this value to the `AuthorizationRequest` builder:

```java
String codeVerifier = CodeVerifierUtil.generateRandomCodeVerifier(new SecureRandom(), 128);
AuthorizationRequest request = new AuthorizationRequest.Builder(/*...*/)
    // ...
    .setCodeVerifier(codeVerifier)
    .build();
```

I want to avoid adding more configuration where it's possible to directly achieve what you want using the existing builder methods and utilities.

**Comment by ebridges** [comment]
Thanks for the suggestion.  We'll try that out, and re-open this ticket if any issues.
