### ISSUE TITLE
redirect_uri not handled

### ISSUE THREAD

**Issue by midgardb** [openid/AppAuth-Android#307]
Having just installed AppAuth I'm getting "redirect_uri is not handled by any activity in this app..." message in my Android emulator. As I've not made any alterations to the downloaded code I'm guessing I need to provide something to get this to work, but I don't see an indication of what it's supposed to be.

My manifest has the default:
android.buildTypes.debug.manifestPlaceholders = [
    'appAuthRedirectScheme': 'net.openid.appauth.test'
];

Thanks for any insight.
Dave

**Comment by iainmcgin** [comment]
Did you read the main README.md? It tells you what needs to be done to configure redirect URIs.
