### ISSUE TITLE
How to use AppAuth in order to authenticate without sending client_secret?

### ISSUE THREAD

**Issue by eurbon** [openid/AppAuth-Android#310]
According to https://aaronparecki.com/oauth-2-simplified/#mobile-apps

**Note: Previously, it was recommended that mobile and native apps use the Implicit grant. In the time since the spec was originally written, the industry best practice has changed to recommend using the authorization code flow with no secret for native apps.**

and

**The authorization code is exchanged for an access token without using the client secret.**

I am trying to authenticate my application in a custom service provider(IdentityServer4). I won't be storing client secret in my application due to security.

How I should use this lib in order to achieve what I want?

**Comment by iainmcgin** [comment]
If IdentityServer4 is doing the right thing (e.g. compatible with [BCP 212 / RFC 8252](https://tools.ietf.org/html/rfc8252), it should be as straightforward as sending an authorization request with grant_type "code", specifying a client ID and redirect URI which is permitted for that client ID.
