### ISSUE TITLE
authorization_scope is required ?

### ISSUE THREAD

**Issue by ayushdimri** [openid/AppAuth-Android#314]
authorization_scope is required but not scpecified in the configuration.There is no authorization_scope in my configuration json file? where will i get authorization scope????

**Comment by iainmcgin** [comment]
Your question isn't very clear but I'll do my best to interpret it. In the demo, `authorization_scope` is specified [here](https://github.com/openid/AppAuth-Android/blob/master/app/res/raw/auth_config.json#L4). It should also be noted that the [Configuration](https://github.com/openid/AppAuth-Android/blob/master/app/java/net/openid/appauthdemo/Configuration.java) class isn't a core part of the AppAuth API - we defined it to make configuring the demo easier, but in general it is your responsibility to decide how the scope parameter of your authorization requests should be configured and specified.
