### ISSUE TITLE
Wrap this library in another library and set appAuthRedirectScheme

### ISSUE THREAD

**Issue by JustinTullgren** [openid/AppAuth-Android#316]
Hi,

I was wondering if its possible to wrap this library in another library?  I would like to leverage the simply token refresh and Basic Client Secret method. The issue I am having is that the manifest placeholder in the wrapping android library doesn't seem to be noticed in the check manifest task resulting in this error:

```Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.
```

I added the KVP in the gradle config per the documentation and I have attempted various ideas such as the following:

```
project.afterEvaluate {
    android.libraryVariants.all { variant ->
        variant.productFlavors.each { flavor ->
            flavor.manifestPlaceholders = [
                    'appAuthRedirectScheme': 'WrappedLibrarySchem'
            ]

        }
    }
}
```
and this

```
project.afterEvaluate {
    android.libraryVariants.all { variant ->
        variant.outputs.all { output ->
            output.processManifest.doFirst {
                variant.mergedFlavor.manifestPlaceholders = [ 'appAuthRedirectScheme': 'WrappedLibrarySchem' ]
            }
        }
    }
}
```

Any ideas?

Thanks!

**Comment by iainmcgin** [comment]
I'll need to think about this more deeply to give a better answer, but one option would just be to eliminate the manifest merging on RedirectUriReceiverActivity by declaring it in your own manifest and specifying a replace directive on the element. Your library would then be free to define it's own equivalent mechanism, or just let your library users do their own replacement of the activity intent filters.

**Comment by JustinTullgren** [comment]
That works thank you!
