### ISSUE TITLE
fingerprint sensor

### ISSUE THREAD

**Issue by chongma** [openid/AppAuth-Android#319]
is there any way to store the username and password in the fingerprint sensor and then inject that into AppAuth?

**Comment by iainmcgin** [comment]
I recommend reading the documentation on [keystore providers](https://developer.android.com/training/articles/keystore.html) to learn how to store secrets secured by a fingerprint sensor. However, I generally wouldn't recommend storing the user's raw credentials at all, and the only way to use them from your app would be through a [resource owner password credential grant](https://tools.ietf.org/html/rfc6749#section-4.3), which is rarely supported by identity backends for security reasons. There's a more in-depth discussion of this topic on [Scott Brady's blog](https://www.scottbrady91.com/OAuth/Why-the-Resource-Owner-Password-Credentials-Grant-Type-is-not-Authentication-nor-Suitable-for-Modern-Applications).

**Comment by chongma** [comment]
Are there any plans to integrate the fingerprint sensor with appauth in the future? I already have a banking app that stores my login details and then allows me to further login using the sensor. Could the first authentication be done normally and then the refresh token be accessed through the sensor?

**Comment by iainmcgin** [comment]
Encryption of the `AuthState` object using a secret key stored via the keystore provider is a good idea. I don't think we would integrate this directly into the core AppAuth library, however, as to date we have been deliberately unopinionated about where the `AuthState` object should be stored - there are many possibilities and we don't want to steer people towards a solution that doesn't work for them.

It's worth noting that there are many caveats to using the Android KeyStore - older Android devices have many known unfixable bugs that have to be worked around, some vendors have customized it and behave differently, etc.

We have been discussing writing some extension libraries for AppAuth to deal with some common problems with synchronizing authentication state between multiple apps, simplifying app links configuration, etc. These would be open sourced via the OpenID Foundation as well, but currently we don't have any concrete plans as to when they will be written or shared with the community.

**Comment by chongma** [comment]
Thanks, I will look at the net.openid.appauth.AuthState and see if I can encrypt it as you suggest.   I should be able to get a copy of Authstate from AuthStateManager after authentication?

It would be great to have a repository of extension libraries for commonly required things.  And it will be way better if they are written to same quality as AppAuth has been

**Comment by iainmcgin** [comment]
I'll report back here if/when such a library becomes real :)
