### ISSUE TITLE
Problems linking AppAuth to custom Auth provider

### ISSUE THREAD

**Issue by Smedzlatko** [openid/AppAuth-Android#320]
We have our own authentication server/provider to which we are trying to link an Android application with AppAuth. We used the provided demo app to test the workflow but still have no success.

This is our `auth_config.json`:

```json
{
  "client_id": <client_id>,
  "redirect_uri": "net.openid.appauthdemo://api.staging.myfuturity.com",
  "authorization_scope": "read",
  "discovery_uri": "",
  "authorization_endpoint_uri": "https://api.staging.myfuturity.com/auth/oauth/authorize",
  "token_endpoint_uri": "https://api.staging.myfuturity.com/auth/oauth/token",
  "registration_endpoint_uri": "",
  "user_info_endpoint_uri": "https://api.staging.myfuturity.com/auth/user",
  "https_required": true
}
```

`build.gradle`:
```
manifestPlaceholders = [
       'appAuthRedirectScheme': 'net.openid.appauthdemo'
 ]
```

manifest:
```xml
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="net.openid.appauthdemo"
                  android:host="api.staging.myfuturity.com"/>
            </intent-filter>
</activity>
```

We updated our assetLinks file accordingly: https://api.staging.myfuturity.com/.well-known/assetlinks.json

After trying to authorize the application, we are taken to the login page (inside ChromeTab) on our auth server and after providing the credentials, we get back to the app with 401 response and failed to authorize message. 

Can you please provide some more information? Are we doing something wrong?

**Comment by iainmcgin** [comment]
The configuration looks OK to me, though you may be a little confused about the purpose of the digital asset links declaration. It would only be needed in this case if you were trying to use a [trusted web activity](https://developers.google.com/web/updates/2017/10/using-twa) to remove the displayed address bar during authentication.

Can you provide any additional information on the 401 error? Do you get an AuthorizationException instance that provides an error code? Also, if you check the Intent that is returned to you, the data field should contain the actual URI that was triggered on the completion of the flow - from this you can see the raw parameters passed to you, and whether you think AppAuth is interpreting it incorrectly.

**Comment by Smedzlatko** [comment]
Thank you for the response. These are the requests logged in our auth server with their status codes:

```
GET /auth/oauth/authorize?redirect_uri=net.openid.appauthdemo%3A%2F%2Fredirect&client_id=<client_id>&response_type=code&state=k7dZhGG9O6lvbq2IcZIunQ&scope=read%20write&code_challenge=NKD0Hk4E2R1Q6aTQXll8TOdlSxZ5WcHYdVU2AFbe9dA&code_challenge_method=S256 HTTP/2.0 302

GET /auth/login HTTP/2.0 200

POST /auth/login HTTP/2.0 302

GET /auth/oauth/authorize?redirect_uri=net.openid.appauthdemo%3A%2F%2Fredirect&client_id=originalsin&response_type=code&state=k7dZhGG9O6lvbq2IcZIunQ&scope=read%20write&code_challenge=NKD0Hk4E2R1Q6aTQXll8TOdlSxZ5WcHYdVU2AFbe9dA&code_challenge_method=S256 HTTP/2.0 302

POST /auth/oauth/token HTTP/1.1 401
```

The demo application then shows: `Authorization Code exchange failedUnauthorized`

**Comment by Smedzlatko** [comment]
After extensive debugging, we solved the problem by changing the client authentication on the token endpoint to `new ClientSecretBasic(<client-secret>)` in method `performTokenRequest`.

Our token endpoint is secured with basic auth and authorization code grant usually expects usage of client secret so I was a bit confused that it was not required anywhere. It might be useful to update your documentation to reflect this configuration.
