### ISSUE TITLE
android.defaultConfig.manifestPlaceholders must be placed in all modules

### ISSUE THREAD

**Issue by julien-baczynski** [openid/AppAuth-Android#325]
Hi,

I'm using AppAuth in a low level module : 
App module
          |
Networking module (use AppAuth to encapsulate api calls)
          |
Module containing AppAuth helper classes 

I intended to reuse the third module in other apps, and by doing so, configure the redirect url in
the app module grade file.
But it won't let me build my app until i put a dummy manifest placeholder in every module gradle file.

Am i missing something or making a wrong usage of the library?

Thanks

**Comment by iainmcgin** [comment]
You're not doing anything wrong, it's just manifest placeholders don't seem to work very well when chained through more than one layer of indirection. My suggestion would be to remove the activity definition for RedirectUriReceiverActivity in your intermediary module. See Google's documentation on [manifest merging](https://developer.android.com/studio/build/manifest-merge.html) for more info; essentially you would add the following definition to your intermediary module's AndroidManifest.xml:

```xml
<activity 
    android:name="net.openid.appauth.RedirectUriReceiverActivity"
    tools:node="remove" />
```

This would then mean each app module would need to explicitly define the activity definition for RedirectUriReceiverActivity, with their own settings. Alternatively, you could define your own manifest placeholder, "myPlaceholder":

```xml
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity" 
          android:exported="true" 
          tools:node="merge">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="${myPlaceholder}"/>
    </intent-filter>
</activity>
```

This just pushes the placeholder up a layer, but that might be sufficient for you.

**Comment by chiara-jm** [comment]
Hi @iainmcgin , I know this issue is closed but I am facing a similar problem. I have the same setup as @julien-baczynski but my problem is while running unit test on the intermediate module, it fails cause the manifest merger expects the placeholder.

Is there a way to avoid enforcing the `manifestPalceholder` and configure it programatically 

I see it both equally intrusive in the intermediate module to add: 

```
<activity 
    android:name="net.openid.appauth.RedirectUriReceiverActivity"
    tools:node="remove" />``` 

on your manifest than or 

```
    defaultConfig {
        manifestPlaceholders = ['appAuthRedirectScheme': ""]
    }```

on your gradle

Thanks for the help

**Comment by ignaciotcrespo** [comment]
nice tip using the tools:node, thanks @chiara-jm 

In my case I prefer to use a string for configuration, so my activity is:

```
        <activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="@string/my_redirect_scheme" />
            </intent-filter>
        </activity>
```
