### ISSUE TITLE
Logout from browser session on phone also logouts inside application

### ISSUE THREAD

**Issue by Smedzlatko** [openid/AppAuth-Android#327]
We developed an application using AppAuth for OAuth2 authentication against our custom auth server. Everything is working fine - we can login using Chrome custom tabs on our auth server and then get redirected back to the application with valid AuthState and access token.

But I just noticed a very strange behavior. When I logout from the session in my browser, my application will stop working and requires authorization again even though the access token is still valid.

So I am wondering, if this is intended behavior because it does not make sense to me, why the browser session has anythign to do with the authentication process once I have a valid token.

I am happy to provide code but I am not sure where to start and would like to avoid wall of text. Any ideas what could be possibly wrong?

**Comment by iainmcgin** [comment]
This behavior doesn't sound like it has anything to do with AppAuth -  we certainly don't try and keep web and native "sessions" in sync in any way. What is the IDP you are integrating with? My guess would be that the action of signing out on the web may be invalidating the refresh token you are using in your app.

**Comment by Smedzlatko** [comment]
It's a simple Spring application which invalidates the session on logout (no token manipulation). So it is probably something I did terribly wrong with my AppAuth integration. I was just curious whether it is some AppAuth feature that I missed. Thank you for the clarification, though.
