### ISSUE TITLE
WhiteList for custom tabs fallbacks to browser rather than throwing exception

### ISSUE THREAD

**Issue by awaseem** [openid/AppAuth-Android#330]
## WhiteList for customtabs fallback to firefox browser

Version: **0.7.0** 

Hi there! Loving the library but have some issues with the whitelist feature. We've enabled the use of custom tabs only, but when the Chrome browser is disabled, the Samsung browser doesn't exisit (non samsung phone) and the toggle for "Custom Tabs" functionality is disabled for Firefox. AppAuth falls back to opening the Firefox app rather than throwing an `ActivityNotFoundException`. Here is our code snippet for the browser matching, we explicitly set custom tabs to be  true for all the browsers. 

```
// Custom Tabs using Chrome 45+, Samsung 5.4+, Firefox 57+
val appAuthConfig = AppAuthConfiguration.Builder()
        .setBrowserMatcher(BrowserWhitelist(
                VersionedBrowserMatcher.CHROME_CUSTOM_TAB,
                VersionedBrowserMatcher(
                        Browsers.SBrowser.PACKAGE_NAME,
                        Browsers.SBrowser.SIGNATURE_SET,
                        true,
                        VersionRange.atLeast("5.4")),
                VersionedBrowserMatcher(
                        Browsers.Firefox.PACKAGE_NAME,
                        Browsers.Firefox.SIGNATURE_SET,
                        true,
                        VersionRange.atLeast("57"))
        )).build()
```

### Steps to reproduce

1. Have Chrome and Firefox installed on your device
2. Disable Chrome
3. Go into settings for Firefox, and disable the custom tabs (Settings> general> toggle "Custom Tabs")
4. Try to start the `AuthorizationRequestIntent` which opens the FireFox App rather than throwing an exception (custom tabs are disabled for Firefox)

Thank you!

**Comment by iainmcgin** [comment]
Apologies for the delay, but upon investigating this further, it is not an AppAuth bug. The way that AppAuth determines whether a browser provides custom tabs is by looking for a custom tab service advertised by the browser, via its manifest. There is no standard mechanism that AppAuth can use to determine that a browser has custom tabs dynamically disabled - one possibility would be for the browser to reject service connections to the custom tabs service. However, Firefox does not do this, so even if AppAuth were explicitly checking for this it would still not know that Firefox intended to handle custom tab intents in a separate task from the app.

The correct way to handle this on the Firefox side, I think, would have been to actually disable the custom tabs service if the user disables the feature in the settings. This _should_ be possibly by using [PackageManager.setComponentEnabledSetting](https://developer.android.com/reference/android/content/pm/PackageManager#setComponentEnabledSetting(android.content.ComponentName,%20int,%20int)). If I understand the semantics of PackageManager correctly, disabling the service would then mean AppAuth would not succeed in finding the service. With your whitelist settings, it would then reject Firefox as an option.

Closing this issue as there is nothing further that can be done on the AppAuth side.
