### ISSUE TITLE
 Move to 27.1.1 support libraries

### ISSUE THREAD

**Issue by Boosted300blk** [openid/AppAuth-Android#334]
Latest Code is still on 26.1.0 support library while 27.1.1 is out.
With v0.8.0 not being released yet can you please update to the latest support library for that release.

**Comment by iainmcgin** [comment]
I'm in an awkward situation right now where I can't release new versions until my new employer signs some agreements with the OpenID Foundation, but while you're waiting it should be possible to override the support library versions used via gradle: see [the gradle documentation on enforced dependency versions](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:enforcing_dependency_version) for more info.

**Comment by iainmcgin** [comment]
Updated in #342.
