### ISSUE TITLE
client_secret_basic header value invalid when special characters are used

### ISSUE THREAD

**Issue by panva** [openid/AppAuth-Android#337]
According to https://tools.ietf.org/html/rfc6749#section-2.3.1 (+appendix) the client_id and client_secret values are to be `application/x-www-form-urlencoded`-encoded before being used the basic authentication scheme as username and password. This is [currently not the case](https://github.com/openid/AppAuth-Android/blob/0.7.0/library/java/net/openid/appauth/ClientSecretBasic.java#L52-L56).

Given a client_id value of `1PpG/Q 1` and client_secret value of `z/tZ9VwFZqApmIQ+ZH1I5pLk/uB4ud:X2/8bL+wfFTt1rFw=` the Authorization header should be processed as follows

```
// Authorization: Basic base64(formEncode(1PpG/Q 1):formEncode(z/tZ9VwFZqApmIQ+ZH1I5pLk/uB4ud:X2/8bL+wfFTt1rFw=))

// Authorization: Basic base64(1PpG%2FQ+1:z%2FtZ9VwFZqApmIQ%2BZH1I5pLk%2FuB4ud%3AX2%2F8bL%2BwfFTt1rFw%3D)

Authorization: Basic MVBwRyUyRlErMTp6JTJGdFo5VndGWnFBcG1JUSUyQlpIMUk1cExrJTJGdUI0dWQlM0FYMiUyRjhiTCUyQndmRlR0MXJGdyUzRA==
```

This is very likely to cause issues with clients using this scheme with a provider that also omits this requirement and has identifier or a secret with special characters.

**Comment by iainmcgin** [comment]
Fixed by #345.
