### ISSUE TITLE
Issue refreshing the Access Token

### ISSUE THREAD

**Issue by AlbertoCamillo** [openid/AppAuth-Android#346]
Hello, 

I'm trying on Android to refresh the Access Token with both `performActionWithFreshTokens` and manually with `performTokenRequest` creating a TokenRefreshRequest.

In both cases I'm getting an `AuthorizationException`: 

`AuthorizationException: {"type":2,"code":2002,"error":"invalid_grant","errorDescription":"Bad request - client_id is mandatory.","errorUri":""}`

If I try to pass the `ClientSecretBasic` using the client secret the exception says the client_id is invalid.

I debugged the final Auth Request and the `client_id` is there and it's correct.

Thanks

**Comment by AlbertoCamillo** [comment]
Found the issue and solved.

**Comment by fulyay** [comment]
Hi @AlbertoCamillo, Can you explain how you solved the issue?

**Comment by IstrateAndrei** [comment]
@AlbertoCamillo I'm struggling with the same problem. Can you please explain how you solved it?

**Comment by tusharmate** [comment]
For anyone still struggling this issue, I found solution as below
Refer Refreshing an access token section at link: https://developers.google.com/identity/protocols/oauth2/native-app
Send all parameters except client_secret
You will get successful response in JSON
