### ISSUE TITLE
AuthorizationException: {"type":0,"code":3,"errorDescription":"Network error"}

### ISSUE THREAD

**Issue by vandanaKumari89** [openid/AppAuth-Android#347]
Hi @iainmcgin

I am trying to use AppAuth to integrate with SecureAuth using Authorization code flow.

During Authorization-code exchange flow, i am getting below error : 
"Authorization code exchange failed null"

On debugging, i get below info
{"type":0,"code":3,"errorDescription":"Network error"}

I am using ClientSecretBasic.java class to send my clientID and Client Secret as authorisation header.

Any idea what's wrong and how to resolve it? 

Cheers,
Vandana

**Comment by vandanaKumari89** [comment]
I am testing it on Android Pixel (Oreo)

**Comment by iainmcgin** [comment]
I'll need some more information to be able to help you effectively - do you see any stack traces from AppAuth in logcat? 

Unrelated to your issue: we strongly discourage the use of client secrets unless they are sourced via dynamic client registration. If SecureAuth does not support public clients (i.e. those without a client secret), I strongly suggest you do the code exchange on your backend. This is not to say that exchange using a secret from the client won't work, it's just generally a bad idea.

**Comment by iainmcgin** [comment]
Closing due to lack of response.

**Comment by YogeshwarSharma** [comment]
Getting the same Issue in Android KitKat only but working fine above KitKat version.
How to resolve this issue?

**Comment by LucasFebatis** [comment]
According to the android documentation, from Android Oreo, cleartext support is disabled by default

The solution is in a response in the stackoverflow I use all the time as a reference

https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

Remembering that the use of http is not advised for Production
