### ISSUE TITLE
Readme suggestions

### ISSUE THREAD

**Issue by celphy** [openid/AppAuth-Android#350]
Hey, I recently played around with AppAuth-Android and noticed two smaller things in the Readme (which I heavily relied upon).

First is directly beneath **Obtaining an authorization code** at 
AuthorizationRequest.Builder authRequestBuilder =

    new AuthorizationRequest.Builder(

        serviceConfig, // the authorization service configuration

        MY_CLIENT_ID, // the client ID, typically pre-registered and static

        ResponseTypeValues.CODE // the response_type value: we want a code

        MY_REDIRECT_URI); // the redirect URI to which the auth response is sent

There seems to missing a comma after `ResponseTypeValues.CODE`.

The second thing was less obvious and cost me a few hours to realize my mistake.
Directly beneath the first block is

    AuthorizationRequest authRequest = authRequestBuilder

    .setScope("email profile https://idp.example.com/custom-scope")

    .setLoginHint("jdoe@user.example.com")

    .build();

Here the scope is defined without **openid** as is recommended [in this openid connect document.](http://openid.net/specs/openid-connect-core-1_0.html) I tested my application with a [MITREid Connect local instance](https://github.com/mitreid-connect/) and it wouldn't work without. A wrong token would result in a 401 but I was able to attain a technically correct token and would get a 403 result without the openid scope.

Besides these two minor issues I was very happy with my results and the pace I progressed at.

**Comment by iainmcgin** [comment]
Thanks for reporting these! #351 fixes the errors you highlighted. We are glad that you are finding the library useful.
