### ISSUE TITLE
AppAuth For IdentityServer4

### ISSUE THREAD

**Issue by JubinMathai** [openid/AppAuth-Android#354]
I want to integrate IdentityServer4 in my Android Application.

Please let me know if we can use AppAuth for Authentication with IdentityServer4.

**Comment by WilliamDenniss** [comment]
Your best best would be to contact the folks at IdentityServer4 with this question. Our GitHub issues are not really a general Q&A forum.

I did find this link which may help you though: https://github.com/openid/AppAuth-iOS/blob/master/Examples/README-IdentityServer.md

**Comment by WilliamDenniss** [comment]
Your best best would be to contact the folks at IdentityServer4 with this question. Our GitHub issues are not really a general Q&A forum.

I did find this link which may help you though: https://github.com/openid/AppAuth-iOS/blob/master/Examples/README-IdentityServer.md

**Comment by WilliamDenniss** [comment]
Your best bet would be to contact the folks at IdentityServer4 with this question. Our GitHub issues are not really a general Q&A forum.

I did find this link which may help you though: https://github.com/openid/AppAuth-iOS/blob/master/Examples/README-IdentityServer.md
