### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by mehulpxm** [openid/AppAuth-Android#355]
Just configured auth_config.json file in demo app but whenever i run app i am getting below error not able to download discovery document. see attachment for more details 
<img width="1696" alt="screen shot 2018-06-20 at 6 38 14 pm" src="https://user-images.githubusercontent.com/35398127/41661284-f5720988-74bb-11e8-8844-f38d3794dd4c.png">

Thanks.

**Comment by iainmcgin** [comment]
As the exception states, this is a network error - the device can't resolve the network address of the host name you have specified. Please test that you can open this URL in the device's browser, I don't believe this is anything to do with AppAuth.
