### ISSUE TITLE
AppLink Configuration

### ISSUE THREAD

**Issue by asharif1990** [openid/AppAuth-Android#356]
I tried to use the Library with another Idp. Therefore, I update the auth_config.json file based on their documentation, but the problem is that after the authorization, I did not redirect to the application, instead, I redirected to the https://appauth.demo-app.io/oauth2redirect inside the browser. 
I enclosed the configuration for your consideration. 
{
  "client_id": "TMQXh6506piGSkFd607rJsH9pqE1jj0f5eoq5TkW",
  "redirect_uri": "appauthdemo.openid.net:/oauth2redirect",
  "authorization_scope": "email profile",
  "discovery_uri": "",
  "authorization_endpoint_uri": "https://idp.io/v1/auth/authorize",
  "token_endpoint_uri": "https://idp.io/v1/auth/token/",
  "registration_endpoint_uri": "",
  "user_info_endpoint_uri": "https://idp.io/v1/users/me",
  "https_required": true
}

**Comment by asharif1990** [comment]
Good Morning, 

As I explored more about the before mentioned problem, I understand that it is a problem with some browsers, so I tried the method with other phones and now I faced another problem that showed me the bellow error:

Authorization code exchange failed
<img width="240" alt="screen shot 2018-06-25 at 15 24 51" src="https://user-images.githubusercontent.com/35602900/41961156-f40d0292-79f1-11e8-943a-1d28d9283ef7.png">

I will be grateful if help me with this issue.

**Comment by iainmcgin** [comment]
The redirect URI in your provided JSON does not match your description - it has a custom scheme redirect URI. Please confirm what the actual redirect URI you specified in your configuration was: did you set it to `https://appauth.demo-app.io/oauth2redirect`?

For your second post, I can't help unless you provide more information - the screenshot does not tell us anything about what the failure is. If there is a stack trace, please include that, otherwise use a debugger to check what the authorization response is - did the IDP reject the request, or is AppAuth incorrectly capturing the response, or rejecting the response as invalid? All of these are possibilities, without more information to narrow the cause down.

**Comment by asharif1990** [comment]
yes, The son file picture is not correct. I set the redirection URI to "https://appauth.demo-app.io/oauth2redirect". 
- for the second problem, after I explored more with capturing the application traffic I understand that the problem is with the IDP. 

- now, I try to use OKTA, every thing went well, but when I try to make an API call to get the user info I get the following error: 
"No Refresh Token Available". 
07-09 10:24:12.863 30110-30110/io.chino E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.chino, PID: 30110
    java.lang.IllegalStateException: No refresh token available
        at net.openid.appauth.AuthState.performActionWithFreshTokens(AuthState.java:385)
        at net.openid.appauth.AuthState.performActionWithFreshTokens(AuthState.java:366)
        at net.openid.appauth.AuthState.performActionWithFreshTokens(AuthState.java:354)
        at io.chino.chat.views.LoginActivity$MakeApiCallListener.onClick(LoginActivity.java:292)
        at android.view.View.performClick(View.java:5610)
        at android.view.View$PerformClick.run(View.java:22265)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

Can you help me with this issue. because, I follow the code lab for this part of code and I can't understand the reason. 
Regards.

**Comment by iainmcgin** [comment]
The redirect you were using isn't a general purpose service, it serves only as an example of how to capture an HTTPS redirect and transform that into a custom scheme redirect, for a specific custom scheme. If you need it, copy it to your own URL for your own custom scheme; don't just directly use it.

For your second issue, you can only use performActionWithFreshTokens if the authorization flow you triggered gave you a refresh token. The refresh token is used to fetch an access token and/or ID token. Without the refresh token, there is nothing that method can do for you.
