### ISSUE TITLE
Missing port when constructing URL for token request

### ISSUE THREAD

**Issue by pntest** [openid/AppAuth-Android#36]
In AuthorizationService::TokenRequestTask::doInBackground(), the URL that is constructed (local variable 'url' inside try block) is missing the port from the request URI. This omission seems to cause FileNotFoundException when connecting to the token endpoint.

**Comment by iainmcgin** [comment]
Good find! Looks like we should be adding mRequestUri.getPort() if it is defined at [library/java/net/openid/appauth/AuthorizationService.java#L234](https://github.com/openid/AppAuth-Android/blob/64148d45711c32d8e09a95d603fc8bfc645afea5/library/java/net/openid/appauth/AuthorizationService.java#L234). I'll fix ASAP.

**Comment by pntest** [comment]
Thanks! 
Is it possible to get a patch for 0.1.1 because I am using that version. Otherwise, when is 0.2.0 scheduled to become available?

**Comment by iainmcgin** [comment]
Once I get this fixed, and the error handing in AuthState done (#26), I can cut a 0.2.0 release. I'll try and get that done for tomorrow to unblock you.

**Comment by pntest** [comment]
Thanks a lot!

**Comment by pntest** [comment]
Just one more request: if it could also be made available to satisfy a Gradle dependency, it would be very helpful.

**Comment by iainmcgin** [comment]
Of course - when I cut a 0.2.0 build I'll update our bintray repo which should propagate to JCenter very quickly.

**Comment by iainmcgin** [comment]
I'm just waiting for code reviews to get the necessary fixes for 0.2.0 in, hopefully we'll have this wrapped up by today.

**Comment by pntest** [comment]
No problem, thanks!

**Comment by iainmcgin** [comment]
0.2.0 is now released; if it doesn't fix your issue, please re-open this bug.

**Comment by pntest** [comment]
Thanks.

**Comment by pntest** [comment]
The issue seems to be fixed in version 0.2.0. Thank you for the fix.
