### ISSUE TITLE
AppAuth without browser

### ISSUE THREAD

**Issue by development-s365** [openid/AppAuth-Android#370]
Hi

I created an App with flutter and would like to authenticate a user with password and username with a keycloak server. Is it possible to do this without having to use a browser?

Kind regards

**Comment by premacck** [comment]
I also want to do the same thing. Perform authorizing without a browser with the default "Microsoft layout" and through my own UI. Is that possible in any way?

**Comment by iainmcgin** [comment]
We don't support the resource owner password credentials flow - it encourages users to enter their password into untrusted third party apps, increasing their risk of being phished. You also don't need AppAuth to implement it, if you insist on doing it: it's a very simple flow.
