### ISSUE TITLE
What is the use of client_secret ?

### ISSUE THREAD

**Issue by arpitjindal97** [openid/AppAuth-Android#373]
According to IEFT standards, installed applications don't need to provide `client_secret` while asking for `access_token`. 

How will I prevent anyone from using my `client_id` in his application and receiving `access_token`?

In Google Console, we provide SHA1 of our key which protects anyone getting `auth_code`. How does it work in Microsoft ?

**Comment by iainmcgin** [comment]
Clients without client secrets are known as "public clients". They are protected against abuse by other malicious apps through two weak mechanisms:

- The redirect URI whitelist for the client ID. If you use universal links or app links, these cannot be intercepted by malicious apps, at least for up-to-date versions of Android and iOS. However, given the difficulty in configuring universal / app links, most apps use custom scheme URIs, which can be easily intercepted / reused by other apps.

- The consent screen typically shows app identification information associated with the client ID. The hope is that users will notice if this information does not match that of the host application. This is a weak assumption, as so many users have become blind to consent screens and click "accept" as quickly as possible without reading the contents.

So, it is clear that public clients don't offer many guarantees. If you _need_ more security, then clients controlled by your backend, using client secrets, are a better choice. It is worth reiterating that client secrets cannot be relied upon in native apps, as the secrets can be trivially extracted from them. Therefore, they offer no additional security over public clients when used in native apps.

**Comment by arpitjindal97** [comment]
How should I add a server? Can you please give a glance of login flow with server included ?

**Comment by iainmcgin** [comment]
Essentially, initiate the authorization code flow as normal using a client ID that is owned by your server. When the authorization code is provided back to your app, send it to your server backend, where the server can then exchange that code for a refresh token by supplying the client secret. When doing this, you will likely need to disable PKCE, or have your backend provide a code verifier challenge to the application.

Sorry, we don't have the bandwidth to act as a general support and tutorial service on how best to use OAuth2 for your use cases. If you have a specific issue with the library, please open a new issue for that.
