### ISSUE TITLE
Feature Request: Support End Session (and Generic External User-Agent requests)

### ISSUE THREAD

**Issue by WilliamDenniss** [openid/AppAuth-Android#374]
_NB. I don't personally have this requirement, creating this issue to serve as the canonical thread for this common feature request._

On AppAuth for iOS, we made two recent changes in support of the OpenID End Session (RP Logout) endpoint, as follows:

1/ Generalized the External User-Agent request logic

Previously we had just one external user-agent request, so all the APIs related to opening that request in the browser, and the various associated logic were specific to that one request. [We generalized those APIs](https://github.com/openid/AppAuth-iOS#212) so as to support *any* external user-agent request, so now Authorization Request was just a specialization of that (enabling the End Session Request to be as well).

2/ Implemented the End Session logout endpoint.

We [implemented](https://github.com/openid/AppAuth-iOS/pull/259) the specification documented by [Section 5 of Draft 28 of OpenID Connect Session Management 1.0](http://openid.net/specs/openid-connect-session-1_0.html#RPLogout). Note: be sure to use that document, as there are some out-dated, and duplicative drafts floating around ([Front-Channel logout](http://openid.net/specs/openid-connect-frontchannel-1_0.html#RPInitiated) for example has duplicated, and out of sync, information).

**Comment by chrisngn** [comment]
Which version does AppAuth-Android plan to release user signout?

**Comment by iainmcgin** [comment]
We don't know, no-one has started the work yet.

**Comment by arnaldo-infinite** [comment]
So till now the end session logout point has not been implemented for AppAuth-Android? My effort to make the call to the end sessions logout point is successful yet the application is still redirected into the application. Can you suggest an alternative till an actual fix is released?

**Comment by smokienko** [comment]
Hi guys ,
I am currently working on okta android sdk where we need end session functionality within AppAuth sdk. I have created a [pullrequest](https://github.com/openid/AppAuth-Android/pull/433) with this functionality. Can somebody please take a look at it?

**Comment by GRRedWings** [comment]
I see there has been some work and documentation on this.  Is there any plan or roadmap for this?

**Comment by agologan** [comment]
Thanks to @smokienko and a very long process there is a working end-session support solution as part of the library.
We don't have a specific plan for cutting a new library release so in the meanwhile feel free to reference a build from https://jitpack.io/#openid/AppAuth-Android

Closing this topic for now, and let's pick it up with specific issues regarding the current implementation.
