### ISSUE TITLE
Feature Request: Support OpenID Connect Token Validation

### ISSUE THREAD

**Issue by WilliamDenniss** [openid/AppAuth-Android#375]
AppAuth for iOS [recently added](https://github.com/openid/AppAuth-iOS/pull/101/commits/89b5473f31d61b07713549e761b14a12d6ebe7c9) support for OpenID Connect ID Token validation (but not signature verification, electing to use the option allowed in the specification for not verifying signatures of ID Tokens received over TLS from the token endpoint).

This feature was added in two stages:
1/ Add [support](https://github.com/openid/AppAuth-iOS/pull/101/commits/11e680b2ef9dddfc23a95b27373f5e2bcb999eb5) for 'nonce' on the authorization request
2/ [Parse](https://github.com/openid/AppAuth-iOS/pull/101/commits/89b5473f31d61b07713549e761b14a12d6ebe7c9#diff-2130c7c7eebc15011ff214026f036d18) the ID Token (if any) and [validate](https://github.com/openid/AppAuth-iOS/pull/101/commits/89b5473f31d61b07713549e761b14a12d6ebe7c9#diff-babcf557cd66620dac5a61fee0ae8bae) the fields according to [OpenID Connect Core Section 3.1.3.7](http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) (excluding rules #1, #4, #5, #7, #8, #12, and #13 which did not apply).

With this feature in place, we were also then able to [implement](https://github.com/openid/AppAuth-iOS/pull/101/commits/e30ea9dc01fbfb9dc479b7b766f00e73e2946a0b) the OpenID Connect RP Certification test suite, which is now part of our test suite that runs on CI.

**Comment by iainmcgin** [comment]
Fixed by #385.
