### ISSUE TITLE
MobSF Launch Mode of Activity (net.openid.appauth.AuthorizationManagementActivity) is not standard.

### ISSUE THREAD

**Issue by ButuzGOL** [openid/AppAuth-Android#376]
Did test of MobSF
and got 
Launch Mode of Activity (net.openid.appauth.AuthorizationManagementActivity) is not standard.

An Activity should not be having the launch mode attribute set to "singleTask/singleInstance" as it becomes root Activity and it is possible for other applications to read the contents of the calling Intent. So it is required to use the "standard" launch mode attribute when sensitive information is included in an Intent.

Could you help me do we need to do something from app side
app using lib https://github.com/FormidableLabs/react-native-app-auth
<img width="956" alt="screen shot 2018-07-19 at 5 10 14 pm" src="https://user-images.githubusercontent.com/196564/42948938-451c68ec-8b79-11e8-9fca-d78361b22b37.png">

**Comment by tikurahul** [comment]
There is nothing sensitive about `AuthorizationManagementActivity`. It's only job is to help keep the back stack sane for the authorization flow & launch `AuthorizationActivity` or `CompletionActivity`. (which use standard flags).  For more info take a look at (https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationManagementActivity.java). 

I would not worry about the MobSF warnings.
