### ISSUE TITLE
MobSF (net.openid.appauth.RedirectUriReceiverActivity) is not Protected.

### ISSUE THREAD

**Issue by ButuzGOL** [openid/AppAuth-Android#377]
Did test of MobSF
and got 
(net.openid.appauth.RedirectUriReceiverActivity) is not Protected. 
[android:exported=true]

An Activity is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device.

Could you help me do we need to do something from app side
app using lib https://github.com/FormidableLabs/react-native-app-auth

**Comment by tikurahul** [comment]
We need `RedirectUriReceiverActivity` to be exported because that's how we do the code flow. 
MobSF warnings seem to be very spurious. Before filing security bugs, I suggest trying to understand how OAuth2 flows protect against these kinds of attacks.
