### ISSUE TITLE
Dependency Incompatibility Errors

### ISSUE THREAD

**Issue by alisonthemonster** [openid/AppAuth-Android#384]
I'm getting dependency incompatibility errors from what looks like an older version of customtabs. I see that you have updated to the [latest support library](https://github.com/openid/AppAuth-Android/search?utf8=%E2%9C%93&q=supportLibVersion&type=), but for some reason I'm not seeing this change?

I'm using this dependency:
`    implementation 'net.openid:appauth:0.7.0'`

And I get this message in android studio:
`
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 25.3.1. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:customtabs:25.3.1 less... (⌘F1) 
There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion)
`

When I run this command:
`./gradlew -q dependencies app:dependencies --configuration debugAndroidTestCompileClasspath`
 
I get this back:
```
\--- net.openid:appauth:0.7.0
     \--- com.android.support:customtabs:25.3.1
          +--- com.android.support:support-compat:25.3.1 -> 27.1.1 (*)
          \--- com.android.support:support-annotations:25.3.1 -> 27.1.1
```

Any idea how?

**Comment by hnljp** [comment]
Had the same problem also with the current code.
The dependency is updated in the git repository, but it was first fixed for me after deleting my gradle cache.

**Comment by alisonthemonster** [comment]
Deleting my cache fixed the problem! Thank you!
