### ISSUE TITLE
Client ID not being sent with a Token Request

### ISSUE THREAD

**Issue by eodc** [openid/AppAuth-Android#393]
I'm trying to get a token from the Twitch API, however when I request I receive a 400 Bad Request saying that the client id wasn't sent. As expected, the AuthorizationResponse has the client id and subsequently, the TokenRequest.

I'm not exactly sure if this is a Twitch problem or an AppAuth problem, as I don't know how to extract the full url from the HttpUrlConnection used by AuthService to request a token, because it doesn't seem as if it's updating in the debugger (its request method is still shown as GET instead of POST)

If it helps, I'm also making the token request with a ClientSecretBasic, because as far as I've seen the implicit flow isn't supported with AppAuth and the Twitch API requires the client secret to be sent with an authorization flow.

Edit: I kind of found out how to find the updated UrlConnection. It seems as the query isn't being concatenated to the base url, but I'm not exactly sure if that's supposed to happen because the Android Docs say that you pass request bodies into the connections output stream. Its coming to look like this is more of a Twitch problem than an AppAuth one.

**Comment by panva** [comment]
> If it helps, I'm also making the token request with a ClientSecretBasic, because as far as I've seen the implicit flow

I think you might want to use `ClientSecretPost` since twitch does not support `ClientSecretBasic` token endpoint auth.

**Comment by eodc** [comment]
>I think you might want to use ClientSecretPost

That was it, thanks!
