### ISSUE TITLE
Disable SSLv3 

### ISSUE THREAD

**Issue by ruhijain** [openid/AppAuth-Android#396]
While trying to login using AppAuth Lib, I get the following error.

`WebRequestCaller: Error: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb89e1710: Failure in SSL library, usually a protocol error
                                                                     error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x96ea3926:0x00000000)
`

I think the library should provide a means by which SSLv3 can be disabled. How can that be done? Please help on this.

**Comment by iainmcgin** [comment]
You can set your own [ConnectionBuilder](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/connectivity/ConnectionBuilder.java) via the [AppAuthConfiguration](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AppAuthConfiguration.java#L91) object - this will let you tweak your connection settings however you wish. If you don't change this, we use the [platform defaults](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/connectivity/DefaultConnectionBuilder.java#L53).
