### ISSUE TITLE
How to sign JWT with a certificate during Token Exchange request?

### ISSUE THREAD

**Issue by chrisngn** [openid/AppAuth-Android#405]
My team would like to authenticate the client by having it sign the JWT with a certificate during the token exchange request. Looking at the AuthorizationService.java, it seems AuthorizationService#performTokenRequest only accepts a ClientAuthentication, which uses a client secret. Does AppAuth support this feature?

**Comment by iainmcgin** [comment]
Are you trying to implement a standard extension to OAuth2, and if so, do you have a link to a specification for what you are trying to implement? We don't support what you are describing, but it is possible that you might be able to achieve what you desire by implementing a custom [ClientAuthentication](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/ClientAuthentication.java) class, and then providing this to [performTokenRequest](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationService.java#L316). 

`ClientAuthentication` instances can add HTTP request headers or body request parameters to the token exchange request. However, you don't get access to a full request object, which may be necessary depending on what it is you are trying to sign as part of the request. An anonymous inner class implementation of `ClientAuthentication` which is given access to what you need in the context where you call `performTokenRequest` might give allow for a slightly awkward workaround.

**Comment by chrisngn** [comment]
This is the documentation that I am reading through [Keycloak Client Authentication](https://www.keycloak.org/docs/3.1/securing_apps/topics/oidc/java/client-authentication.html). I thought I would ask since Keycloak listed AppAuth as an official OIDC client

**Comment by chrisngn** [comment]
@iainmcgin Based on Keycloak's documentation, is signing a JWT achievable with AppAuth? If so, would you still recommend the implementation suggested previously?

**Comment by iainmcgin** [comment]
The answer depends upon whether you are using [dynamic client registration](https://www.keycloak.org/docs/3.1/securing_apps/topics/client-registration.html#_openid_connect_dynamic_client_registration), or a static pre-configured client ID.

If you are using a static client ID, the issue would be how to distribute a certificate to the clients in a secure way. That _may_ be possible with a mobile device management service for enterprise devices. The more common case would be consumer devices and a consumer app distributed through the Play Store, at which point there is no reliable, trustworthy mechanism to distribute a certificate to the client that you could use for signing requests.

If you are using dynamic client registration, it looks like the spec allows for clients to provide their JSON Web Key Set as part of the [registration process](](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata), which would allow you to use a dynamically created key pair. However, I don't think this would work well for mobile apps - the key set would have to be published on a web URL that the IDP can retrieve, so you would have to be dynamically publishing that key set on a domain you control also.

Overall, I wouldn't recommend the approach you are investigating. It is difficult to securely configure a mobile app to be a confidential client - that is, one that uses a client secret or private key of some sort to reliably prove its identity. If possible, treat the app as a public client with no secret, or perform all of your token management operations on a backend service in an environment where you can use secrets in a secure manner.

**Comment by chrisngn** [comment]
@iainmcgin Thanks for the opinion and suggestions! I will investigate further to see if this is a viable option. I would like to keep this open in the mean time

**Comment by iainmcgin** [comment]
@chrisngn any update? If there isn't a specific action I can take right now (e.g. bug or documentation fix) I'd like to close this issue. You can always reopen it later if the situation changes.

**Comment by chrisngn** [comment]
Hi Iain,

We decided not to use jwt for authentication. Please close.

Thanks,
Chris
