### ISSUE TITLE
BrowserMatcher ignored in CustomTabsIntent.launchUrl

### ISSUE THREAD

**Issue by piisku78** [openid/AppAuth-Android#409]
I have defined an AppAuthConfiguration with BrowserMatcher and I use this configuration in my AuthorizationService. 

When I launch AuthorizationRequestIntent the BrowserMatcher is used to select a correct Browser.
authService.getAuthorizationRequestIntent(authRequestBuilder.build());

But when I launch a customTab intent to open a webpage then the BrowserMatcher is ignored.
CustomTabsIntent customTabsIntent = authService.createCustomTabsIntentBuilder().build();
customTabsIntent.launchUrl(this, Uri.parse("https://www.blabla.com"));

I expected the BrowserMatcher is always used.

**Comment by iainmcgin** [comment]
The `createCustomTabsIntentBuilder()` is intended to give you the opportunity to customize some of the properties of the custom tab (title bar color, etc) before passing that intent back to the `AuthorizationService` via `performAuthorizationRequest`. It is at that point that we attach the matched browser to your intent (in [prepareAuthorizationRequestIntent](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationService.java#L368), along with the necessary request parameters based on the `AuthorizationRequest` you provide. 

It is not intended that you should directly use `launchUrl` on the CustomTabsIntent provided by this library - if you do this, then you are not really getting any benefit from the additional functionality in AppAuth for request construction. Instead, do something like:

```java
CustomTabsIntent customTabIntent = authService.createCustomTabsIntentBuilder()
    .setToolbarColor(Color.RED)
    /* ... */
    .build();

authService.performAuthorizationRequest(authRequest, completionIntent, customTabIntent);
```
