### ISSUE TITLE
Suggestions for different redirect urI configuration

### ISSUE THREAD

**Issue by ChingSheng** [openid/AppAuth-Android#410]
Hi, we are developing a music integration services which support two different music services. Both services need OAuth procedure to get each access token. 

  As I use appAuth and read from README, there are some setting under **app/build.gradle** & **AndroidManifest.xml**

```
android.defaultConfig.manifestPlaceholders = [
                'appAuthRedirectScheme': 'service_1_scheme'
        ]
```
``` xml
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="service_1_scheme"
                      android:host="service_1_host"/>
            </intent-filter>
</activity>
```
  I want to know is any possible to let both services use different redirect uri configution under one project? Or any suggestions, thanks!

**Comment by iainmcgin** [comment]
Sure - you can ignore the `appAuthRedirectScheme` manifest placeholder and define your own activity intent filters in your manifest, to allow for multiple schemes, hosts, whatever you need. It would look like this:

```
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity"
    tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="service_1_scheme"
                      android:host="service_1_host"/>
                <data android:scheme="service_2_scheme"
                      android:host="service_2_host"/>
            </intent-filter>
</activity>
```

The `tools:node="replace"` directive is required so that the manifest entry in the library is ignored, giving you full control over the definition.

**Comment by iainmcgin** [comment]
@ChingSheng did this solve your problem?

**Comment by ChingSheng** [comment]
@iainmcgin Yes, thank you! By using tools:node="replace", no need write "manifestPlaceholders" under app/build.gradle.
