### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by aromanelli** [openid/AppAuth-Android#415]
The following paragraph in the [README.md](https://github.com/openid/AppAuth-Android/blob/master/README.md) file has a typo ...

> Alternatively, the redirect URI can be directly configured by adding an intent-filter for AppAuth's RedirectUriReceiverActivity to your _AndroidMan**fi**est_.xml:

Specifically, the spelling of 'AndroidManifest' is incorrect.

**Comment by iainmcgin** [comment]
Fixed, thanks for pointing this out!
