### ISSUE TITLE
Android X support

### ISSUE THREAD

**Issue by SDemonUA** [openid/AppAuth-Android#417]
Hi there, 
Just migrated my app to AndroidX and now found type missmatch for methods that configure and work with custom tabs , i.e. 4th argument for AuthorizationService.performAuthorizationRequest().
Right now as I can see it builds and works fine, but can I do smth with that ?

**Comment by FizzyMobile** [comment]
Also I found out that Jetifier modifies _ACTION_CUSTOM_TABS_CONNECTION_ value. Package manager doesn't recognize any application that can handle this action anymore.
The original value is _android.support.customtabs.action.CustomTabsService_ and jetifiered is _androidx.browser.customtabs.action.CustomTabsService_.

**Comment by cwt-rami-citrom** [comment]
Is there any timeline for this fix?

CWT would like to offer a fix to this, but I see that there are already 6 open pull requests, from quite a while ago that have not been handled. Is this library still actively maintained?

**Comment by hnljp** [comment]
Until it gets fixed, you can use: https://github.com/openid/AppAuth-Android/issues/423#issuecomment-447013411

**Comment by hnljp** [comment]
An updated version of the jetifier processor is on its way:
https://issuetracker.google.com/issues/119183822#comment7
Should fix the problem.

**Comment by hnljp** [comment]
The jetifier processor has now been released.

**Comment by andreluizreis** [comment]
Please, is there any news about this issue? Why is taking so long to have an update?

**Comment by authguidance-examples** [comment]
As far as I'm aware AppAuth plays very nicely with androidx, though it may not have been officially certified. Code sample that I'm in the process of writing up is here: https://github.com/authguidance-examples/authguidance.mobilesample.android/blob/master/README.md

**Comment by alwa** [comment]
I suggestg that you consider making `net.openid.appauth.AuthorizationManagementActivity` extend `androidx.appcompat.app.AppCompatActivity`

**Comment by alwa** [comment]
I will create a separate ticket for my request

**Comment by agologan** [comment]
Library has been migrated to AndroidX in `0.8.0` with the exception of the activity mentioned by @alwa.

Closing this issue and will continue the discussion to that particular item in the PR.
