### ISSUE TITLE
On Android 7+ devices, token requests to endpoints with an unsigned certificate results in network error

### ISSUE THREAD

**Issue by EarlyWild** [openid/AppAuth-Android#420]
On Android 7+ devices, when performing a token request that uses a static client secret, a network error occurs. This can be replicated using the example app by adding a clientSecret (either ClientSecretBasic or ClientSecretPost) to the token request. I have tested on multiple Android devices at multiple API levels (21-28).

Using the Android Profiler, it appears that the network operation is not adding any oauth information to the network call. 

Below is an example of the token request:
>             SAMPLE
            AuthorizationResponse response = AuthorizationResponse.fromIntent(data);
            AuthorizationException ex = AuthorizationException.fromIntent(data);
            ClientAuthentication clientAuth = new ClientSecretBasic("MY SECRET CODE");
            mAuthService.performTokenRequest(
                    response.createTokenExchangeRequest(),
                    clientAuth,
                    (resp, ex1) -> {
                        if (resp != null) {
                            // exchange succeeded
                            Log.i(TAG,"token WORKED");
                        } else {
                            // authorization failed, check ex for more details
                            Log.i(TAG,"token FAILED: " + ex.toString());
                        }
                    });

**Comment by EarlyWild** [comment]
This issue looks like it is the same as #347

**Comment by EarlyWild** [comment]
I figured this out. The service that I was connecting to had a user signed cert (which I had installed onto my device and forgot). This caused an error when performing the token exchange. Since Android API level 24, you are required to mark in the manifest that the app will trust user added certs. If anyone else comes across this issue, refer to:

https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html

In my case, the user added cert is only utilized for developing and never for production.

NOTE: This is not a bug so I will close this issue.

**Comment by shishirshettygit** [comment]
So adding this xml and referencing it in the Manifest file should resolve this issue?

```
<network-security-config>
    <base-config>
        <trust-anchors>
            <!-- Trust preinstalled CAs -->
            <certificates src="system" />
            <!-- Additionally trust user added CAs -->
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
```
