### ISSUE TITLE
New release request + OpenID RP Certification?

### ISSUE THREAD

**Issue by KarlBusse** [openid/AppAuth-Android#422]
Sorry to be a bother @iainmcgin ...I saw issue #298 prompted the previous release to [jcenter](https://bintray.com/openid/net.openid/appauth), so I just wanted to ask if you might be willing to do another release soon?

(I understand that we _could_ use jitpack [as you mentioned](https://github.com/openid/AppAuth-Android/issues/298#issuecomment-411636224), but I'd rather not add yet another repo to my projects...and the jcenter releases elicit the warm, fuzzy feeling of formality.)

Very much looking forward to getting some ID Token validation! 1a47f749ea5300ec17454ce05b804c9578018b95

And while I'm on the topic, are there any plans for official OpenID RP Certification in the near future?
...similar to: openid/AppAuth-iOS#101

**Comment by iainmcgin** [comment]
#27 covers the request for RP certification. Otherwise, closing this old issue.
