### ISSUE TITLE
Add option for enabling FLAG_SECURE

### ISSUE THREAD

**Issue by milhauscz** [openid/AppAuth-Android#428]
The app where I use the AppAuth library is automatically scanned for security issues by DataTheorem. The scan detected that net.openid.appauth.RedirectUriReceiverActivity and AuthorizationManagementActivity do not enable the FLAG_SECURE, thus reduced my app's score. Please add some configuration option for enabling this flag, or maybe set the flag as default setting. Code example:

`// Secure code for protecting one Activity
// See https://github.com/datatheorem/FlagSecure-Android for protecting all Activities
public class SecureActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        // Set the Secure flag for this Window
        getWindow().setFlags(LayoutParams.FLAG_SECURE, LayoutParams.FLAG_SECURE);
    }
}`

**Comment by YogeshwarSharma** [comment]
You can add FLAG_SECURE to these activities net.openid.appauth.RedirectUriReceiverActivity and AuthorizationManagementActivity using onActivityCreated(Activity activity, Bundle savedInstanceState) function of Application.ActivityLifecycleCallbacks inside Application Class. But Chrome Custom Tab use chrom's activity not these activities.

**Comment by iainmcgin** [comment]
Neither of these activities renders anything on-screen, so FLAG_SECURE doesn't actually do anything useful in this case. Does anyone know if FLAG_SECURE has any other effects other than preventing rendering on insecure displays or capturing screenshots?

**Comment by milhauscz** [comment]
You are right the Activities do not render anything so the flag is useless. I have solved this with the DataTheorem company, they have added an exception for the AppAuth Activities. Therefore I am closing this ticket.

**Comment by carstenhag** [comment]
Theoretically the custom tab activity could have FLAG_SECURE set, but passing this option onto the custom tab is not possible.
