### ISSUE TITLE
using CustomTabs vs launching external browser

### ISSUE THREAD

**Issue by heidijinxujia** [openid/AppAuth-Android#440]
It seems the appauth prefers to use customTabs rather than launching the external browser. Besides the pros listed in the documentation [here](https://developer.chrome.com/multidevice/android/customtabs).   

Is there any difference in dehydrating the calling activity? For example, when the user is trying to do an auth and the auth activity launches the external browser. A device in dose mode may close the apps in the background, like the auth activity. And after the user finishes the login in the external browser and is redirected back to the calling activity. The calling activity is already been killed and could not be found.  In this case, I am wondering if CustomTabs will be a better choice. Will the CustomTabs prevent the calling app from closing compared to the external browser?

**Comment by iainmcgin** [comment]
I'm not sure I follow your first paragraph: AppAuth uses custom tabs when available as it provides a better UX. You can easily override this with a browser filter if you wish, check the documentation in the main README.

Using a custom tabs doesn't guarantee any difference the behavior of the lifecycle of the initiating activity; under memory pressure Android may still decide to kill your activity. This is why it is important to persist the important state of your activity through the appropriate lifecycle methods regardless.

**Comment by AntonyARHS** [comment]
Hi @iainmcgin

How could you enforce the use of a browser in the "external" mode and not the custom tab even if the browser support it? (For specific reasons.)
