### ISSUE TITLE
Question about logged out session with Keycloak

### ISSUE THREAD

**Issue by claudiat** [openid/AppAuth-Android#441]
Hello,

Is there any way to verify if the session has been logged out externally from the Admistration Console of the provider?
I am currently using an offline session from Keycloak. When I logout the user's session from the Keycloak Administration Console, my session in the application remains online regardless of the fact that is has been previously killed.

I have tried the functions 'getNeedsTokenRefresh()' and 'isAuthorized()" but they render 'true'. Is there any way to verify if the session has been logged out from the Administration console?

**Comment by iainmcgin** [comment]
Sorry, this is an IDP specific question and not something specific to the AppAuth-Android library. Keycloak may provide a way to revoke tokens or check for token revocation from the client, you'll need to check with their documentation.

**Comment by claudiat** [comment]
Ok, thank you for your response!
