### ISSUE TITLE
How to sign out completely?

### ISSUE THREAD

**Issue by amanzan** [openid/AppAuth-Android#443]
I'm testing the sample project but the sign out doesn't work as expected. I am able to authenticate with a username and password, then I tap sign out. Then I wanted to authenticate with a different username and password, but somehow the info of the previous user is still there and I cannot authenticate a new user.

The only way I have to use a new user is if I go to Chrome app and delete all data. 

Is there any way to sign out completely?

**Comment by iainmcgin** [comment]
This is Identity provider specific: some provide a way to fully deauthenticate the user, others do not. Check the documentation for the IDP(s) you are integrating with to see what your options are.
