### ISSUE TITLE
my redirect activity not called when i change base activity calling auuthorization

### ISSUE THREAD

**Issue by ZahraSdg** [openid/AppAuth-Android#445]
my problem is when i open the chrome to my login pagefrom ActivityA it works fine and redirects to my ResultActivity but as soon as i change my Activity A to Activity B it doesnt redirect to ResultActivity anymore! 
i checked the scheme and redirect uri and it works fine on ActivityA but when calling performAuthorizationRequest in ActivityB with exact method, RedirectUriReceiverActivity doesnt get called.
anyone facing the same issue?

**Comment by iainmcgin** [comment]
Pleass share the portion of your app manifest related to the the two activities. My guess would be that the intent filters for handling the redirect are somehow misconfigured.

**Comment by tomaszwojcik** [comment]
@ZahraSdg Have you every activity/have you renamed in the manifest file?

For example, my authorization code has **AuthCompletedActivity** and **AuthCancelledActivity**:

```
authService.performAuthorizationRequest(authRequest,
    PendingIntent.getActivity(context, 0, new Intent(context, AuthCompletedActivity.class), 0),
    PendingIntent.getActivity(context, 0, new Intent(context, AuthCancelledActivity.class), 0));
```
Same names must appear in the AndroidManifest.xml:

```
<activity android:name=".AuthCompletedActivity" />
<activity android:name=".AuthCancelledActivity" />
```

**Comment by ZahraSdg** [comment]
I found out it was because it was not triggered on click event and i started it on onCreate(). once i started the auth process in click listener of a button it worked. 
thanks anyway
