### ISSUE TITLE
Recursive Sign-in

### ISSUE THREAD

**Issue by ktsoukanov** [openid/AppAuth-Android#447]
A recursive sign-in within a sign-in issue is happening to users who don't actively use Chrome browser on their device. Instead of loading a page, specified in **authorization_endpoint_uri** ,chrome custom tab will load a **Sign in to Chrome** page instead.

Many users do not know about **Sign in to Chrome** feature or it's purpose and will not understand what exactly they are signing-in to. At this point the sign-in session is effectively highjacked by the browser.

![sn1](https://user-images.githubusercontent.com/20212763/52487866-93681b00-2b8c-11e9-87dd-0d099037fa62.png)

Steps to reproduce:

1. Sign into Chrome
2. Sign-out of Chrome
3. Do not use Chrome for a couple of months, but let the auto-updates install new versions.
4. Try to authenticate using the AppAuth demo app.
5. Notice, that instead of loading a page, specified by authorization_endpoint_uri, a "sign in to Chrome" page will load instead prompting user to sign-in into a different account than a user intended to.

There could be variations in this user experience, depending on the state of Chrome browser on a device:

![sn2](https://user-images.githubusercontent.com/20212763/52488232-5f412a00-2b8d-11e9-8d40-eb8e4c325432.png)
![sn3](https://user-images.githubusercontent.com/20212763/52488233-5f412a00-2b8d-11e9-8344-d48cafb25bb4.png)

User may also see a "Welcome to Chrome" page:

![sn4](https://user-images.githubusercontent.com/20212763/52488310-87c92400-2b8d-11e9-9ee1-1d715463cad3.png)

Is there a way to prevent Crome from highjacking the oauth sign-in session and always directly load the **authorization_endpoint_uri** instead?

**Comment by iainmcgin** [comment]
This is related to #172 and #173; it is a long-standing issue with the Chrome browser on Android that has not been fixed. There is nothing you can do from your app to prevent this issue that I am aware of.

Closing as duplicate.
