### ISSUE TITLE
Using of Client Secret

### ISSUE THREAD

**Issue by asharif1990** [openid/AppAuth-Android#450]
Hello there, I would like to ask which part of code should I change in order to send the client secret within my app, inside the documentation I see that there is a section that mention to add 
```ClientAuthentication clientAuth = new ClientSecretBasic(MY_CLIENT_SECRET);
TokenRequest req = ...;
authService.performTokenRequest(req, clientAuth, callback); ```

I should add this inside the TokenActivity? is that correct?

Thank you in advance

**Comment by iainmcgin** [comment]
https://github.com/openid/AppAuth-Android#utilizing-client-secrets-dangerous
