### ISSUE TITLE
Opera browser does not open login page

### ISSUE THREAD

**Issue by sarbyn** [openid/AppAuth-Android#452]
How to reproduce:

- Setup opera (version 50.2.xxxx) as default browser
- Try to login

Expected:
- Opera browser loads the login page

Actual:
- ActivityNotFoundException is thrown

With a little bit of debugging I've found that Opera does not expose the Intent.CATEGORY_BROWSABLE intent filter. The library fails at BrowserSelector.isFullBrowser():

`// The filter must match ACTION_VIEW, CATEGORY_BROWSEABLE, and at least one scheme,
if (!resolveInfo.filter.hasAction(Intent.ACTION_VIEW)
   || !resolveInfo.filter.hasCategory(Intent.CATEGORY_BROWSABLE)
   || resolveInfo.filter.schemesIterator() == null) {
       return false;
}`

Then an ActivityNotFoundException is thrown (as espected) but the user is unable to login.

This is the intended behaviour or I've missing something?

**Comment by kristerkari** [comment]
I am seeing the same thing when setting Opera 51.3.xxxx as the default browser on Samsung Galaxy S7. 

I'm wondering if https://github.com/openid/AppAuth-Android/pull/463 will help with this, or will it just cause the app not to crash.

**Comment by childnode** [comment]
dup #459

**Comment by HideakiSago** [comment]
I'm having the same problem whether I set Opera as the default browser or Chrome as the default browser.
There was no problem before setting it to the default browser.

**Comment by HideakiSago** [comment]
I was in exactly the same situation.
> With a little bit of debugging I've found that Opera does not expose the Intent.CATEGORY_BROWSABLE intent filter. The library fails at BrowserSelector.isFullBrowser():
> 
> // The filter must match ACTION_VIEW, CATEGORY_BROWSEABLE, and at least one scheme, if (!resolveInfo.filter.hasAction(Intent.ACTION_VIEW) || !resolveInfo.filter.hasCategory(Intent.CATEGORY_BROWSABLE) || resolveInfo.filter.schemesIterator() == null) { return false; }


I'm not sure if it's an Opera issue, an OS issue, or a CustomTabs issue, but uninstalling Opera fixed this issue.
Setting Opera to the default browser again seems to cause the same problem again.
And this problem seems to depend on the OS etc., and it seems that there are some devices that do not have the problem.

**Comment by SuddenH4X** [comment]
The same bug is currently discussed in another issue. I've added there some additional information: https://github.com/openid/AppAuth-Android/issues/521#issuecomment-815692988

**Comment by agologan** [comment]
@HideakiSago Opera developers have fixed the issue in v60 (https://github.com/openid/AppAuth-Android/pull/469#issuecomment-759772716)
If you're still having issues with specific browser/version combos please reach out to the individual browser developers for a fix and in the meanwhile you may blacklist the browser using  [BrowserDenyList](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/browser/BrowserDenyList.java)

Closing issue.

**Comment by agologan** [comment]
For anybody reading this d4fde4462126fa0f5c183509dc9775d189d8e11b aims to fix the specific issue of having Opera installed as default and misbehaving. Please test release `0.9.1+`

**Comment by bharris86** [comment]
Still having this issue with opera browser won't auth the github application on login
