### ISSUE TITLE
Unexpected error while performing partial evaluation:

### ISSUE THREAD

**Issue by YogeshwarSharma** [openid/AppAuth-Android#454]
Getting following error with dexgaurd
Unexpected error while performing partial evaluation:
  Class       = [com/samsung/android/knox/sdp/SdpUtil]
  Method      = [registerListener(Ljava/lang/String;Lcom/samsung/android/knox/sdp/SdpStateListener;)Z]
  Exception   = [java.lang.IllegalArgumentException] (Can't find common super class of [com/samsung/android/knox/sdp/SdpStateListener] (with 2 known super classes) and [com/samsung/android/knox/sdp/SdpStateListenerProxy] (with 1 known super classes))
:app:dexguardRelease FAILED

**Comment by iainmcgin** [comment]
That error is pointing to Samsung Knox, nothing to do with this project.

**Comment by sushant37** [comment]
@YogeshwarSharma Did you got the solution of samsung knox issue?

**Comment by YogeshwarSharma** [comment]
Yes @sushant37, It is already known issue with the Samsung Knox library. These above class are present in the Samsung Devices so that is why it was not present in Samsung Knox Lib. so, you have to create the stub class above missing classes 
[com/samsung/android/knox/sdp/SdpStateListener]
[com/samsung/android/knox/sdp/SdpStateListenerProxy] 

Just create different Jar with above classes with the same package name and put it as a jar in the project.

Or 

You can try with below command in gradle.properties 
systemProp.allow.incomplete.class.hierarchy
