### ISSUE TITLE
Browser redirection does not work in android p mobiles

### ISSUE THREAD

**Issue by sagarsrao** [openid/AppAuth-Android#456]
Hello,

Browser redirection works great in all the mobiles < android p. But when it comes to android p the browser redirection does not happen at all Forcefully I need to close the browser or click back to get the redirection done?
Is there any way I can fix....?

**Comment by andrebbk** [comment]
@sagarsrao is your problem fixed? I have the same issue...

**Comment by justincounts** [comment]
@andrebbk I noticed that this was only broken for me when using an AppLink for the callback. if I used a custom scheme everything works fine.

**Comment by andrebbk** [comment]
@justincounts can u show me how I shoud implement the costum scheme. I did a costum scheme in manifest with https and it Still doesnt redirect me to the app...

**Comment by sagarsrao** [comment]
My issue is fixed

**Comment by andrebbk** [comment]
@sagarsrao How? custom scheme in manifest?

**Comment by justincounts** [comment]
I mean using a custom scheme instead of HTTP/HTTPS.

instead of using AppLinks to intercept requests for `https://foo.bar.com/deep/link/path` used `com.foo.bar://deep/link/path` where com.foo.bar is defined as the custom scheme in the manifest.

**Comment by andrebbk** [comment]
Sorry for wasting your time, but like this?
   
 <activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="http"
                    android:host="com.testingappauth.utad"
                    android:path="/callback"/>
            </intent-filter>
        </activity>

**Comment by andrebbk** [comment]
Sorry for wasting your time, but like this?  
  
#<activity
#            android:name="net.openid.appauth.RedirectUriReceiverActivity"
#           tools:node="replace">
#           <intent-filter>
#               <action android:name="android.intent.action.VIEW"/>
#                <category android:name="android.intent.category.DEFAULT"/>
#               <category android:name="android.intent.category.BROWSABLE"/>
#                <data android:scheme="http"
#                    android:host="com.testingappauth.utad"
#                    android:path="/callback"/>
#            </intent-filter>
#        </activity>

**Comment by andrebbk** [comment]
Sorry for wasting your time, but like this?

`  <activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="http"
                    android:host="com.testingappauth.utad"
                    android:path="/callback"/>
            </intent-filter>
        </activity>`

**Comment by agustinsivoplas** [comment]
Any solution for this? I am forced to use https as scheme

**Comment by ghosalmartin** [comment]
You need to to start the browser with an executor e.g

```        executor.submit {
            val intentBuilder: CustomTabsIntent.Builder =
                authService.createCustomTabsIntentBuilder(authRequest.toUri())
            intentBuilder.setInstantAppsEnabled(false)
            intentBuilder.enableUrlBarHiding()
            intentBuilder.setToolbarColor(
                ContextCompat.getColor(
                    this,
                    R.color.colorPrimary
                )
            )
            val intentRequired = intentBuilder.build()
            intentReference.set(intentRequired)
            mAuthIntentLatch.countDown()
        }```

Like the example app

**Comment by agologan** [comment]
@ghosalmartin using an [Executor](https://developer.android.com/reference/java/util/concurrent/Executor) or not has nothing to do with the issue here.

@justincounts was on the right track, either implement [App Links](https://developer.android.com/training/app-links) if you want to use `http/https` redirect URI or configure a **custom scheme** for your client in the identity provider e.g. `myapp://` with the redirect uri being something like `myapp://auth/redirect?token=...`

Closing this as the author has [resolved](https://github.com/openid/AppAuth-Android/issues/456#issuecomment-492710763) his issue
