### ISSUE TITLE
Google auth example not working

### ISSUE THREAD

**Issue by andygeers** [openid/AppAuth-Android#46]
I'm trying to get the demo project working to authenticate me with Google. I have two problems:
1. The AppAuth-Android framework isn't sending the required `client_secret` parameter when it makes its token request. I can fix this from the client side by passing in an additional_parameters map.
2. The response from Google includes an `id_token` but not a `refresh_token`. Then when I press the "View user info" button that appears on `TokenActivity` it crashes because of an invalid state exception - it doesn't have the necessary refresh token

Any ideas?

**Comment by andygeers** [comment]
(If I modify the library to use the `id_token` as though it were a `refresh_token`, it actually works just fine and fetches the user info quite happily - I just would prefer not to have to modify the library to get it working)

**Comment by iainmcgin** [comment]
Client secrets are not required for Google auth, and are strongly discouraged for mobile apps where the secret can be easily extracted from an APK. The demo app that is included in this repository includes instructions for configuring Google authentication, see [here](https://github.com/openid/AppAuth-Android/blob/master/app/README.md).

If you send the right authorization request you should be able to get an authorization code for a refresh token quite easily - the demo app does this already, and uses the retrieved access code for requests to the UserInfo endpoint: see [here](https://github.com/openid/AppAuth-Android/blob/master/app/src/net/openid/appauthdemo/TokenActivity.java#L274).

**Comment by andygeers** [comment]
Thanks very much for the clarification. I think I would change the Google integration instructions to clarify that appauth.keystore is created by AppAuth-Android during the build process - I was looking for it whilst integrating the library and of course couldn't find it because it hadn't been run yet. I had assumed it was something generic to any Android project.

**Comment by iainmcgin** [comment]
Ah, apologies for that. I tried to simplify the setup process by generating the keystore during the build but as you say this isn't specifically mentioned anywhere in the instructions. I'll try to clarify this point.

**Comment by andygeers** [comment]
On that note: are we meant to copy and paste the generateKeystore task into our own project or is it meant to run automatically when our project expresses a dependency on the library?

**Comment by iainmcgin** [comment]
It's just for convenience when developing AppAuth-Android - your own app should have its own keystore for debug and release. You're of course welcome to re-use this if you find it useful, but most apps will use the standard ~/.android/debug.keystore for debug and another more carefully managed keystore for release.

**Comment by andygeers** [comment]
Wonderful, that makes a *lot* more sense now - perhaps the documentation could explain that (especially that debug path - I was conscious of my production keystore but not the debug one)

**Comment by andygeers** [comment]
And *now* I see that Google documents that location within the tool where you create API credentials... not sure how I missed that last time. Thanks again.
