### ISSUE TITLE
Userinfo endpoint call does not honor https_required configuration

### ISSUE THREAD

**Issue by madurangasiriwardena** [openid/AppAuth-Android#467]
Token endpoint call is made using the ConnectionBuilder (refer [code](https://github.com/openid/AppAuth-Android/blob/0.7.1/library/java/net/openid/appauth/AuthorizationService.java#L418)). This ConnectionBuilder implementation will be picked based on the https_required config in auth_config.json. But userinfo endpoint call is not made like above (refer [code](https://github.com/openid/AppAuth-Android/blob/0.7.1/app/java/net/openid/appauthdemo/TokenActivity.java#L366)).

If the userinfo edpoint call is made similar to the token endpoint call, it can facilitate easier testing of AppAuth against development servers.

**Comment by agologan** [comment]
Closing as the proposed change was merged.

**Comment by madurangasiriwardena** [comment]
Hi @agologan,

The PR I have sent regarding this is still open and I don't see the changes are added with a different PR as well. Can you point me to the merged change you are referring to?

Regards,
Maduranga.

**Comment by agologan** [comment]
Sorry for being careless. Could've sworn I saw this change merged.
Thank you for your contribution and for noticing my mistake.

**Comment by madurangasiriwardena** [comment]
Hi @agologan,

No worries. You are welcome and thank you for merging my pull request.

Regards,
Maduranga
