### ISSUE TITLE
Documentation: usage of example.com

### ISSUE THREAD

**Issue by michaelJustin** [openid/AppAuth-Android#471]
In the documentation, usage of example.com is not clear when it refers to the client app and where it refers to some third party service:

> For example, if the web domain for your service is "service.example.com", then the reverse domain name form to use for a custom scheme would be "com.example.service". This is also, typically, the convention used for the package name of your app, e.g. "com.example.app". 

For example, my custom scheme to access the GitHub API would be com.github.service, but my app would not use the com.github domain for its package name.  If the the same "neutral" domain example.com is used for two unrelated things, it is hard to understand the documentation. Suggestion: use distinct example domains names, for example "myapp.example" for the app.

**Comment by agologan** [comment]
Hopefully the change makes it a bit clearer. Closing for now but feel free to reply or [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if there are further questions. 👍
