### ISSUE TITLE
Refresh Token authorization issue

### ISSUE THREAD

**Issue by IstrateAndrei** [openid/AppAuth-Android#472]
Every time I'm calling `performActionWithFreshTokens()` I get 
`AuthorizationException: {"type":2,"code":2002,"error":"invalid_grant","errorUri":""}`

Seen the same issue reported here but without a proper solution/explanation.

**Comment by yasirali133314** [comment]
i'm also facing this same issue.

**Comment by jtn-d** [comment]
Have you requested [Offline Access](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess)?

**Comment by shishirshettygit** [comment]
@IstrateAndrei Do you have any update on this? (Still facing this issue I assume)

**Comment by iainmcgin** [comment]
This is an error message you are receiving from the provider. From the OAuth2 RFC, `invalid_grant` is returned when:

> The provided authorization grant (e.g., authorization code, resource owner credentials)  or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

As this is provider / configuration specific behavior, we can't provide help without more information.

**Comment by varuntribe** [comment]
> Have you requested [Offline Access](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess)?

Hi, how do you ask for offline access with AppAuth?
I have tried adding it as additional param but still no luck.
