### ISSUE TITLE
Is it possible to send the Username and Password instead of redirecting to the SSO

### ISSUE THREAD

**Issue by Johnnie843** [openid/AppAuth-Android#478]
I wanted to make my own custom login and authenticate with the Keycloak SSO, is this possible with AppAuth?

**Comment by devharis** [comment]
You can impl. your custom login together with `grant_type: password`, however it isn't a recommended approach.

**Comment by iainmcgin** [comment]
We explicitly do not support nor recommend password based authentication handled directly by the app.
