### ISSUE TITLE
Authorization code exchange failed

### ISSUE THREAD

**Issue by Leonelli** [openid/AppAuth-Android#479]
Good Morning, 
I develop an App in order to interact with Google Cloud Print API by using the AppAuth Library. In our scenario, after we authorise with Google to fetch the job list from the Google Cloud, after selecting a Job we have to choose a printer which is done inside another activity that start an authentication process on our backend that needs to send a client secret. So, I take a look to the extended demo and add a function to create a request with secret as follows:
```java
 private void createAuthRequest() {
        AuthorizationRequest authRequest = new AuthorizationRequest.Builder(
                mStateManager.getCurrent().getAuthorizationServiceConfiguration(),
                mClientId.get(),
                ResponseTypeValues.CODE,
                mConfigurationApp.getRedirectUri())
                .setScope(mConfigurationApp.getScope())
                .build();
        mAuthService.performAuthorizationRequest(
                authRequest,
                CieTokenActivity.createPostAuthorizationIntent(
                        this,
                        authRequest,
                        null,
                        mConfigurationApp.getClientSecret()),
                mAuthService.createCustomTabsIntentBuilder()
                        .build());
    }
```    

Then, we used the issued token by our backend to process the print request. Beside this, on the App backend I check if the both token (the one issued with Google and the 2nd one issued by the backend are valid).

the first part with google is going well, but when we send a request to the backend for the 2nd token, we got the following error message:

> Authorization Code Exchange Failed:invalid_client

thanks in advance

**Comment by childnode** [comment]
🤷‍♂  I think, your question is better on stackoverflow, since this is an issue tracker for the library - that is actually someway unmaintained, see call for maintainer #444

**Comment by agologan** [comment]
The question does seem outside the scope of this library. Since this is an older topic without enough information to take any action I'm closing it for now. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience other problems or can provide further information how this relates to the lib 👍
