### ISSUE TITLE
how to support multiple  schemes

### ISSUE THREAD

**Issue by satdmail** [openid/AppAuth-Android#481]
I am trying to support multiple oAuths (apple & amazon)  from our app, and i used the code like this:
I have one custom scheme and one HTTPS redirect URI.
> <activity

                android:name="net.openid.appauth.RedirectUriReceiverActivity"
                android:exported="true"
                android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="sampleaoneapp" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                        android:host="com.sxm.sample"
                        android:path="/oauth2redirect"
                        android:scheme="https" />
            </intent-filter>
        

> </activity>

and in gradle file i added like this:
manifestPlaceholders = [
                'appAuthRedirectScheme': 'sampleaoneapp://appleservice'
        ]

For custom sampleaoneapp, it is working, however for the https redirect url, it is trying to open the url in browser, rather than redirecting to app. when i try to find whether redirect URI is handled by any activity it is coming as false.
can anybody help me to find a way to add multiple oAuths

**Comment by VictorAdeva** [comment]
Any help with this? I'm struggling as well

**Comment by satdmail** [comment]
yes, with same code it worked,  my problem was i didn't get intent in my activity , that is just redirection problem.
As long as you added  both intent-filter , you redirection works fine.

**Comment by iainmcgin** [comment]
For HTTPS response handling, your app has to be correctly registered as an app link handler for that domain. See: https://developer.android.com/training/app-links
