### ISSUE TITLE
Report redirect url

### ISSUE THREAD

**Issue by Janos1977** [openid/AppAuth-Android#489]
Hi. I need to log all redirect url with related dates and statuses from my app. If It is possible, how do I do that?
Thx

**Comment by iainmcgin** [comment]
The redirect URIs are passed to your completion handling activity [via the intent](https://github.com/openid/AppAuth-Android/blob/0fbed7df170591bb4d9f20d5e7551e66aaabb4a3/library/java/net/openid/appauth/AuthorizationManagementActivity.java#L264); you should be able to call `getData()` on those Intents.
