### ISSUE TITLE
Not getting token Response Type 0 Error Code -9 Invalid Token

### ISSUE THREAD

**Issue by SaiAshish123** [openid/AppAuth-Android#495]
{
  "client_id": "medicare.mobile",
  "redirect_uri": "net.openid.appauthdemo:/oauth2redirect",
  "authorization_scope": "openid profile offline_access api.medicare.member.local",
  "discovery_uri": "http://account..Dummy.Dummy.com:5001/.well-known/openid-configuration",
  "authorization_endpoint_uri": "http://account..Dummy.Dummy.com:5001/connect/authorize",
  "token_endpoint_uri": "http://account.Dummy.Dummy.com:5001/connect/token",
  "registration_endpoint_uri": "",
  "user_info_endpoint_uri": "",
  "https_required": false
}

AuthorizationException ex = AuthorizationException.fromIntent(getIntent());
         AuthorizationResponse response = AuthorizationResponse.fromIntent(getIntent());

performTokenRequest(authorizationResponse.createTokenExchangeRequest(),this::handleCodeExchangeResponse);

   @MainThread
    private void performTokenRequest(TokenRequest request,AuthorizationService.TokenResponseCallback callback) {
        ClientAuthentication clientAuthentication ;
        try {

            clientAuthentication = mStateManager.getCurrent().getClientAuthentication();

        } catch (ClientAuthentication.UnsupportedAuthenticationMethod ex) {
            Log.d(TAG, "Token request cannot be made, client authentication for the token "
                            + "endpoint could not be constructed (%s)", ex);
            displayNotAuthorized("Client authentication method is unsupported");
            return;
        }

        mAuthService.performTokenRequest(request, clientAuthentication,callback);
    }

M not getting Token Response

**Comment by shishirshettygit** [comment]
@SaiAshish123 is this still an issue? Let me know if you found a solution. Thanks.

**Comment by iainmcgin** [comment]
Without more information, this would appear to be a provider issue.

**Comment by ximenaperez** [comment]
Hi! I'm having this issue as well, I have a very similar setup, I get my authorization code, but then when I follow the request token steps just as on the readme, I get the issue of invalid token id, issuer mismatch, code 9. Anyone know what could be happening?? my scope is openid offline access.

I noticed that on the iOS library they don't have to follow this step and get the token right away on the authorization. Is it possible on android to do that? @shishirshettygit @iainmcgin @SaiAshish123 

Thanks!!
