### ISSUE TITLE
How to make logout from browser in app auth android(identity server)

### ISSUE THREAD

**Issue by karthik9052** [openid/AppAuth-Android#500]

**Comment by Barryrowe** [comment]
Looking at PR #433 might help you find a working solution for this.

**Comment by djdance** [comment]
yes, https://github.com/openid/AppAuth-Android/pull/433#issuecomment-617031510 from 433 works fine.

**Comment by agologan** [comment]
[OpenID Connect RP-Initiated Logout ](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) has been available since `0.8.0`
Closing this issue. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you experience other problems. 👍
