### ISSUE TITLE
Should end_session_endpoint be included inside AuthorizationServiceDiscovery?

### ISSUE THREAD

**Issue by jialvarez** [openid/AppAuth-Android#501]
Typically end_session_endpoint is included in discovery service, but AuthorizationServiceDiscovery doesn't contemplate this endpoint, just authorization, token and userinfo endpoints.

You can read anyway this property from auth_config.json as is instead of reading from discovery, but library is then forcing to code this endpoint outside, while end_session_endpoint usually appears at least in some SSO systems.

```
        if (getConfigString("discovery_uri") == null) {
            mAuthEndpointUri = getRequiredConfigWebUri("authorization_endpoint_uri");

            mTokenEndpointUri = getRequiredConfigWebUri("token_endpoint_uri");
            mUserInfoEndpointUri = getRequiredConfigWebUri("mUserInfoEndpointUri");

            if (mClientId == null) {
                mRegistrationEndpointUri = getRequiredConfigWebUri("registration_endpoint_uri");
            }
        } else {
            mDiscoveryUri = getRequiredConfigWebUri("discovery_uri");
        }

        mLogoutEndpointUri = getRequiredConfigWebUri("end_session_endpoint"); // this need to be coded outside discovery object scope
```

**Comment by gary-archer** [comment]
For the time being you'll need to code your own solution. Also, oidc logout is a draft standard and many vendors implement it differently. My write up + code sample may help - though the code is not as elegant as I'd like: https://authguidance.com/2019/09/13/android-code-sample-overview/

**Comment by jialvarez** [comment]
Thank you Gary.

I've coded my own logout against Keycloak, getting the URI endpoint from separated property instead getting from discovery, but it's working.

Regards!

**Comment by djdance** [comment]
> I've coded my own logout against Keycloak, 

Hi, could you please share you KeyCloak logout implementation?
