### ISSUE TITLE
Dynamically fill appAuthRedirectScheme (in React Native app)

### ISSUE THREAD

**Issue by NemanjaManot** [openid/AppAuth-Android#503]
For my react-native application I am using [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth) library (react native bridge for AppAuth-Android).

I need to fill this info in build.gradle file, for android:

```
android {
  defaultConfig {
    manifestPlaceholders = [
      appAuthRedirectScheme: 'io.identityserver.demo'
    ]
  }
}
```

But _appAuthRedirectScheme_ can be different for some roles of users. And I need to send this scheme directly from react-native components (when I get that scheme/url from another API).

Is there any way to do this?

**Comment by NemanjaManot** [comment]
Any news?

**Comment by AnirudhChakraborty** [comment]
Hi I am facing the same situation. I have two different schemes I want to use in different aspects.
Did you find any solution for this?

**Comment by iainmcgin** [comment]
Registration of redirect handles is a compile-time activity, as it influences the application manifest. It cannot be done dynamically.
