### ISSUE TITLE
how to add SSL pinning to AuthorizationServiceConfiguration

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [openid/AppAuth-Android#505]
I want to add SSL pinning to AuthorizationServiceConfiguration,
How can i do that?

**Comment by witrisna** [comment]
Is it something you looking for https://developer.android.com/training/articles/security-config#CertificatePinning

**Comment by iainmcgin** [comment]
You can specify your own `ConnectionBuilder` to be used to fetch the configuration. Via that, you should be able to specify whatever client-side TLS configuration you need.

https://github.com/openid/AppAuth-Android/blob/0fbed7df170591bb4d9f20d5e7551e66aaabb4a3/library/java/net/openid/appauth/AuthorizationServiceConfiguration.java#L253-L276
