### ISSUE TITLE
PKCE use documentation/example ? 

### ISSUE THREAD

**Issue by sebastienminne** [openid/AppAuth-Android#506]
I'm trying to use AppAuth-Android lib to authenticate my application using  PKCE.
I can't really find any documentation on how to make this lib works with PKCE. 
IS there a specific configuration to set ?

**Comment by martin-ohlin** [comment]
Unless you explicitly turn it off it is on by default, so no need for you to do anything.
Calling `setCodeVerifier(null)` will turn it off if I remember correctly.
