### ISSUE TITLE
Is this library still in active development?

### ISSUE THREAD

**Issue by PatrickGaissert** [openid/AppAuth-Android#507]
Since we are relying on this library in our iOS as well as Android apps, the Android version seems to be effectively EOL. If this is the case, can you suggest an alternative going forward?

**Comment by blundell** [comment]
see #444

**Comment by iainmcgin** [comment]
As far as we are aware everything still works as intended and there has been little change required, other than perhaps officially supporting AndroidX and bumping the SDK versions. If you find issues please do file them, and if possible, submit PRs. This is a community effort.
