### ISSUE TITLE
Can't build with Android Studio

### ISSUE THREAD

**Issue by laoda512** [openid/AppAuth-Android#51]
It seems gradle can't find "org.ajoberstar.grgit.Grgit" ?

Error:(132, 0) Cause: repository not found: /Users/cwang/Downloads/AppAuth-Android-master
<a href="openFile:/Users/cwang/Downloads/AppAuth-Android-master/build.gradle">Open File</a>

**Comment by iainmcgin** [comment]
We all use Android Studio here too for development work on this library, so I'm unsure what is causing your issue. The grgit dependency should be retrieved from maven central / jcenter. Did you import the root of the project into Android Studio, or a specific subfolder (e.g. library)? You should import the root.

The error message you've included seems to indicate that, for whatever reason, your configuration thinks that the AppAuth folder is a repository for dependencies (which it is not).

**Comment by iainmcgin** [comment]
Please reopen if you still can't build and can provide more specific information about your issue.

**Comment by SeaRoth** [comment]
I fixed this by recursively downloading AppAuth instead of downloading the zip file. I'm boosted af.
