### ISSUE TITLE
openIDConnectDiscoveryUri must be https

### ISSUE THREAD

**Issue by sw-tt-chiragdarji** [openid/AppAuth-Android#511]
How to call non https url 
Like http://192.168.1.1/auth etc.

we are facing below issue when call AuthorizationServiceConfiguration.fetchFromIssuer(
                Uri.parse("http://192.168.1.1/auth"),
                RetrieveConfigurationCallback { serviceConfiguration, ex ->
                    if (ex != null) {
                        AndroidLog.e("LoginViewModel", "failed to fetch configuration")
                        //return@RetrieveConfigurationCallback
                    } else {
                        this.serviceConfiguration = serviceConfiguration
                    }
                    // use serviceConfiguration as needed
                })

Run time Error 
 W/System.err: java.lang.IllegalArgumentException: openIDConnectDiscoveryUri must be https

**Comment by iainmcgin** [comment]
By default, AppAuth requires https URIs for all endpoints to protect apps against man in the middle or content rewriting attacks. You can bypass this by using your own `ConnectionBuilder`, which is what the demo app does if you specify https is not required.

See: 
- https://github.com/openid/AppAuth-Android/blob/0fbed7df170591bb4d9f20d5e7551e66aaabb4a3/app/res/raw/auth_config.json#L10
- https://github.com/openid/AppAuth-Android/blob/0fbed7df170591bb4d9f20d5e7551e66aaabb4a3/app/java/net/openid/appauthdemo/Configuration.java#L169-L174
- https://github.com/openid/AppAuth-Android/blob/master/app/java/net/openid/appauthdemo/ConnectionBuilderForTesting.java
