### ISSUE TITLE
idphint for google and facebook login like javascript adapter

### ISSUE THREAD

**Issue by Allan-Nava** [openid/AppAuth-Android#512]
Is possible to use the same flow of javascript adapter?

```javascript
keycloak.createLoginUrl({
                idpHint: "facebook",
            })
```

**Comment by ybenkhaled** [comment]
Hi,

The code you provided is for `keycloak.js` and the paramater `idpHint `is translated to `kc_idp_hint` in the final URI.
I just give a try with the lib and you can achieve this by using `additionalParameters `when building your `AuthorizationRequest`.

```
final Map<String, String> params = new HashMap<>();
params.put("kc_idp_hint", "facebook");
final AuthorizationRequest.Builder authRequestBuilder = new AuthorizationRequest.Builder(...).setAdditionalParameters(params);
```

**Comment by Allan-Nava** [comment]
I solved this issue and it works, now I need to implement with the mvp pattern #517
