### ISSUE TITLE
OpenID connect Discovery return value

### ISSUE THREAD

**Issue by Puru1653** [openid/AppAuth-Android#516]
I tried with below code for discovery document 
AuthorizationServiceConfiguration serviceConfig =
    AuthorizationServiceConfiguration.fetchFromIssuer(.....

But, the return type of this method is void and hence serviceConfig is always null. I have even tried with 
AuthorizationServiceConfiguration serviceConfig =  AuthorizationServiceConfiguration.fetchFromIssuer( Uri.parse("https://idp.example.com"),  new RetrieveConfigurationCallback() { public  void onFetchConfigurationCompleted(
              @Nullable AuthorizationServiceConfiguration serviceConfiguration,
              @Nullable AuthorizationException ex) {            if (ex != null) {              Log.e(TAG, "failed to fetch configuration");              return;            }            // use serviceConfiguration as needed          }       });
Tried assigning serviceConfig = serviceConfiguration inside onFetchConfigurationCompleted() But, here the control is not entering into onFetchConfigurationCompleted().

**Comment by juanmendez** [comment]
yes, readme has it stated as you mention. but in reality this is an asynchronous operation which is handled by RetrieveConfigurationCallback, which is the second argument in `fetchFromIssuer`. 
There you are going to be able to get access to `serviceConfig`..  maybe I am talking too much, just see the source code for `fetchFromIssuer` method

**Comment by iainmcgin** [comment]
Looks like we need to clarify the documentation here.

**Comment by agologan** [comment]
`fetchFromIssuer()` example was updated in f4f7bc2a8d8394e2172ad9dc3acd1aabb3ade1c2 and 
`fetchFromUrl()` example was update in fc8ee991392b14e7845aa58f959763f7b0bea550

Closing
