### ISSUE TITLE
Implement the AppAuth-Android with the MVP pattern

### ISSUE THREAD

**Issue by Allan-Nava** [openid/AppAuth-Android#517]
Yes, it's possible to implement with MVP. but that's another question/answer away from this issue.

_Originally posted by @juanmendez in https://github.com/openid/AppAuth-Android/issues/91#issuecomment-583743416_

Example of implementation for MVP pattern?

**Comment by Giovanni-94** [comment]
+1

**Comment by Allan-Nava** [comment]
Any news? 
I got the same error #91

**Comment by juanmendez** [comment]
you turned my answer into an issue, why!?, even the title is not a good description for anyone else to understand what this is about. Implementing MVP is not an issue with the library, the library is independent from it. You need to first make sure the library work, then think how you can refactor to make it useful with MVP. Your presenter can simply be about delegating to the view to initiate authentication, and for the view to report back to the presenter if there are any exceptions, or your tokens are back, or if you need to decrypt in the view any token and provide a data structure instead to your presenter. From there on the presenter can ask the view to jump to another activity/fragment.. etc.. It's not a lot you can do in the presenter.

**Comment by Allan-Nava** [comment]
> you turned my answer into an issue, why!?, even the title is not a good description for anyone else to understand what this is about. Implementing MVP is not an issue with the library, the library is independent from it. You need to first make sure the library work, then think how you can refactor to make it useful with MVP. Your presenter can simply be about delegating to the view to initiate authentication, and for the view to report back to the presenter if there are any exceptions, or your tokens are back, or if you need to decrypt in the view any token and provide a data structure instead to your presenter. From there on the presenter can ask the view to jump to another activity/fragment.. etc.. It's not a lot you can do in the presenter. I did something similar using MVVM.

You are right mate! But i have the problem with leak

**Comment by juanmendez** [comment]
are you implementing this in your `onStop` or `destroy` handlers? Ignore this is written in Kotlin.
```
authService?.dispose()
authService = null 
```

**Comment by Allan-Nava** [comment]
> are you implementing this in your `onStop` or `destroy` handlers? Ignore this is written in Kotlin.
> 
> ```
> authService?.dispose()
> authService = null 
> ```

yess but it doesn't work, still have the same problem

**Comment by juanmendez** [comment]
are you using this?
```
<activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="yourScheme"/>
            </intent-filter>
        </activity>
```

**Comment by juanmendez** [comment]
If you see the lifecycle https://static.javatpoint.com/images/androidimages/Android-Activity-Lifecycle.png, the activity can be stopped and be created again. That object authService cannot be kept alive and that's why I make sure to dispose it, and ensure it is null by the time the activity is started again when coming from RedirectUriReceiverActivity. There after `onActivityResult` which happens prior to onResume is targetted. There you will see the data coming back. If I were you I would avoid any other code in `onActivityResult`, set a breakpoint, and check the data as well as evaluate authService if it's null. See what happens

**Comment by juanmendez** [comment]
when you get to the Custom Tab, see the activity stack using 
`adb shell dumpsys activity activities | grep yourAppProjectId | grep Hist`. This helps you to realize what's going on. Hope all this helps. Just go one step at a time.

**Comment by Allan-Nava** [comment]
> are you using this?
> 
> ```
> <activity
>             android:name="net.openid.appauth.RedirectUriReceiverActivity"
>             tools:node="replace">
>             <intent-filter>
>                 <action android:name="android.intent.action.VIEW"/>
>                 <category android:name="android.intent.category.DEFAULT"/>
>                 <category android:name="android.intent.category.BROWSABLE"/>
>                 <data android:scheme="yourScheme"/>
>             </intent-filter>
>         </activity>
> ```

I got this!

**Comment by Allan-Nava** [comment]
Fixed thanks!
