### ISSUE TITLE
AuthorizationResponse.fromIntent & AuthorizationException.fromIntent return null

### ISSUE THREAD

**Issue by luckyhandler** [openid/AppAuth-Android#519]
When following the official guideline for intercepting the Authorization Code response, the following snippet is recommended:

```java
AuthorizationResponse resp = AuthorizationResponse.fromIntent(getIntent());
AuthorizationException ex = AuthorizationException.fromIntent(getIntent());
```
Though, the activity is correctly intercepting the event and the intent contains the url with authorization code, both functions return null.

--------
Sony Xperia XZ 3, Android 10
Security Patch December 2019

**Comment by iainmcgin** [comment]
Without more information on how you are triggering the authorization request, and the contents of the intent that triggers your activity on completion, I can't do much to help. Does the demo app work as expected on your device? The demo app triggers the authorization flow [here](https://github.com/openid/AppAuth-Android/blob/0fbed7df170591bb4d9f20d5e7551e66aaabb4a3/app/java/net/openid/appauthdemo/LoginActivity.java#L351-L367), and handles the response [here](https://github.com/openid/AppAuth-Android/blob/0fbed7df170591bb4d9f20d5e7551e66aaabb4a3/app/java/net/openid/appauthdemo/TokenActivity.java#L125-L128).

**Comment by agologan** [comment]
Closing this as there has been no response to our request for more information from the OP in a reasonable amount of time. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍
