### ISSUE TITLE
Dynamic Client Registration

### ISSUE THREAD

**Issue by asharif1990** [openid/AppAuth-Android#520]
Hello, 

I would like to ask if anyone uses the dynamic client registration method to register the public key with the server using AppAuth? I tried to add the JWKS parameter through using  setAdditionalParams() , but it seems not working, any help appreciated. 

thanks in advance

**Comment by juanmendez** [comment]
hope this helps....

```
fun dynamicRegistration() {
    AuthorizationServiceConfiguration.fetchFromIssuer(
        Uri.parse(SITE_URL)
    ) { authServiceConfig, authException ->
        authServiceConfig?.let { configuration ->
            authState = AuthState(configuration)
            
            val request = RegistrationRequest.Builder(
                authServiceConfig,
                listOf(Uri.parse(YOUR_SCHEME))
            ).build() // i believe you call setAdditonalParams(map) before build()

            authService.performRegistrationRequest(request) { regResponse, authException ->
                regResponse?.let { response ->
                    // we were able to register!!!
                } ?: authException?.let { exception ->
                    // issue with performRegistrationRequest
                }
            }
        } ?: authException?.let {
            // issue with fetchFromIssuer
        }
    }
}
```

**Comment by juanmendez** [comment]
If the library cannot detect the location of your openid config, maybe you need to do it manually as it describes in the homepage in how to configure `AuthorizationServiceConfiguration`

**Comment by asharif1990** [comment]
@juanmendez : thanks for your response, I already managed to create a request by using the library and setting additional parameters. what I encountered so far is that I got 

> Network Error. Error code:3

Firstly, I thought it could be due to the fact that I need to set the `Authorization` header. I set it as well, but I still got the same error. do you have any idea? 

thanks in advance
Amir

**Comment by asharif1990** [comment]
I enclosed my code to provide you with more details on how my code looks like:

    `RegistrationRequest registrationRequest = new RegistrationRequest.Builder(
                mAuthStateManager.getCurrent().getAuthorizationServiceConfiguration(),
                Collections.singletonList(mConfiguration.getRedirectUri()))
                .setTokenEndpointAuthenticationMethod("private_key_jwt")
                .setAdditionalParameters(additionalParams())
                .build();
`
> additionalParams()

`
   private HashMap<String,String> additionalParams() {
       
        HashMap<String, String> map = new HashMap<>();
        map.put("jwks", "{\"keys\": [{\"kty\": \"RSA\",\"e\":\"AQAB\",\"kid\": \"key1\",\"n\":\"AJncrKuine49_CEVR4GPn.....zOrouIUCSMlRL0HU=}]}");
        map.put("client_name","test3245");
        return map;
    }
`

**Comment by juanmendez** [comment]
You may have to do some digging inside `build()` to know how it takes the jwks entry set. Have you tried `AuthorizationServiceConfiguration.fetchFromIssuer(Uri.parse(SITE_URL))? As I mentioned it allowed me to skip adding additional parameters.

**Comment by aleksz** [comment]
@juanmendez I'm running into same issue as @asharif1990 . I have a feeling that there are 2 separate key sets mixed here. The one that @asharif1990 is trying to set is client's jwks, the one resolved by AuthorizationServiceConfiguration is for oidc provider. jwks property in dynamic client registration is supposed to be a JSON object, but additionalParameters is just <String,String>. Is there any way to set jwks property to JSON object?

**Comment by agologan** [comment]
@asharif1990 the way you are setting additional parameters is correct. (not sure if the rest of your registration request params are what you want)
Please provide the actual error you are running into.

@aleksz the purpose of `setAdditionalParameters` is to give you the ability to specify params which haven't been formally added to the lib.
You provide a dictionary of **key -> serialized value** and the lib will add each key as a param to the request.
In this case if you want to set `jwks` add it as a key to the dictionary and the JSON as an already converted string value.
Or another example if you wanted to provide `logo_uri` add that to the dictionary and provide the URL as the value.

**Comment by aleksz** [comment]
@agologan if I serialise jwks to string, wouldn't it result in string jwks value? Like
```
{
  jwks: "{}"
}
```
vs
```
{
  jwks: {}
}
```

and jwks is supposed to be a JSON object, not string containing JSON

**Comment by agologan** [comment]
You are right. 👍 
This wouldn't work for this use-case.
We need to add proper support in the lib.

**Comment by agologan** [comment]
@aleksz do you mind testing these new changes?
You can grab a build via: https://jitpack.io/#openid/AppAuth-Android/

**Comment by ikopenkov** [comment]
> @aleksz do you mind testing these new changes?
> You can grab a build via: https://jitpack.io/#openid/AppAuth-Android/

Hey, thanks for the changes! I've checked them, `jwks` is successfully passed to the API.

Seems like the only thing left is to add this parameter to the `register` method of `react-native-app-auth`, since if it's passed via `additionalParams` it fails as it should be `HashMap<String, String>` 🙂

**Comment by agologan** [comment]
Glad to hear that.
We will include this in our next release.

Closing this issue.
