### ISSUE TITLE
Synchronous requests

### ISSUE THREAD

**Issue by EscapeArtist** [openid/AppAuth-Android#524]
Hi there.
Is there a way to perform the Token Request synchronously, without using the callbacks?
I'm trying to make refresh the token from an OkHTTP interceptor but the callback nature of the performTokenRequest makes it impossible to return the response in the same call.
Thanks.

**Comment by michaeltnguyen** [comment]
@EscapeArtist did you figure this out?

I think you could do something with a countdown latch and wait in the interceptor, but it's a bit awkward.

**Comment by michaeltnguyen** [comment]
I ended up just rewriting their `AsyncTask` synchronously and shoving it in `AuthStateManager`.

You can also attempt some reflection and instantiate the `RequestTokenTask` that way, and call

```
JSONObject response = doInBackground();
onPostExecute(repsonse);
```

**Comment by nabraas60000** [comment]
Hi

**Comment by nabraas60000** [comment]
> Hi

https://github.com/openid/AppAuth-Android/issues/524#issuecomment-663086746
