### ISSUE TITLE
'Refresh token expired exception'

### ISSUE THREAD

**Issue by essieM** [openid/AppAuth-Android#531]
Hi,

I'm using appAuth with Keycloak for authenticationin my android app. After about 25 minutes, the access token expires. When I try to refresh the token after this period, I get this error:

`Failed to authorize = AuthorizationException: {"type":2,"code":2002,"error":"invalid_grant","errorDescription":"Refresh token expired","errorUri":""}` 

To refresh the token, I'm calling `performActionWithFreshTokens` and passing in the refreshToken I received earlier from the TokenResponse.

   `Map<String, String> refreshTokenAdditionalParams = new HashMap<>();
            refreshTokenAdditionalParams.put(Constants.REFRESH_TOKEN,getAuthState().getRefreshToken());
            Log.i(TAG, "Refresh Token from AuthState:"+ getAuthState().getRefreshToken());

        mAuthStateManager.getCurrent().performActionWithFreshTokens(mAuthService,clientAuthentication,refreshTokenAdditionalParams, (accessToken, idToken, ex) -> {
            Log.i(TAG, "Access Token :"+ accessToken + "id Token :"+ idToken );
            Log.i(TAG, "Token Response :"+ mAuthStateManager.getCurrent().getLastTokenResponse());
            if (ex != null) {
                // negotiation for fresh tokens failed, check ex for more details
                if (ex.errorDescription.contains(Constants.TOKEN_EXPIRED)) {
                    CommonHelper.getAccessDeniedFailure(false);
                    return;
                }
            }

            mAuthStateManager.getCurrent().update(mAuthStateManager.getCurrent().getLastTokenResponse(), ex);
            if (getAuthState().isAuthorized()) {
                SessionManager.UserDetail detail = sessionManager.getUserDetails();
                if (detail == null) {
                    detail = new SessionManager.UserDetail();
                }
                detail.updateAuthToken(getAuthState().getAccessToken());
                detail.updateRefreshToken(getAuthState().getRefreshToken());
                sessionManager.createUserSession(detail);
                sessionManager.setLastActivityTime(System.currentTimeMillis());
            }
            callback.onTokenRequestCompleted(mAuthStateManager.getCurrent().getLastTokenResponse(), ex);

        });`
Before deciding to pass in the refreshToken as additionalParameters in the function, I thought the fact that I'm calling `performActionWithFreshTokens` would automatically solve this exception. I still got the error. Then I decided to pass in the refreshToken as a parameter but I still get the exception and the returned accessToken and idToken are null.

I'm not sure how else to resolve this issue.

**Comment by agologan** [comment]
No need to pass in the refreshToken again for `refreshTokenAdditionalParams`, that param is used just to pass in extra information to the refresh request.

Judging by the error, you're getting you haven't refreshed the token in the allocated time and it expired.

There may be multiple reasons why your refresh token expired that can only be answered by looking at your KeyCloak configuration.

**Comment by essieM** [comment]
@agologan thanks for your feedback. I may be wrong, but my assumption was that refresh tokens do not expire? 

What sort of configuration information should I be looking at on KeyCloak? Do you mind pointing me in the right direction?

**Comment by agologan** [comment]
Refresh tokens expire, and their lifecycle actually determine the session length, as in if you're no longer able to refresh your access token or obtain a new refresh token than your session has ended.
Two most common reasons in KeyCloak are **SSO Session Idle**  and **SSO Session Max**.

**Comment by priyankkasera** [comment]
I have already changed the settings of **SSO Session Idle** and **SSO Session Max** to 30 days, still i am getting the same error after token expiration. can any one please come up with a solution.

**Comment by iainmcgin** [comment]
As this appears to be an issue with Keycloak rather than AppAuth, I will close this issue. Please raise your question via the appropriate channel for Keycloak support.

**Comment by fukemy** [comment]
hi, can i ask a question: How did u detect if token expired?

**Comment by agologan** [comment]
@fukemy unsure I understand the question, without further context but an 401 response is usually a good indication the token is expired. See this topic https://github.com/openid/AppAuth-Android/issues/747 for further information about detecting 401 vs `performActionWithFreshTokens` and checking expiration time via `getNeedsTokenRefresh`.

_Feel free to open an new topic of type question providing further context if you still need help._
