### ISSUE TITLE
The meaning of user_info_endpoint_uri isn't explained in https://github.com/openid/AppAuth-Android/tree/master/app although it seems to be a required parameter

### ISSUE THREAD

**Issue by lsh-silpion** [openid/AppAuth-Android#534]
Could you please add a section to https://github.com/openid/AppAuth-Android/tree/master/app where the meaning of `user_info_endpoint_uri` gets explained? The App seems to require it, at least it is barfing at me when I don't set it.

Thanks!

**Comment by iainmcgin** [comment]
This is the user info endpoint described in the OpenID Connect Core (OIDC) specification: https://openid.net/specs/openid-connect-core-1_0.html#UserInfo

If an OIDC discovery document URI is specified, the value isn't required. Without a discovery document, the Configuration class requires a value to be specified: https://github.com/openid/AppAuth-Android/blob/f1dbeb51f4d905523d804d70363abdb00728d99c/app/java/net/openid/appauthdemo/Configuration.java#L208-L219

This is overly strict, as the code that actually uses this value is conditional:  https://github.com/openid/AppAuth-Android/blob/f1dbeb51f4d905523d804d70363abdb00728d99c/app/java/net/openid/appauthdemo/TokenActivity.java#L226-L228

So, you could make a small tweak to the Configuration class to make this optional.
