### ISSUE TITLE
No Stored State Error

### ISSUE THREAD

**Issue by jajmo** [openid/AppAuth-Android#535]
My auth URL triggers a second app on my device. Every time it returns to the original app, I get the AppAuth error:

`W/AppAuth: No stored state - unable to handle response`.

I followed the README code, and haven't made any additional modifications to the source code. 

I noticed that it is caused by the `onCreate` of `AuthorizationManagementActivity`. When the app is resumed after SSO login, the `savedInstanceState` parameter is `null`, and the resulting intent doesn't have any extras (since it was created from `createBaseIntent` after the URI receiver was triggered). 

Any ideas for what I could try? I have the source code included in my project so I could try things locally as necessary.

Thanks!

**Comment by jajmo** [comment]
Resolved. I had to change the `launchMode` of `AuthorizationManagementActivity` to `singleInstance` in the project's manifest.

**Comment by flowbe** [comment]
@jajmo Thanks, it solved the issues for us too!
