### ISSUE TITLE
Veracode Flaws Error

### ISSUE THREAD

**Issue by PikselMobileTeam** [openid/AppAuth-Android#551]
Hi,
using Veracode static scan, an error is raised. Have you any idea as mitigate this error? Is a false positive?

<img width="999" alt="Screenshot 2020-06-03 at 23 01 05" src="https://user-images.githubusercontent.com/63742632/83688949-7d3a6580-a5ee-11ea-95e1-8e6a782b02a9.png">

Here the second error

![image (12)](https://user-images.githubusercontent.com/63742632/83741377-6b8da800-a658-11ea-8ad8-55cfdf08e64b.png)

**Comment by agologan** [comment]
Having ran Veracode scanning myself I know it doesn't correctly report those issues.
For the first one I think the reporting improved but it's still overprotective and thinks the intent filter is too much.
For the latter, the way the code is structured it cannot determine the stream is closed unless you put everything in the same function call.

_Closing this. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you require further assistance 👍_
