### ISSUE TITLE
Using DefaultConnectionBuilder for production code

### ISSUE THREAD

**Issue by deka91** [openid/AppAuth-Android#563]
I used the class ConnectionBuilderForTesting from the sample app, which accepts all certificates.

` val builder = AppAuthConfiguration.Builder()
        builder.setConnectionBuilder(ConnectionBuilderForTesting.INSTANCE)
        authService = AuthorizationService(this, builder.build())`

Of course we don't want this for production code, so I tried to use the DefaultConnectionBuilder which only allows https connections:

`  val builder = AppAuthConfiguration.Builder()
        builder.setConnectionBuilder(DefaultConnectionBuilder.INSTANCE)
        authService = AuthorizationService(this, builder.build())`

But when I use it I always get the following network error for the token request:

AuthorizationException: {"type":0,"code":3,"errorDescription":"Network error"} 
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

Then I tried to init the AuthorizationService without a ConnectionBuilder with the same error.

Do I miss something here?

**Comment by balkarov** [comment]
```java
private static Uri buildConfigurationUriFromIssuer(Uri openIdConnectIssuerUri) {
        return openIdConnectIssuerUri.buildUpon()
                .appendPath(AuthorizationServiceConfiguration.WELL_KNOWN_PATH)
                .appendPath(AuthorizationServiceConfiguration.OPENID_CONFIGURATION_RESOURCE)
                .build();
    }
```

```java
AuthorizationServiceConfiguration.fetchFromUrl(buildConfigurationUriFromIssuer(issuer), (serviceConfiguration, ex) -> {

}, ConnectionBuilderForTesting.INSTANCE);
```

Or you can use this PR
https://github.com/openid/AppAuth-Android/pull/594

**Comment by agologan** [comment]
Closing this as there hasn't been any recent activity which may mean the OP resolved his issue or that he has abandoned it and can't provide further clarifications to his problem. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍
