### ISSUE TITLE
How to provide callback url

### ISSUE THREAD

**Issue by mckavan** [openid/AppAuth-Android#565]
My auth server need a callback url(path) as a parameter like AuthorizationEndpoint, TokenEndpoint. I wasn't able to find where to send it. Is this supported in the library?

**Comment by ibrahim003** [comment]
> My auth server need a callback url(path) as a parameter like AuthorizationEndpoint, TokenEndpoint. I wasn't able to find where to send it. Is this supported in the library?

**Comment by agologan** [comment]
`redirectUri` on [AuthorizationRequest.java#L605](https://github.com/openid/AppAuth-Android/blob/fc8ee991392b14e7845aa58f959763f7b0bea550/library/java/net/openid/appauth/AuthorizationRequest.java#L605) via the Builder constructor or the setter ?!

Don't forget to define the redirect scheme as explained in [Capturing the authorization redirect
](https://github.com/openid/AppAuth-Android#capturing-the-authorization-redirect)

Closing this as I doubt the OP needs further clarification.
Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if encounter other issues. 👍
