### ISSUE TITLE
I am getting invalid scheme

### ISSUE THREAD

**Issue by adKaranChhabra** [openid/AppAuth-Android#570]
Hi, 

I am using this scheme and getting invalid scheme while opening browser. Please help. Is there anything wrong in scheme ?

 <activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="com.developer.auth_service" />
            </intent-filter>

**Comment by hnljp** [comment]
Check the allowed characters for the sheme:
https://tools.ietf.org/html/rfc3986#section-3.1

Underscore is not allowed.


Med venlig hilsen
Henning Nielsen Lund

Softwareudvikler, Native Apps Team



Jyllands-Posten | JP Medier

Mediebyen 3, 8000 Aarhus C

________________________________

**Comment by adKaranChhabra** [comment]
Can you please suggest what schema can I use in this case ? as my app is published with underscore..and I want to integrate auth service in that.

**Comment by adKaranChhabra** [comment]
Is there any other way to remove this error.... ?

**Comment by geoffreytan** [comment]
Hi there,
I am also in the same case.
Any way to resolve this ?

**Comment by agologan** [comment]
@adKaranChhabra the uri scheme does NOT need to match your package name or some specific domain.
You can use any string you like as long as it makes sense to you.
Can also have a more complex URI: https://developer.android.com/guide/topics/manifest/data-element
e.g.
```
<data
    android:scheme="myorg"
    android:host="myapp"
    android:path="/auth" />
``` 
Which translates to a redirect uri of `myorg://myapp/auth`

@hnljp Thank you for clarifying the list of allowed characters via the RFC.
