### ISSUE TITLE
Facing Issue with google signin in my published app.

### ISSUE THREAD

**Issue by adKaranChhabra** [openid/AppAuth-Android#572]
Hi, 

If I want to integrate google signin with in my published app which has underscore in package name...What Scheme I can use in manifest? Please suggest.

**Comment by agologan** [comment]
I do hope you have figure this out, but you can define any scheme you want, it doesn't need to be your app bundle (it's just a common practice).
So if you app bundle is `com.my_app_so_cool` you can use `myappneedsauth://` without any issues.

Closing this but feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you run into other issues. 👍
