### ISSUE TITLE
How can I set token life time

### ISSUE THREAD

**Issue by AmioLee** [openid/AppAuth-Android#579]
I want to change the expiration time of the token instead of the default 8 hours when use refresh api, but I don’t see any api to set it

**Comment by GSpanakos** [comment]
Token lifetime is not set from your App Auth client. It is a configuration managed from your Identity Provider(eg Identity Server 4) If you're using IdS4 check their [docs](http://docs.identityserver.io/en/dev/reference/client.html)

**Comment by blundell** [comment]
Closing as not an issue.
