### ISSUE TITLE
When refreshing token, library is calling two endpoints

### ISSUE THREAD

**Issue by HaydnDias** [openid/AppAuth-Android#583]
When using the refresh token to get a new access_token, the library is calling /connect/authorize followed by /connect/token when it should only need the latter? Any reason why this behaviour happens, is it a configuration issue on our side?

Many thanks

**Comment by blundell** [comment]
Please create a Minimal Reproducible Example of the problem you are having, so others can validate/investigate.

**Comment by HaydnDias** [comment]
Hi @blundell This might be an issue with the expo-app-auth library, but when calling refreshAsync it calls /connect/authorize before calling /connect/token. Will close this for now until I've done more investigation, apologies.
