### ISSUE TITLE
PKCE Code Challenge is shorter than a SHA256 hash?

### ISSUE THREAD

**Issue by AndreasDolphin** [openid/AppAuth-Android#586]
Hello!

## Background
I'm writing an OpenID Connect compliant authorization service, or trying to anyway, and I've bumped into something that stumps me when using AppAuth in our app.

## Issue
I've done a tiny test implementation app which in the least amount of code contacts my service and successfully performs the authorization, but then I get these values returned to my service from AppAuth for the token exchange. 
* Code Challenge: `FOKi9M7Il2kYCIiw2aq-T4cMqBMvEcyIAgwZFC0G61Y`, it is my understanding that this is a string that has been SHA256 hashed and then base64URL-encoded, but it's too short to be either for a valid Code Challenge? On the other hand it has the exact length of the minimum value Code Verifier?
* Code Verifier: `bdjyPcDJfShzt6FS7i5AR0_TzH4eOMbDZnYmVo_xIWsWzM3ZgyZQe-XjXZJ1CGJvM250Qvk_Vzdxr0CpHmwyAg`, this is a valid code verifier according to the standard, not too long or too short or any illegal characters, but how does it become the above Code Challenge? And suspiciously it matches the length of an encoded hash of a min length code verifier...

As the lengths seems to match the opposite value I've tried hashing and encoding the Code Challenge instead, thinking I was doing things backwards, but that does not match the Code Verifier instead, which it really shouldn't, right? Result is: `NzQ0MmE2NjkxMzMzY2UyNjBiYjJkZDkxNjY1ZTYzYzk2OTcwYzQ4NWEyNTIzMjAwNDBhMTRkZDViMDcyMDYwNA`

If I encode the hash of the Code Verifier, which I think is what I am supposed to do, and then match it against the Code Challenge, it ends up as `MTRlMmEyZjRjZWM4OTc2OTE4MDg4OGIwZDlhYWJlNGY4NzBjYTgxMzJmMTFjYzg4MDIwYzE5MTQyZDA2ZWI1Ng` which is far from matching `FOKi9M7Il2kYCIiw2aq-T4cMqBMvEcyIAgwZFC0G61Y`. 

I've been going through a number of examples and various documentation but I'm honestly not sure what I'm missing here, although I just came back after a break to this code, it is Friday afternoon and I am somewhat sleep deprived, so I wouldn't be surprised if I've missed something obvious.

Thankful for any type of advice or suggestion on what is going wrong here 😅

**Comment by AndreasDolphin** [comment]
It was my derp, I was returning the hash as string in PHP instead of bytes. 😞

**Comment by Hmawn** [comment]
#586

**Comment by Hmawn** [comment]
#586

**Comment by jason453** [comment]
#
