### ISSUE TITLE
On a few devices,  the browser is not closing after Google sign in

### ISSUE THREAD

**Issue by Bloubloublou** [openid/AppAuth-Android#590]
Hi!

There are some problems similar to this https://github.com/openid/AppAuth-Android/issues/550 on some users' devices and I am not able to reproduce it : on a few devices, at the end of a Google sign in, the browser doesn't close. Could it be related to the fact they don't have Chrome as default browser ? (as seen in a comment here https://github.com/openid/AppAuth-Android/issues/444)

I've searched for answers and cannot see what's wrong. (for example I checked https://github.com/openid/AppAuth-Android/issues/527 and I've a custom appAuthRedirectScheme :) ). 

Here is a part of my manifest : 
`        <activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="http"
                    android:host="XXX"
                    android:path="XXX"/>
            </intent-filter>
        </activity>`

**Comment by agologan** [comment]
For http based redirects you need to implement https://developer.android.com/training/app-links/index.html or the user will be met with a disambiguation dialog where he can select to **always** open the redirect in browser.
If that happens the only way to get back to open it in app is to reset the browser association in settings.

**Comment by agologan** [comment]
Closing this as there has been no other response from the OP. Assuming the issue has been resolved. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍
