### ISSUE TITLE
Changes needed when targetting SDK 30+

### ISSUE THREAD

**Issue by chrisbanes** [openid/AppAuth-Android#599]
The new [package visibility](https://developer.android.com/about/versions/11/privacy/package-visibility) changes in Android 11 means that all of the `queryIntentActivities()` call [BrowserSelector.java](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/browser/BrowserSelector.java) is broken.

As per the [docs](https://developer.android.com/training/basics/intents/package-visibility-use-cases#open-urls), the following should be added to your app's manifest when targeting SDK 30 and above:

``` xml
<manifest>
   <application>
       <blah />
   </application>

    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>

        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>

</manifest>
```

**Comment by marinantonio** [comment]
I can confirm this, after targeting SDK 30 I'm getting following error when trying to `getAuthorizationRequestIntent`:

```
Caused by: android.content.ActivityNotFoundException
at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(AuthorizationService.java:372)
at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(AuthorizationService.java:267)
```

**Comment by childnode** [comment]
correct, #558 has been merged

release schedule is tracked in #578 (including information how to get snapshot builds)

**Comment by peshkira** [comment]
> Edit, now looking at the commits, this issue has been addressed just not released 0875455
I have tried the snapshot of 0875455 (as described in #578) and the app still crashes with ActivityNotFoundException for me?

Were you able to resolve it @marinantonio ?

**Comment by peshkira** [comment]
Ah got it. My mistake. I thought the `queries` portion is provided by app auth and will be auto merged via the manifester merger.

I added it and now it works. Thanks.

**Comment by agologan** [comment]
@peshkira we have modified that fix to be part of the library manifest thus including it via the manifest merge process.
Once we get some time we'll publish an official release including this fix.

@chrisbanes Thank you for reporting this.

**Comment by Nimrodda** [comment]
@agologan I noticed your PR left out one of the queries suggested by Chris and opened a PR for it. Please see #629.

**Comment by IgorGanapolsky** [comment]
This is still happening when targeting `API 31`.  Is there a fix?

**Comment by agologan** [comment]
@IgorGanapolsky Please open a new issue describing the problem you're seeing. I have yet to test the new SDK.

**Comment by Allan-Nava** [comment]
What is the fix?

**Comment by agologan** [comment]
Just tested this on sdk31 and haven't seen the issue mentioned by the OP.
Please open a new issue describing the problem you're encountering.

_Locking this issue to avoid further comments without proper context._
