### ISSUE TITLE
How to implement Logout Uri? 

### ISSUE THREAD

**Issue by kushanshah11** [openid/AppAuth-Android#603]
Hi, 
Can anyone please let me know how to implement Logout URi for logout?

i have setprompt = login in builder but it is not working.

i have also added Logout as per demo in token activity but its not working my goal is to delete login history from browser if it is deleted my issue will be reesolved.
 
in my app every time user have to perform login.

Help will be appreciated.

Thanks in advance.

**Comment by blundell** [comment]
I'm not quite sure what you mean.

Add a button to your app to perform logout.

To logout client side, you delete any access & refresh tokens you have persisted, and if using a WebView then clear its cache & cookies.

To logout server side, you need to create your own api call to tell the server your user is logging out.

What is it that you cannot do?

**Comment by agologan** [comment]
If you're interested in logging out your SSO session you may want to look into this PR: https://github.com/openid/AppAuth-Android/pull/525

The flow is similar to authorization: create an `EndSessionRequest` with `AuthorizationServiceConfiguration` and the current `idToken`, then **startActivity** with intent from `AuthorizationService.getEndSessionRequestIntent()`.
This will start an activity with a webview which will logout the session from your service clearing any cookies along with it.

**Comment by blundell** [comment]
Closing as no further information added in 3+ months.
