### ISSUE TITLE
Make `AuthorizationRequest.state` optional?

### ISSUE THREAD

**Issue by mhelder** [openid/AppAuth-Android#615]
I'm in the process of implementing an auth challenge against a server that does not seem to support the `state` parameter very well. Basically the parameter isn't returned as part of the `AuthorizationResponse` (so it's `null`), which causes the `AuthorizationManagementActivity` to propagate an `AuthorizationException.STATE_MISMATCH`:

https://github.com/openid/AppAuth-Android/blob/0875455b1390c49c4d6b2aaeee01a3cbf93d3407/library/java/net/openid/appauth/AuthorizationManagementActivity.java#L324-L332

Currently, there doesn't seem to be a way to opt out of the `state` parameter in the request. When constructing an `AuthorizationRequest.Builder` a `state` parameter with a random value is automatically generated, and `setState` does not allow for it to be set to null or an empty string.

https://github.com/openid/AppAuth-Android/blob/27b62d5da94023941db545b70036a742a52b7070/library/java/net/openid/appauth/AuthorizationRequest.java#L591

https://github.com/openid/AppAuth-Android/blob/27b62d5da94023941db545b70036a742a52b7070/library/java/net/openid/appauth/AuthorizationRequest.java#L781-L783

I realise the RFC indicates it's _recommended_ to include the  parameter to mitigate CSRF attacks, but so far I haven't seen any statements that it's actually _required_? As such, would it make sense to allow SDK consumers to opt out of this request parameter? The default could (and probably should) still be for `state` to have a randomly generated value, of course.

Alternatively, the `AuthorizationManagementActivity` could perhaps not propagate an error if the response contains no `state` parameter at all, but I suppose that kind of defeats its purpose.

**Comment by Dumoulin-Lander** [comment]
I have similar issues to OP and agree that state should be able to be optional in the response as it is in spec.

**Comment by Moes81** [comment]
Having the same issue but with `endSession`. A state is required, but Forgerock doesn't return the state. Any idea how work around this?

**Comment by agologan** [comment]
The `state` parameter on `AuthorizationRequest` **is** optional.
It has an implicit default which is now suggested by the doc: 

https://github.com/openid/AppAuth-Android/blob/3c7417922238064f499f3b9b2274822d289b9da4/library/java/net/openid/appauth/AuthorizationRequest.java#L596-L606

You can set it to `null` if you don't want to/can't use the state field.
https://github.com/openid/AppAuth-Android/blob/3c7417922238064f499f3b9b2274822d289b9da4/library/javatests/net/openid/appauth/AuthorizationManagementActivityTest.java#L211-L215

@Moes81 I realize the same couldn't be said about `EndSessionRequest` so I tried to address this as part of e7d65bf03df29316aede4ab7cd13e9b30a8e76c0

Closing this issue but feel free to reply or open a new issue if you encounter problems when settings the `state` to `null`.
