### ISSUE TITLE
Callback Issue - onTokenRequestCompleted

### ISSUE THREAD

**Issue by PeaceNestPK** [openid/AppAuth-Android#616]
Hello everyone.

I'm not sure if this is the right place to discuss this issue, but I'm having an issue while integrating the library.

Everything worked well, and I can see the login page from the Azure as well.

The issue is: when I put the correct login credentials, the control doesn't return to the callback method. The callback method mentioned in the documentation is onTokenRequestCompleted 

![image](https://user-images.githubusercontent.com/73216969/96687323-29f86200-1399-11eb-8bfc-64e9ab445097.png)

Any advice, please.

Thank you.

**Comment by Fercafig** [comment]
.

**Comment by Fercafig** [comment]
.

**Comment by dIeGoLi** [comment]
But you execute `performTokenRequest`?

**Comment by amrfarid140** [comment]
@PeaceNestPK It might be better if you provided a code sample of how you are using AppAuth. It's hard to understand the issue is without seeing your logic.

**Comment by agologan** [comment]
Closing this as there has been no response to our request for more information from the OP in a reasonable amount of time. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍
