### ISSUE TITLE
https redirect does not redirect to android app

### ISSUE THREAD

**Issue by cpednekar** [openid/AppAuth-Android#618]
redirect url is https://mywebsite.com/about

android intent filter is 

`

            <intent-filter>

                <action android:name="android.intent.action.VIEW"/>

                <category android:name="android.intent.category.DEFAULT"/>

                <category android:name="android.intent.category.BROWSABLE"/>

                <data android:scheme="https"

                    android:host="mywebsite.com"

                    android:path="/about"/>

            </intent-filter>
`

after auth redirected url is https://mywebsite.com/about?oauth_code=xxx&oauth_verifier=yyy

but this is never redirected to app automatically. 
have to manually open the disambiguation dialog and select my app from there. then it works.

how to fix this?

**Comment by andrewdittmer** [comment]
Same here.

**Comment by panafana** [comment]
same for me as well

**Comment by amindadgar** [comment]
I'm having the same issue using a custom uri in manifest

**Comment by agologan** [comment]
When using an https redirect you need declare an [App Link](https://developer.android.com/training/app-links/index.html) in Android M+ if you want to bypass the default browser behaviour.

My recommendation though is to declare a separate client in your identity provider for the mobile integration and use a custom redirect scheme instead.

**Comment by andrewdittmer** [comment]
Thanks. I will aim to try this out later this week.

**Comment by andrewdittmer** [comment]
My issue was different to the issue described by OP. After adding a path to my intent filter and appending the path in my redirect url I was able to receive callback.

**Comment by amindadgar** [comment]
> When using an https redirect you need declare an [App Link](https://developer.android.com/training/app-links/index.html) in Android M+ if you want to bypass the default browser behaviour.
> 
> My recommendation though is to declare a separate client in your identity provider for the mobile integration and use a custom redirect scheme instead.

Thanks Agologan for your time 🌹 
After spending about two weeks on this it seems there's an issue in my authenticator server so I contacted my associates to resolve the issue.

**Comment by agologan** [comment]
Glad to hear you managed to sort it out.
