### ISSUE TITLE
NPE on isFullBrowser method

### ISSUE THREAD

**Issue by prasannarupan** [openid/AppAuth-Android#623]
Running into this NPE after building the app with Intune SDK and when launching the custom chrome tab to render our login page.

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.IntentFilter.hasAction(java.lang.String)' on a null object reference
        at net.openid.appauth.browser.BrowserSelector.isFullBrowser(BrowserSelector.java:183)
        at net.openid.appauth.browser.BrowserSelector.getAllBrowsers(BrowserSelector.java:99)
        at net.openid.appauth.browser.BrowserSelector.select(BrowserSelector.java:152)
        at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:96)

On debugging the issue, noticed that Intune SDK uses MAMResolverActivity which comes up as one of the intents. The filter property of ResolveInfo object is null and hence causing the NPE above. 

This does not happen when WebView is used but only happens on Custom Chrome Tabs.

**Comment by amrfarid140** [comment]
Which version of Android are you testing with?

**Comment by prasannarupan** [comment]
@amrfarid140 testing this on Android 10 OS. We're using the latest version of the AppAuth Android SDK.

**Comment by auzwang** [comment]
@prasannarupan one of our clients reported this issue when using our app wrapped by Microsoft Intune. It appears this happens when an Intune App Protection Data Protection Policy has _Send org data to other apps_ set to _None_. There's no longer a crash once it's set to _All apps_.

<img width="1054" alt="Screen Shot 2021-01-28 at 11 04 13 am" src="https://user-images.githubusercontent.com/1657832/106070924-7651fb80-6159-11eb-8921-0bf35dfdd419.png">

**Comment by prasannarupan** [comment]
Thank you @auzwang for this insight. I also noticed @amrfarid140 has pushed some changes related to this issue. 
Should I take a latest version of AppAuth to test this fix and also use the above mentioned settings in Intune portal?

**Comment by agologan** [comment]
While `GET_RESOLVED_FILTER` should ensure we have a filter - checking the property is safer.
Similar check can be seen in the implementation of `TrustedWebUtils`.

Change will be include in the next release and can be tested in the meanwhile via Jitpack.
