### ISSUE TITLE
Not capturing redirect in recently built project, local ad, adfs/openid

### ISSUE THREAD

**Issue by karezza** [openid/AppAuth-Android#635]
Testing using Samsung S20, w/ Android Studio 4.1.1, Flutter 1.25.0-8.3.pre * channel beta, Dart 2.12.0, flutter_appauth 0.9.2+6

A prompt appears to gather username/password (once in the morning, and once 12 hours later).  This morning I think it may have actually caught the redirect once, but since then, without being prompted it takes me to the redirecturl and it times out.  Not sure how to reset things so it prompts for my username/password again.

I can see in the web browser I'm being redirected, which times out.  This redirect needs to be captured.  I recreated the project just a few days ago (using a clean OS install, Android Studio install, etc), and after days of hours of debugging, maybe the documentation I've come across is just dated and the method has changed?  I must be close, if I could just get an assist.

Note, I'm using a local ADFS server setup via Windows Server.  The ADFS server setup is known to work as I can use it via a PowerShell script which uses ADFS to get a token that I pass to a webapi I have written which is able to perform authorization of the token (and now which I'm working to access via my mobile flutter app).  Via the flutter app I can see the URL it is trying to access is working and generating a 'code' attribute which is specified on the redirecturl (which is timing out because it's not being caught).

I have a CA setup in my domain and the needed certificate imported into my mobile, though I'm not 100% positive this is resulting in certificates validating.  I can put them in a web browser on my mobile and they show as valid but via flutter http.get it doesn't?  Developing via wifi (adb connect ...).

The URL currently registered as the redirecturl with ADFS is: https://net.server.app

[build.gradle]
```Yaml
android {
  ...
  defaultConfig {
    applicationId "net.server.app"
    ...
    minSdkVersion 30
    targetSdkVersion 30
    manifestPlaceholders = [
      'appAuthRedirectScheme': 'net.server.app'.
    ]
  }
  ...
}
```

[AndroidManifest.xml]
```Java
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="net.server.app"
    xmlns:tools="http://schemas.android.com/tools">
    ...
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.APP_BROWSER" />
            <data android:scheme="https" />
        </intent>
    </queries>
    ...
        </activity>
        <activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="net.server.app" />
            </intent-filter>
        </activity>
```

**Comment by agologan** [comment]
In your case, either declaring **appAuthRedirectScheme** or intent-filter with just **data android:scheme**, both translate to having the redirect uri declared as **net.server.app://**,  **NOT**: https://net.server.app
If you want to have the redirect uri be https you need to declare the intent-filter as:
```
    <intent-filter>
        ...
        <data android:scheme="https"
              android:host="net.server.app"/>
    </intent-filter>
```
and **NEED** to support [App Links](https://developer.android.com/training/app-links/index.html) for Android M(6.0) and above

**Comment by karezza** [comment]
Thank you.  Win Server ADFS requires the redirecturl to have a http/https in front of it, and now understand that the appAuthRedirectScheme won't work on its own.  I wonder if the 'queries' section above in the AndroidManifest, along with the appAuthRedirectScheme should have worked.  In any case, I've commented out the 'queries' section and though there is a value in appAuthRedirectScheme I don't expect it to be used.  Instead I am folcusing on the intent-filter which is now:

```
<activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="app.server.net" />
            </intent-filter>
        </activity>
```

Which matches what I have setup for the adfs client: https://app.server.net .

My first test this morning went through with an `PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: null, description: User cancelled flow], null)` which I looked up and discovered the scopes I was requesting were not granted in adfs, I have reduced the scropes being requested to 'openid profile email' which have been granted to the client.  I was hoping the second test would be successful but the same repeat as the last few days ending up on https://app.server.net/?code=... .  Is there a way to change something so I'll get prompted like I did first thing this morning?  Changing the clientId in the mobile and in adfs didn't cause it to prompt, nor does giving a new redirecturl and updating in mobile and adfs.  (changing the redirecturl is enough to cause my powershell client to prompt for credentials again).

**Comment by agologan** [comment]
Not sure I understand what the problem is right now, but I'm guessing you haven't set up [App Links](https://developer.android.com/training/app-links/index.html)

If you don't have App Links setup what happens is that the user will be prompted with a disambiguation dialog which will ask him to choose which app will open the link. 
The buttons on that dialog are **Just Once** or **Always**. 
If you accidentally clicked always and selected a browser your app will never be redirected again unless you go into Settings and reset the association.
Settings > Apps & Notifications > Advanced > Default Apps choose the browser and then **Clear Defaults**

An easy way to test the current link behavior is to run `adb shell am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d "https://app.server.net/"`

**Comment by karezza** [comment]
Ran the test command and was prompted with Just Once or Always and the choice between my app and a web browser.  I clicked my app and Just Once.

I am using "flutter_appauth".  Came here because it is using AppAuth behind the scene.  Definitely have made progress.

If things are looking good with the above the problem may be how flutter_appauth is calling back into RedirectUriReceiverActivity.  I can see in my AndroidManifest.xml the 'net.openid.appauth.RedirectUriReceiverActivity' is red with a message Class referenced in the manifest, ..., was not found in the project or in the libraries.  Will look in the flutter_appauth code to see if I can find an activity I should be using instead.  If there's something I need to include to get access to RedirectUtiReceiverActivity please let me know, though I have a lot experience with software development I only have a few months with flutter.

**Comment by karezza** [comment]
I'd prefer to not, just yet, setup a release fingerprint for use in the assetlinks.json file on a server with a valid ssl certificate.  I'd rather focus on development for now.  Sounds like that is needed to open a link without being prompted "Just Once or Always", but for now I'd be ok with that.  Can I avoid setting up the assetlinks.json & ssl server certificate for now and AppAuth will still work (just with me having to click on my app when prompted)?

**Comment by karezza** [comment]
I have since learned that Windows Server ADFS does in fact allow for a custom scheme such as net.server.app://, and am now pursuing that more simplified implemenation.  Closing as this question appears to be solved (verified through reading documentation, though not through implementation) with the answer being to setup App Links in order to get an https redirect_uri to work.
