### ISSUE TITLE
A weird interruption when waiting for too long in a separate auth application

### ISSUE THREAD

**Issue by Ohems** [openid/AppAuth-Android#638]
**ISSUE CASE 2**
[Case 1 here](https://github.com/openid/AppAuth-Android/issues/637)

## General info

In our React Native project, we use the the `react-native-app-auth` version 6.0.2. We begin the authorization process with something like the following:
```js
reactNativeAuthorize({
  issuer: BASE_API_URL,
  clientId: "our-client-id",
  redirectUrl: "ourapp://callback",
  scopes: ["offline", "openid", "create:payments", "read:accounts"]
});
```

This opens a login flow in browser. As a part of the login flow, the user will be redirected to the login page of their chosen bank account. Most banks nowadays require the use of a separate login app which means that in order to complete the login flow the user must leave our application, open the separate login app, enter their PIN code or use finger print recognition and navigate back to our application.

The flow works well on iPhone. It usually works well on Android, but we have noticed two cases where the login process repeatedly fails with a consistent outcome when following certain steps.

## Case 2

When the user navigates to the login app and waits for more than roughly 6 seconds in that app, this interferes with the login process in some weird way and results in a faulty login process state. The login process doesn't crash or end immediately, but the bank login page which is supposed to redirect back to our authentication service redirects to an empty 404 page instead. This means that the user is stuck with an empty browser window and closing that window results in a canceled login process.

We are still in the middle of debugging what exactly goes wrong here. The login process is very complex and we do not yet fully know where or how this faulty state materializes. We have scoured our systems and code for suitable timeouts that could cause this, but have so far found none. We will add more information to this issue report when available.

Just to stress the fact, this issue can't be replicated on an iPhone. Even after waiting for a long time in the authorization application the login process completes without issues.

**Comment by agologan** [comment]
Closing this as there has been no further information and I'm assuming you have reached a conclusion debugging the login process. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍
