### ISSUE TITLE
Authorization Code Flow With PKCE Requires client_secret For Some Severs

### ISSUE THREAD

**Issue by MartinStumpf** [openid/AppAuth-Android#639]
Not sure if this is a server or client issue BUT this can be fixed via this client code if desired otherwise this post is here for others running into the same issue.

Ive been getting the following error when doing a token request with PKCE in AuthorizationService.doInBackground when the response is finally read:

{"error":"invalid_request","error_description":"Client authentication failed."}

I compared the built token request with what Postman makes for OAuth2 and noticed that Postman has a "client_secret" parameter with no value set when using PKCE. Sure enough adding "client_secret" to TokenRequest.getRequestParameters() allowed the token request to pass on the server i was testing on:

    public Map<String, String> getRequestParameters() {
        Map<String, String> params = new HashMap<>();
        params.put(PARAM_GRANT_TYPE, grantType);
        putIfNotNull(params, PARAM_REDIRECT_URI, redirectUri);
        putIfNotNull(params, PARAM_CODE, authorizationCode);
        putIfNotNull(params, PARAM_REFRESH_TOKEN, refreshToken);
        putIfNotNull(params, PARAM_CODE_VERIFIER, codeVerifier);
        putIfNotNull(params, PARAM_SCOPE, scope);

        //
        // Seems some servers have a bug that causes token requests to fail if the client_secret param is missing.
        // Add the parameter with no value set to prevent an "invalid_request", "Client authentication failed" error
        //
        params.put("client_secret", "");

        for (Entry<String, String> param : additionalParameters.entrySet()) {
            params.put(param.getKey(), param.getValue());
        }

        return params;
    }

**Comment by agologan** [comment]
https://tools.ietf.org/html/rfc6749#section-2.3.1
> client_secret
>          REQUIRED.  The client secret.  The client MAY omit the
>          parameter if the client secret is an empty string.

I'm glad you solved your issue but please look into get the server code up to spec.
