### ISSUE TITLE
 No stored state - unable to handle response

### ISSUE THREAD

**Issue by noormohammadi100** [openid/AppAuth-Android#641]
Unable to resolve this!!! any body please help
  
I'm hitting endsession point to identity server by the below code.
it's working fine.

steps that i followed to get  **"No stored state - unable to handle response"**

1. open app login into identity server 
2. get authroization and token exchange.....
3. close the app
4. open the app again
5. so i'll land in tokenactivity page because already i'm authorized
6. now click on signout and i'm clearing the storage as well at my endpiont redirection happening
   but browser isnot closing and in logcat it displaying " No stored state - unable to handle response"
note: when click the signout after immediate of tokent exchange it goes throught the below lines and browser closed successfully.
 
CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
        CustomTabsIntent customTabsIntent = builder.build();
        customTabsIntent.intent.setFlags(Intent.FLAG_ACTIVITY_NO_HISTORY | Intent.FLAG_ACTIVITY_NEW_TASK
            | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        customTabsIntent.launchUrl(this, Uri.parse(url.toString()));

**Comment by agologan** [comment]
Sorry but I don't understand your steps clearly.
Let's back up:
After login you persist [AuthState](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthState.java)
When you reopen the app you don't need through the login flow again, (refresh the token if you need to) and use the authState.accessToken in your requests either directly or via **performActionWithFreshTokens**

To logout, you need to provide the **idToken** from authState to the **EndSessionRequest** and then startActivityForResult.
On return if successful, you may clear your saved AuthState

**Comment by noormohammadi100** [comment]
my appauth sdk didnt have updated commit of EndsessionRequest.
so I pull it.
yes it's working perfectly.
please close the issue

**Comment by agologan** [comment]
Glad to hear everything's working now 👍
