### ISSUE TITLE
Token validation issues while working with Windows Server 2019 ADFS?

### ISSUE THREAD

**Issue by karezza** [openid/AppAuth-Android#642]
WebApi Exception caught:

```
Bearer was not authenticated. Failure message: IDX10205: Issuer validation failed. Issuer: 'http://server.net/adfs/services/trust'. Did not match: validationParameters.ValidIssuer: 'null' or validationParameters.ValidIssuers: 'https://server.net/adfs'.
```

The mobile wants to have an Issuer of `http://server.net/adfs/services/trust`, but for some reason the WebApi is determining the Issuer to be `https://server.net/adfs`.  Both AppAuth and my C# .Net WebApi provide a place to specify an Issuer and both appear to promptly the value if I try to manually set it.

**Comment by karezza** [comment]
I can force this work with the following code:

```CSharp
        options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                {
                    ValidateIssuer = false
                };
```

I'd rather have things working right than to disable a validation.  Someone recognize this and know how to do so?

**Comment by agologan** [comment]
First of all, glad you figured your previous issue out. Was writing a reply while you updated the topic.
If you have C# auth related topics a good place to start is https://github.com/dotnet/aspnetcore/labels/area-security

In AppAuth the issuer is read from the discovery request (`https://{domain}/auth/realms/{realm}/.well-known/openid-configuration`) If you have a mismatch that's the best place to start.

**Comment by agologan** [comment]
Closing this as there has been no response to our request for more information from the OP in a reasonable amount of time. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍

**Comment by karezza** [comment]
I don't see an additional question for me but I was able to get this to work.  Too much time has passed though and I'm not sure what the specific fix was.  Thank you for your help.

**Comment by agologan** [comment]
Yeah sorry. Generic message.
I did expect a reply after my last message with further information/testing in order to provide more assistance if need be.
But I'm glad you got it resolved.
