### ISSUE TITLE
Release to jitpack or mavenCentral

### ISSUE THREAD

**Issue by Jawnnypoo** [openid/AppAuth-Android#645]
JCenter is shutting down: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

So, please consider publishing to Jitpack.io or Maven Central instead. The deadline is May 1st.

**Comment by chrisharris77** [comment]
Actually JCenter will no longer accept submissions after February 28, so if it is expected that there will be any new releases after then, it would need to be published elsewhere.

**Comment by agologan** [comment]
We are looking into getting builds in Central and we'll get back when we have an update.
As previously mentioned, we do recommend you grab a trunk build from JitPack https://jitpack.io/#openid/AppAuth-Android if you need one.

**Comment by agologan** [comment]
AppAuth 0.7.1 and newer now available via (MavenCentral)[https://search.maven.org/search?q=g:net.openid%20appauth]

You can still use artifacts from (JitPack)[https://jitpack.io/#openid/appauth-android] if you want to, just remember there is not guarantee those will be available long time, yet you can ask JitPack to rebuild whenever you need it.
