### ISSUE TITLE
EndSessionRequest and EndSessionResponse not available in 0.7.1

### ISSUE THREAD

**Issue by SunitaMK** [openid/AppAuth-Android#646]
Hello Team,

We are trying to implement "EndSession" flow. Trying to use the "EndSessionRequest" and "EndSessionResponse" apis but it is not available in version - 0.7.1. 
Please let us know how can we use these apis for end session?
Following are the details
********************************
Added this lib in build.gradle 

implementation "net.openid:appauth:$rootProject.ext.appAuthOpenIdVersion"
ext {

    // AD Integration
    appAuthOpenIdVersion = '0.7.1'
}

*********************************

Regards,
Sunita

**Comment by FlorianRenaud** [comment]
You should use Jitpack integration as long as there is no new release version planned, see [#578 ](https://github.com/openid/AppAuth-Android/issues/578#issuecomment-678357663).

**Comment by agologan** [comment]
We are looking at planning a new release, in the meantime please use a trunk build from JitPack https://jitpack.io/#openid/AppAuth-Android
