### ISSUE TITLE
onActivityResult not called

### ISSUE THREAD

**Issue by angelu25** [openid/AppAuth-Android#649]
`val authRequestBuilder = AuthorizationRequest.Builder(
                serviceConfig, 
                "myClientID",
                ResponseTypeValues.CODE,
                Uri.parse("https://myserver/handleredirects.htm"))`

        val authRequest = authRequestBuilder
                .setState("12345")
                .setScope("openid")
                .build()
        val RC_AUTH = 4
        val authService = AuthorizationService(this)
        val authIntent = authService.getAuthorizationRequestIntent(authRequest)
        startActivityForResult(authIntent, `RC_AUTH)`

On Android Manifest:
`<activity
      android:name="net.openid.appauth.RedirectUriReceiverActivity"
      tools:node="replace">
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="https"
          android:host="myserver"
          android:path="/handleredirects.htm"/>
      </intent-filter>
    </activity>`

But when I do the login in the opened web view and it redirects to something like https://myserver/handleredirects.htm?code=xxxx&state=12345" I'm not getting the onActivityResult method call from the original activity and the opened web activity is never closed, but redirected

Any idea?

**Comment by ghosalmartin** [comment]
you need to start the creation of the chrome tab with a `executor` look at the sample app. I had same issues here

https://github.com/openid/AppAuth-Android/issues/647

**Comment by angelu25** [comment]
Not able to make it work :(

**Comment by agologan** [comment]
Per your Manifest the redirect should be prefixed with `https://myserver/handleredirects.htm`. 
The actual redirect is different which means your server-side client is not matching your manifest.
Whatever you consider correct in this case please make sure you change either your identity provider configuration or you manifest to match.

Secondly, since you're using an **https** redirect the first you open this you'll see a disambiguation dialog asking you to open the link in your app or another browser. To get rid of this step you need to support (App Links)[https://developer.android.com/training/app-links] or use a custom scheme. Otherwise if the user opts to always open in browser they will never be able to complete the sign in flow.

**Comment by angelu25** [comment]
> Per your Manifest the redirect should be prefixed with `https://myserver/handleredirects.htm`.
> The actual redirect is different which means your server-side client is not matching your manifest.
> Whatever you consider correct in this case please make sure you change either your identity provider configuration or you manifest to match.
> 
> Secondly, since you're using an **https** redirect the first time you open it you'll see a disambiguation dialog asking you to choose between your app or another browser. To get rid of this step you need to support (App Links)[https://developer.android.com/training/app-links] or use a custom scheme. Otherwise if the user opts to always open in browser they will never be able to complete the sign in flow.

What do you mean different? It is like that in the Manifest and when creating the builder for the request.

**Comment by angelu25** [comment]
I finally make it work but now I do have one question:

As I needed to add the redirect to the Manifest, when it is detected, onActivityResult is executed but app is reopened (capturing the redirect link) and I loose the previous flow, being from the start point again.

How should I solve that issue?

**Comment by angelu25** [comment]
I finally make it work but now I do have one question:

As I needed to add the redirect to the Manifest, when it is detected, onActivityResult is executed but app is reopened (capturing the redirect link) and I loose the previous flow, being from the start point again.

Current code is:
Manifest
`    <activity
      android:name="net.openid.appauth.RedirectUriReceiverActivity"
      tools:node="replace">
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="https"
          android:host="myserver"
          android:path="/test/handleredirects.htm"/>
      </intent-filter>
    </activity>`

Code:
` val serviceConfig = AuthorizationServiceConfiguration(
                Uri.parse("https://myserver/authorizationserver/oauth/authorize"), 
                Uri.parse("https://myserver/authorizationserver/oauth/token"))
        val authState = AuthState(serviceConfig)

        val authRequestBuilder = AuthorizationRequest.Builder(
                serviceConfig,  
                "client",  
                ResponseTypeValues.CODE,  
                Uri.parse("https://mobtest.bestsecret.com/test/handleredirects.htm")) 

        val authRequest = authRequestBuilder
                .setState("12345")
                .setScope("openid")
                .build()
        val RC_AUTH = 4
        val authService = AuthorizationService(this)
        val authIntent = authService.getAuthorizationRequestIntent(authRequest)
        startActivityForResult(authIntent, RC_AUTH)`

**Comment by agologan** [comment]
Sounds like you're having an issue with state management for the activity and/or fragment during the lifecycle.
There are many ways to deal with it depending on your app's logic using a (viewModel)[https://developer.android.com/topic/libraries/architecture/viewmodel#lifecycle] being the most common one.

**Comment by agologan** [comment]
Since the OP has not provided any response in a reasonable amount of time, I'm assuming he figured out his issue so I'm closing this. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience others problems 👍
