### ISSUE TITLE
onActivityResult not called with Chrome Custom Tab

### ISSUE THREAD

**Issue by sQuark23** [openid/AppAuth-Android#652]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)

### Configuration
- Version: 0.8.0
- Integration: Native (Kotlin)
- Identity provider: Xero (https://developer.xero.com/)

### Issue Description
Hey, I'm trying to implement integration with Xero (but I think issue should occur) with any provider. Here's code

```
val authRequest = AuthorizationRequest.Builder(
                AuthorizationServiceConfiguration(
                        Uri.parse("https://login.xero.com/identity/connect/authorize"),
                        Uri.parse("https://identity.xero.com/connect/token")
                ),
                "{client_id_here}",
                ResponseTypeValues.CODE,
                Uri.parse("https://developer.android.com") // just for example, but I'm using https scheme too
        ).apply {
            setScope("openid email")
        }.build()

val authService = AuthorizationService(context)
val intent = authService.getAuthorizationRequestIntent(authRequest)
startActivityForResult(intent, 42)
```

AndroidManifest.xml
```
<activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="https"
                    android:host="developer.android.com"/>
            </intent-filter>
</activity>
```

It opens up in Chrome Custom Tab and when I log in into my account, it redirects to https://developer.android.com, but doesn't automatically closing. If I set up 
`BrowserMatcher(BrowserDenyList(VersionedBrowserMatcher.CHROME_CUSTOM_TAB)))`,
it opens up in Chrome Browser, redirects to https://developer.android.com and shows popup with option to open this link in my app, where I get code in onActivityResult. 

How to make it working with Custom Tabs?

**Comment by agologan** [comment]
Using an `https` redirect scheme requires you implement [App Links](https://developer.android.com/training/app-links).
The other option is to just use a custom URI scheme.

**Comment by sQuark23** [comment]
@agologan, even after adding App Links support it doesn't close automatically. Only if I open three-dots menu and click "Open in Chrome", there's a popup shown with option to select my app

**Comment by sQuark23** [comment]
@agologan, I've found cause of issue. Maybe it supposed to work so, but when I removed another intent-filter from app Manifest, intent-filter for RedirectUriReceiverActivity worked

**Comment by agologan** [comment]
Do you mind letting us known what your other intent filter was about so we keep that in mind if other users run into it?
