### ISSUE TITLE
How to use AppAuth with HTTP?

### ISSUE THREAD

**Issue by balkarov** [openid/AppAuth-Android#657]
### Configuration
- Version: 0.8.0
- Integration: (native(Java))
- Identity provider: (IdentityServer4)

### Description
I need use IdentityServer on HTTP port.
But new version (0.8.0) has condition for HTTP using

![Безымянный](https://user-images.githubusercontent.com/6030335/108337473-345f2700-71e6-11eb-9dd3-c51afcda8cc1.png)

```java
Uri issuerUri = Uri.parse(this.issuer);

if (!issuerUri.getScheme().equals("https")) {
   throw AuthorizationException.fromTemplate(GeneralErrors.ID_TOKEN_VALIDATION_ERROR,
         new IdTokenException("Issuer must be an https URL"));
}
```

Any workaround?

**Comment by chrismash2** [comment]
Sounds similar to these issues: https://github.com/openid/AppAuth-Android/issues/585 & https://github.com/openid/AppAuth-Android/issues/655

**Comment by carstenhag** [comment]
This is solved with the version 0.8.1, see https://github.com/openid/AppAuth-Android/pull/662/files

**Comment by carstenhag** [comment]
@balkarov Can you please close this ticket if the new version solves it for you?

**Comment by agologan** [comment]
Details available in [README.md](https://github.com/openid/AppAuth-Android#issues-with-id-token-validation) please be aware you also need a Connection builder that allows HTTP Connection like [ConnectionBuilderForTesting.java](https://github.com/openid/AppAuth-Android/blob/master/app/java/net/openid/appauthdemo/ConnectionBuilderForTesting.java)
