### ISSUE TITLE
Jitpack builds not working

### ISSUE THREAD

**Issue by dIeGoLi** [openid/AppAuth-Android#658]
Many use jitpack to get a build of a specific commit. It seems not to work anymore.

1. Follow this link to [jitpack](https://jitpack.io/#openid/AppAuth-Android)
2. Under Releases you can observe that the builds are ok. (Green document icon in log column)
3. Under Commits you can observe that commit builds fail. (Red document)
The log file states:

* What went wrong:
Execution failed for task ':library:signReleasePublication'.
> Cannot perform signing task ':library:signReleasePublication' because it has no configured signatory

So there seems to be some signing task which probably does not have the necessary configuration. I have been searching and scanning source code but do not get where i could disable the signing attempt. (for my fork) . Somebody with clear vision?
Thanks

**Comment by agologan** [comment]
Thank you for noticing. 
Have disabled signing if key is not defined.
JitPack builds for commits b445b68efe and later should work fine.
