### ISSUE TITLE
Demo app NPE on end session

### ISSUE THREAD

**Issue by tonylf** [openid/AppAuth-Android#659]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [x] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.8.0
- Integration: demo app
- Identity provider: AWS Cognito

### Issue Description
I have a NullPointerException when I click on "Sign out" in the TokenActivity.java with an endSessionEndpoint set but no registrationEndpointUri.
It looks like endSessionEndpoint and registrationEndpointUri are reversed in LoginActivity.java.216 when calling AuthorizationServiceConfiguration's constructor.

**Comment by keerthiprasad** [comment]
Hi tonyIf,

I faced the same issue with the Demo app. I added "end_session_endpoint" in auth_config.json and modified the AuthorizationServiceConfiguration's constructor by passing the exact values. 

After doing the above changes I was able to signout from the app.

**Comment by tonylf** [comment]
Hi keerthiprasad,

Thank you, I made the changes and it works indeed in my local fork.
I'm not sure who can apply the fix it in the github code though.

**Comment by agologan** [comment]
Fixed parameter issue in https://github.com/openid/AppAuth-Android/commit/a59f5d38c26d846f98788513b24385e18f0c9d59
And addressed the issue where an end-session endpoint is not present in discovery: https://github.com/openid/AppAuth-Android/commit/e599334e6e3bccdd6fe3052c83e01de989b24b4c

Thank you for noticing the issue.
Feel free to open a new issue if you find anything new.

**Comment by tonylf** [comment]
Thanks agologan!
