### ISSUE TITLE
How to separate authorization URL and the URL that will be opened in the browser?

### ISSUE THREAD

**Issue by eminuluyol** [openid/AppAuth-Android#660]
### Configuration
- Version: 0.8.0
- Integration: Kotlin
- Identity provider: Okta

### Description
I would like to separate authorization URL and the URL that will be opened in the browser. In the previous version, I was able to do method reflection and get the intent data from `prepareAuthorizationRequestIntent` method, but after started using the latest version I am no longer able to do that. Because the method now expects to get `AuthorizationManagementRequest` which is package private

This is what I want to get: 
https://my_login_facade.url.com/OktaLogin?fwdUrl= Uri build by sdk

I am using discovery for the endpoints.

**Comment by agologan** [comment]
There was a mistake with `AuthorizationManagementRequest` not being public which has been rectified in 1e5927332f6778c619c93bc1563e07e66901b9c5 and is available as part of release `0.9.0`

I don't fully understand what your trying to achieve and reflection in this case sounds sketchy so if you'd want to explain better I'd appreciate it - maybe it  warrants a different library change.

Closing this for now. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you run into further problems 👍
