### ISSUE TITLE
Is only Chrome custom tabs support redirect using App links?

### ISSUE THREAD

**Issue by agent10** [openid/AppAuth-Android#663]
Hi.
I'm trying to implement my own oauth with external server using redirect through properly registered https App links as described at google docs.
Everything works fine if Chrome browser is using for custom tabs. But there is no any redirects with other browsers e.g. Firefox
Is it known behavior or I have some problems in my implementation.

**Comment by agologan** [comment]
Not all browsers deal with this consistently.
Firefox has an _"Open Links in apps"_ in Settings, otherwise there's an Open In App button.

**Comment by agent10** [comment]
Thanks a lot!
