### ISSUE TITLE
Are there any ways to check that AppLinks verified?

### ISSUE THREAD

**Issue by agent10** [openid/AppAuth-Android#667]
We've recently faced the issue that 5% of our users don't have verified app links and redirecting doesn't work. 
There are a lot of reasons for that: no(or bad) internet / server not available during installing.
As I know verifying will happen again only if user update(or reinstall) the app. I'd like to provide WebView as fallback and I wonder if there are ways to check that my app links verified or not? I've found some method isVerified() inside IntentFilter.java but it's hidden and unavailable to use properly.

**Comment by agologan** [comment]
Afaik there aren't any ways to check if the link has been verified.
Links will be reverified on app upgrade or reinstall and that's about it.
You can try asking Google on their issue tracker for further support but they may just come back with: please ensure your service is reliable.

**Comment by agologan** [comment]
Closing this unfortunately due to lack of activity, will ping you back if get uncover new information 👍
