### ISSUE TITLE
Link to Google Codelab in Readme leads to 404 page

### ISSUE THREAD

**Issue by madfree** [openid/AppAuth-Android#668]
The first link under codelabs "A codelab featuring AppAuth was provided for Google I/O 2016: Achieving Single Sign-on with AppAuth" leads to a 404 page. Could be deleted or link to the (deprecated) code on github directly?

**Comment by agologan** [comment]
There is still a mirror with the old codelabs.
Updated the link to that.

Thank you for noticing.
