### ISSUE TITLE
Authorization request web-view does not get removed from back stack and direct user back to application based on redirect URI

### ISSUE THREAD

**Issue by tt-aali** [openid/AppAuth-Android#671]
### Configuration
- Version: 0.8.1
- Integration: Native Android(Java & Kotlin)
- Identity provider: (OpenID)

### Description

Hi! I am having these issues with 

**Expected Behavior**

(1) User enters email
(2) User is taken to authentication web-view - (performAuthorizationRequest)
(3) User enters password and is redirected to application via redirectUri

**Actual Behavior**

(1) User enters email
(2) User is taken to authentication web-view - (performAuthorizationRequest)
(3) User is stuck on authentication web-view and is NOT redirected back to application

On first time authorization request, the web-view displays the flow completed page but I am not redirected back to my app unless I exit the web view (which doesn't count because I am just finishing the activity)

When attempting to request authorization again, I am correctly redirected back to my activity but with an authorization exception:

![Screen Shot 2021-03-11 at 8 09 49 PM](https://user-images.githubusercontent.com/40069895/110890908-c1594580-82a5-11eb-953d-3db1c1ef736f.png)

Could I get a sanity check on the setup here? 

![Screen Shot 2021-03-11 at 8 08 29 PM](https://user-images.githubusercontent.com/40069895/110890909-c28a7280-82a5-11eb-9acb-8a39537de7cb.png)
![Screen Shot 2021-03-11 at 8 08 17 PM](https://user-images.githubusercontent.com/40069895/110890910-c28a7280-82a5-11eb-9baa-aaf33842136f.png)

What are some problems I may be overlooking? Could it be a provider issue where I am not being redirected accordingly after login?

**Comment by agologan** [comment]
Looks like there is an issue with your provider not returning state information correctly.
Are you using a cloud or off the shelf solution?

**Comment by agologan** [comment]
_Closing this as there has been no response to our request for more information from the OP in a reasonable amount of time.  Assuming issue has been resolved. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍_
