### ISSUE TITLE
Make library activities extend androidx.appcompat.app.AppCompatActivity

### ISSUE THREAD

**Issue by alwa** [openid/AppAuth-Android#676]
#### Motivation
Since this project is supposed to support AndroidX (https://github.com/openid/AppAuth-Android/issues/417) I want to suggest changing activities that are declared in the app manifest to extend `androidx.appcompat.app.AppCompatActivity` instead of `android.app.Activity`.

Some app integrations expect all activities in the application to be descendants of `AppCompatActivity` (because they are using an action bar for example) and therefore have to invent workarounds to support the plain Activities from this library.
See more motivations here why `AppCompatActivity` is more flexible: https://stackoverflow.com/questions/31297246/activity-appcompatactivity-fragmentactivity-and-actionbaractivity-when-to-us

#### Description
Convert at least:
- net.openid.appauth.AuthorizationManagementActivity

Maybe also:
- net.openid.appauth.RedirectUriReceiverActivity

#### Alternatives or Workarounds
No workarounds.

**Comment by alwa** [comment]
I'm starting to see why this hasn't been done already...
Making activities extend AppCompatActivity requires a theme that needs to be explicitly declared.
A reference to resources means adding android resources to the test options. Android resources in test options means processing the Android manifest. Processing the Android manifest means `appAuthRedirectScheme` has to be declared. It seems that it is not enough if it is declared only for a certain build type as is the case right now.

**Comment by alwa** [comment]
One first step to start to clear up this mess I think is to rewrite unit tests to not rely on `Robolectric.buildActivity()` and instead on `ActivityScenario`: https://developer.android.com/reference/androidx/test/core/app/ActivityScenario

**Comment by agologan** [comment]
Done. Thank you for you suggestions.
