### ISSUE TITLE
App not asking to choose Account and Prompt is not passing through AuthorizationRequest on Google Authentication 

### ISSUE THREAD

**Issue by Saitarak436** [openid/AppAuth-Android#681]
### Checklist:

- [ ] I am using the latest release
- [ ] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [ ] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [ ] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [ ] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.X.Y
- Integration: (native(Java/Kotlin), Xamarin, ReactNative, etc)
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

**Comment by agologan** [comment]
The information currently provided is not enough to take any action.
Here's an example config I recently used to integrated google auth which may be of help:
```json
{
  "client_id": "XXXX.apps.googleusercontent.com",
  "redirect_uri": "com.googleusercontent.apps.XXXX:/oauth2redirect",
  "end_session_uri":"https://accounts.google.com/o/oauth2/v2/",
  "authorization_scope": "openid email profile",
  "discovery_uri": "https://accounts.google.com/.well-known/openid-configuration",
  "authorization_endpoint_uri": "",
  "token_endpoint_uri": "",
  "registration_endpoint_uri": "",
  "user_info_endpoint_uri": "",
  "https_required": true
}
```

Closing the issue for now. 

_Please open a new issue providing a comprehensive description of your scenario if you still need help._

**Comment by Saitarak436** [comment]
@agologan 

As you said it directly works with **https://accounts.google.com/**., But i am using along with B2C using tenant id & policy.
using as below :

 AuthorizationServiceConfiguration serviceConfig = new AuthorizationServiceConfiguration(
                                                Uri.parse(Constants.Authorization_endpoint), // authorization endpoint
                                                Uri.parse(Constants.Token_endpoint) // token endpoint
                                        );

                                        String clientId = Constants.ClientID;

                                        Uri redirectUri = Uri.parse(Constants.REDIRECT_URL_Google);


                                        AuthorizationRequest.Builder builder = new 
                                        AuthorizationRequest.Builder(serviceConfig,clientId,"code",redirectUri);
                                        builder.setScopes(new String[]{Constants.Scope});
                                        builder.setPromptValues(new String[]{Constants.Prompt});
                                        AuthorizationRequest authorizationRequest = builder.build();
                                        AuthorizationRequest authRequest = authorizationRequest;
                                        AuthorizationService authService = new AuthorizationService(Login.this);
                                        Intent authIntent = authService.getAuthorizationRequestIntent(authRequest);
                                        startActivityForResult(authIntent,RC_AUTH);


From B2C to Google, Prompt is not appending for B2C Link.

**Comment by agologan** [comment]
Thank you for creating a new issue (#683) with a bit more information. Let's keep using that.
