### ISSUE TITLE
Box

### ISSUE THREAD

**Issue by vonsamnang01041994** [openid/AppAuth-Android#684]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/Box
AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [x] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.X.Y
- Integration: (native(Java/Kotlin), Xamarin, ReactNative, etc)
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

**Comment by agologan** [comment]
Judging by the edits I assume you were confused.
Closing and locking the issue.
