### ISSUE TITLE
accept-language header

### ISSUE THREAD

**Issue by drdla49** [openid/AppAuth-Android#686]
Chrome custom tab automatically sets accept-language based on device language to every request that I create by this library. Is there any way to set accept-language header different from the device language? 

We have many languages in the app and users can change language independently on device language. So I need to send a different accept-language header to our identity server.

For other requests in the app and for webview ve used interceptor to set the right accept-language. But it not work for custom tab.

Thanks

**Comment by agologan** [comment]
You can do this using adding `ui_locales` on the `AuthorizationRequest`.
This takes a list of space-separated language tag values, ordered by preference.

Since the parameter is not currently defined in the lib you can add it via `AuthorizationRequest.Builder#setAdditionalParameters` something along the lines of:
```kotlin
builder.setAdditionalParameters(mapOf("ui_locales" to "fr-CA fr en"))
```

This assumes your identity provider supports this feature.
If this doesn't work please reach out to their support service to figure this out.

**Comment by drdla49** [comment]
Thanks for the reply, but this solution not work. Our identity server returns the page in language according to the accept-language header. 
I add this code:

        val params: MutableMap<String, String> = HashMap()
        params[NONCE_KEY] = NONCE
        params[ACR_VALUES_KEY] = acrValues
        params[COUNTRY_CODE_KEY] = CountryManager.getCountryCode()
        params["ui_locales"] = "cs-CZ"
        return AuthorizationRequest.Builder(
            serviceConfiguration,
            clientId,
            ResponseTypeValues.CODE,
            getRedirectUri()
        ).setScope(SCOPE)
            .setResponseType(RESPONSE_TYPE)
            .setPrompt(AuthorizationRequest.Prompt.LOGIN)
            .setAdditionalParameters(params)
            .build()

But still have this accept-language header if my phone is in english:
`accept-language	en-GB,en-US;q=0.9,en;q=0.8`

I use appAuth version 0.8.0.

Thanks for reply.

**Comment by agologan** [comment]
As mentioned before, please reach out to your identity provider to support the parameter per [2.1.1.1.  Request Parameters](https://openid.net/specs/openid-connect-basic-1_0.html).

We can only pass an URL to the browser, it's up for the browser to actually create the request that it sends to the identity server. Thus, if we need to provide extra instructions to the identity server we do it via the URL parameters hence `ui_locales` has been introduced for this exact reason.

_Closing this issue as there is nothing more to do from a library perspective._
