### ISSUE TITLE
Allow users to edit their profile details under application

### ISSUE THREAD

**Issue by punithbm** [openid/AppAuth-Android#689]
We wanted to allow users to edit their profile details by loading profile URL inside the application using the same keycloak session which was used to log in. Is there any way to do this? 

The expectation is to load profile edit screen as shown below

![51ad8ebe15a7ca13388ff21df0e64095](https://user-images.githubusercontent.com/13044958/114865123-746e0f00-9e0f-11eb-967f-79d05fc290c7.png)

inside the application. Please help us with this.

### Configuration
- Version: 0.8.1 
- Integration: Java
- Identity provider: KeyCloack

**Comment by agologan** [comment]
While this could **theoretically** be possible, you should **NOT** try to do this.

The right solution is to write a profile API to update the data or try using the `account_api` in Keycloak.
Here's a good write-up on using the account_api as I couldn't find proper docs on it: https://www.marcus-povey.co.uk/2020/10/12/using-the-keycloak-accounts-management-api/

**Closing** this issue as it does not refer to an AppAuth lib feature.
_Please direct Keycloak questions to the Keycloak team at https://github.com/keycloak/keycloak via one of their acceptable communication channels._
