### ISSUE TITLE
Is there any way to close the chrome tab once end session is completed in Android?

### ISSUE THREAD

**Issue by Sabaripriyan** [openid/AppAuth-Android#690]
### Configuration
- Version: 0.X.Y
- Integration: (native(Java/Kotlin), Xamarin, ReactNative, etc)
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

**Comment by agologan** [comment]
Please fill in the template as it asks you for minimal amount of information to contextualize your question.

As for the chrome tab closing, assuming your **_identity server supports end session_** flow the tab will close by itself the same way it closes during login.

**Comment by agologan** [comment]
_Closing this as there has been no response from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you require further assistance 👍_
