### ISSUE TITLE
Adding additionalParams to authRequest leads to wrong configuration URIs 

### ISSUE THREAD

**Issue by dnoelb** [openid/AppAuth-Android#691]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.8.1
- Integration: native - kotlin
- Identity provider: own node-openid-connect-provider (https://github.com/panva/node-oidc-provider)

### Issue Description

Whenever there are AdditionalParameters added to the AuthorizationRequest, The Uri opened in the Browser, while performing the authorization request, is the redirect Url, which is linked to my Activity. If I remove the .setAdditionalParameters call on the builder, everything works as expected and the uri opened in the browser is the correct login screen/auth endpoint of my identity provider.

Code that produces the bug:
```
                val authRequestBuilder: AuthorizationRequest.Builder = AuthorizationRequest.Builder(
                    serviceConfig,
                    CLIENT_ID,
                    ResponseTypeValues.CODE,
                    Uri.parse(APP_REDIRECT_URI)
                )

                val additionalParams : HashMap<String, String> = HashMap()
                additionalParams["audience"] = "myAudience"
                val authRequest: AuthorizationRequest =
                    authRequestBuilder.setScope("openid profile offline_access")
                        .setAdditionalParameters(additionalParams)
                        .build()
```

Code that results in the correct login page:
```
                val authRequestBuilder: AuthorizationRequest.Builder = AuthorizationRequest.Builder(
                    serviceConfig,
                    CLIENT_ID,
                    ResponseTypeValues.CODE,
                    Uri.parse(APP_REDIRECT_URI)
                )

                val authRequest: AuthorizationRequest =
                    authRequestBuilder.setScope("openid profile offline_access")
                        .build()
```

The problem is, that my IdP expects the audience parameter in order to create an valid access token in jwt format.

### Expected Behavior:

The additional Parameter is just added to the existing Authorization Request without overwriting any parts of the configuration

Thank you very much for any help :)

**Comment by agologan** [comment]
I'm sorry but I don't think I understand the issue or I'm missing some context.

Change the following block [LoginActivity.java#L473-L4780](https://github.com/openid/AppAuth-Android/blob/master/app/java/net/openid/appauthdemo/LoginActivity.java#L473-L478) in the demo app with:
```java
        HashMap<String, String> additionalParams = new HashMap<String, String>();
        additionalParams.put("audience", "myAudience");
        AuthorizationRequest.Builder authRequestBuilder = new AuthorizationRequest.Builder(
                mAuthStateManager.getCurrent().getAuthorizationServiceConfiguration(),
                mClientId.get(),
                ResponseTypeValues.CODE,
                mConfiguration.getRedirectUri())
                .setScope(mConfiguration.getScope())
                .setAdditionalParameters(additionalParams);
```
And an auth request link is opened in the browser with `&audience=myAudience` appended as expected.

**Comment by dnoelb** [comment]
I'm sorry, I submitted this issue a bit fast. 
I resolved my problem, as I figured out the IdP only accepts valid URI's as audience or resource parameters. And I tested it with a wildcard, only.

So everything works as expected. 

Thanks a lot for your reply and your work on library in general. Cheers David.
