### ISSUE TITLE
Calling AuthorizationManagementActivity.createStartIntent causes the app to crash 

### ISSUE THREAD

**Issue by Nimrodda** [openid/AppAuth-Android#694]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [ ] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.8.1
- Integration: native-Kotlin
- Identity provider: our own

### Issue Description

Calling `AuthorizationManagementActivity.createStartIntent` causes the app to crash because `AuthorizationManagementRequest` is package private.

Can I make a PR to change it to public?

**Comment by agologan** [comment]
You shouldn't be calling `createStartIntent` directly, instead you should be using `AuthorizationService#performAuthorizationRequest`

**Comment by Nimrodda** [comment]
I think it's better to keep the flexibility of the library.

We have a specific use case for this where user doesn't have a browser installed (rare, but happens!), we fallback to our own Activity with WebView. The implementation plugs into the library's authentication flow by launching `AuthorizationManagementActivity` with an `authIntent` that starts our WebView Activity like so:

```
startActivityForResult(
     Intent(activity, AuthorizationManagementActivity::class.java).apply {
                            putExtra(
                                "authIntent",
                                WebViewLoginActivity.createStartIntent(
                                    activity, authRequest
                                )
                            )
                            putExtra("authRequest", authRequest.jsonSerializeString())
                        }), RC_AUTH)
```

Once the user is logged in, we intercept the redirect uri and start `RedirectUriReceiverActivity` with it.
It works flawlessly, but as mentioned in my initial post, we have to create `AuthorizationManagementActivity` manually since `AuthorizationManagementRequest` is package private which causes a public API to crash (`AuthorizationManagementActivity.createStartIntent`).

Will you approve a PR that fixes it?

**Comment by agologan** [comment]
While I understand your intent this library is explicitly designed to not use an embedded WebView (as mentioned in the first paragraph of our Readme).
Adding a change that may encourage that usage is not something that goes along with that philosophy even if it is for an exceptional use-case.

Alternatively, what I would encourage you here is to ask your users to install a browser they trust. 
https://tools.ietf.org/html/rfc8252#section-8.12 expands more on the topic.

**Comment by Nimrodda** [comment]
>While I understand your intent this library is explicitly designed to not use an embedded WebView (as mentioned in the first paragraph of our Readme).
Adding a change that may encourage that usage is not something that goes along with that philosophy even if it is for an exceptional use-case.

I understand your point and see how this can be a security issue, but I think this applies more when using a 3rd party provider, such as Google and Facebook, which isn't the case here. In our case, we have our **own provider**, which is used only in **our apps**.

>Alternatively, what I would encourage you here is to ask your users to install a browser they trust.
https://tools.ietf.org/html/rfc8252#section-8.12 expands more on the topic.

We have this solution currently in place and the UX is so bad that we started getting negative reviews about it. Some users don't even bother to continue with the sign in. We have apps with millions of users. Having users not being able to log in means a direct hit to our revenue.

IMO, the library shouldn't enforce anything, but leave it to the developers. Everyone has a different use case and should be able to make the decision what's best for their app.

**Comment by agologan** [comment]
While I do not agree with your statements, having reevaluated that API it was a mistake that it's currently unusable although being public.
