### ISSUE TITLE
Error after updating Android Gradle to 4.2.0

### ISSUE THREAD

**Issue by tallnato** [openid/AppAuth-Android#696]
### Configuration
- Version: 0.8.1
- Integration: native Kotlin

### Issue Description
After updating Android Studio to 4.2.0 and Android Gradle to 4.2.0 I started getting the error, just when running the unit tests
> Manifest merger failed : Attribute data@scheme at manifestMerger8985243458617216070.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.

Just some context, I have all the AppAuth related stuff in a separate model, called `authorization`.
In that module it's defined the `manifestPlaceholders`
```
android {
       default {
              manifestPlaceholders = [
                     'appAuthRedirectScheme': 'xxx',
              ]
       }
}

```
and also in the main app module I have the `manifestPlaceholders`.

when I run `./gradlew :authorization:testDebugUnitTest`
I get that error 
`Manifest merger failed : Attribute data@scheme at manifestMerger8985243458617216070.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.`

If I downgrade the Gradle to 4.1.3 everything runs fine.

 Also, running the app in a device, no problems, just when running the tests.

Any ideia what's happening ?
Thanks

**Comment by agologan** [comment]
Don't know enough about test targets to say what is the right way but depending on how you configure unit tests there are a couple of ways to tackle this:
- use a separate **testBuildType** as seen in our own config https://github.com/openid/AppAuth-Android/blob/master/library/build.gradle
- create an `AndroidManifest.xml` in `src/androidTest/` for the `RedirectUriReceiverActivity` activity node and don't forget to add `tools:node="replace"`

**Comment by wakkow** [comment]
I'm running into the same issue. I think that 4.2.0 doesn't work correctly with the `manifestPlaceholders` when it comes to unit tests. Even if you set it it, it still complains about the missing placeholder.

I was able to get it working for me with a variation of the `AndroidManifest.xml` suggestion - putting it in`my-module/src/test` and ensuring it has no `<data android:scheme>` or setting it to a test value.

**Comment by tallnato** [comment]
thank you both for the suggestions 👍 

@wakkow I was trying to do your suggestion with the `AndroidManifest`, but was able to do it.
Would it be possible to provide me a manifest that you used? 🙏 
Thanks
