### ISSUE TITLE
Logout AWS Cognito - client_id is required for EndSessionRequest

### ISSUE THREAD

**Issue by sundeepkmallick** [openid/AppAuth-Android#697]
### Configuration
- Version: 0.8.1
- Integration: Java
- Identity provider: AWS Cognito

### Description
As per the documentation [AWS Cognito Logout](https://docs.aws.amazon.com/en_en/cognito/latest/developerguide/logout-endpoint.html), we need to pass **client_id** as query parameter.  However, EndSessionRequest class does not have any option to receive  **client_id**. It only accepts **id_token_hint** as query parameter. How could I proceed here? Any hint/help is appreciated. Can I contribute/improve here if not already done?

It throws error: "Required String parameter 'client_id' is not present"

**Comment by agologan** [comment]
AWS Cognito doesn't implement [OpenID Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html)
Recommend you integrate their [Amplify framework](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android) instead.

**Comment by sundeepkmallick** [comment]
Hi @agologan , Why EndSessionRequest class does not allow to add more query parameters and restricted to only two idToken & redirectUtri? Is there any problem if we could add more query parameters to the request?

**Comment by p-gag** [comment]
For me, calling the Cognito endpoint directly saved me from going back to the bloated Amplify. Doing auth with react-native-app-auth is way cleaner. 

Here is an example in Typescript:
```Typescript
export const cognitoLogoutOut = async (
  logoutCallback: string,
  clientId: string,
  domain: string,
) => {
  // really "/logout", not "oauth2/logout"
  const endSessionEndpoint = `https://${domain}/logout`;
  // logoutCallback, have to be identical to the one in App client settings in Cognito console.
  const cb = encodeURIComponent(logoutCallback);
  const url = `${endSessionEndpoint}?client_id=${clientId}&logout_uri=${cb}`;
  await InAppBrowser.openAuth(url, logoutCallback, {
    ephemeralWebSession: false,
    showTitle: false,
    enableUrlBarHiding: false,
    enableDefaultShare: false,
  });
};
```

**Comment by agologan** [comment]
Thank you for sharing this with the members of the community 👍
