### ISSUE TITLE
Id Token validation fails, for genuine token sent by the provider, since issuer differs from expectedIssuer

### ISSUE THREAD

**Issue by yaexiste2** [openid/AppAuth-Android#699]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.X.Y
- Integration: (Native Java)
- Identity provider: (https://auth-testing.iduruguay.gub.uy/oidc/v1/.well-known/openid-configuration)

### Issue Description
Id Token validation fails inside AuthorizationService.java, for token given sent by the provider, thus not returning it in the callback. Via debugging it is shown that the idtoken is ok until idToken.validate() is called. I think there is no way the token is not valid, since it´s the token provided, which no one has tampered with.
The issue is that the` issuer = "https://auth-testing.iduruguay.gub.uy/oidc/v1"`, which is not the same as `expectedIssuer = "https://auth-testing.iduruguay.gub.uy"`
Useful data: I initialized the configuration using the discovery method on the url mentioned as the provider. There it states the issuer as it is stated by the SDK. Is my provider wrong?
I've come to the conclusion that this is probably not actually a bug, (Unless maybe validate issuers with that base uri?)  but I don't know how to change the label. Also, what should I do? Try to convince the provider?

**Comment by agologan** [comment]
Per https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation the issuer identifier MUST exactly match.
Looking at the discovery doc the issuer is incorrect and should be: `https://auth-testing.iduruguay.gub.uy/oidc/v1`

Meanwhile checking [IdToken.java#L128](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/IdToken.java#L128) validation is only done if there is a discoveryDoc in the configuration, so you could either:
- create a AuthorizationServiceConfiguration without a discoveryDoc via `AuthorizationServiceConfiguration(Uri authorizationEndpoint, Uri tokenEndpoint, Uri registrationEndpoint, Uri endSessionEndpoint)`
- create a AuthorizationServiceConfiguration by passing in a discoveryDoc that you created from corrected json copy.

Once the issue get resolved you can revert back to using `AuthorizationServiceConfiguration.fetchFromUrl(...)`

**Comment by yaexiste2** [comment]
Yeah, I was thinking about doing something like that. Thanks!
