### ISSUE TITLE
Allow developers to pass additional query parameter via EndSessionRequest 

### ISSUE THREAD

**Issue by sundeepkmallick** [openid/AppAuth-Android#700]
### Feature Request
I would be thankful if you accept my feature request or allow me to work on it if it is already planned & blocked because of some reasons.

#### Motivation
If we could able to pass additional query parameters via **EndSessionRequest**, it will be helpful for developers to use AppAuth SDK for more Open ID platforms.

#### Description
1. Currently we could only pass limited query parameters via the constructor of EndSessionRequest: **id_token_hint**, **post_logout_redirect_uri** & **state**.
2. We could modify either the constructor or builder to set/pass additional query parameters to the URL. 

#### Alternatives or Workarounds
1. Switch to another library which is time consuming and waste of time.

**Comment by sundeepkmallick** [comment]
Hi @agologan , hope you are doing good. I noticed there were some progress on this improvement request. Kindly notify me once it is available to use.

**Comment by agologan** [comment]
`additionalParameters` have been added to EndSessionRequest in e7d65bf03df29316aede4ab7cd13e9b30a8e76c0 
Changes are now available in version `0.9.0`
Please be aware the interface for EndSessionRequest has **changed** to correctly reflect optional fields.

Feel free to open a new issue if you encounter any problems.

**Comment by sundeepkmallick** [comment]
Hi @agologan , thank you very much.
