### ISSUE TITLE
App is stuck on browser post logout

### ISSUE THREAD

**Issue by sundeepkmallick** [openid/AppAuth-Android#701]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [x] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.8.1
- Integration: (native(Java))
- Identity provider: (Auth0)

### Issue Description
I used the demo app AppAuth-Android. Configured all necessary URLs. App Links working as well. Login works perfectly and redirecting user back to app. I am able to refresh the token and also receiving the user info. However, when I press logout button it is logging out the session and then redirecting to the end_session_redirect_uri (same URL used for post login redirection & with app links). After this, app is stuck on the browser. Can anyone help me here or give any hint how to get rid of this issue (thank you in advance) ? Seems like a bug on the SDK where redirection back to app is not addressed.

**Comment by agologan** [comment]
As explained in #679 you may be running into the exact same issue.
Working with the identity provider to provide an extra step for the user to interact with should resolve the issue.

**Comment by agologan** [comment]
_Closing this as there has been no response from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you require further assistance 👍_
