### ISSUE TITLE
Dependency does not work in kotlin project.

### ISSUE THREAD

**Issue by Ronakgadhia** [openid/AppAuth-Android#702]
Below Dependency does not work in kotlin project.  
implementation 'net.openid:appauth:0.8.1'

Error : 
Unresolved reference: AuthorizationServiceConfiguration

Please let me know your views.

**Comment by agologan** [comment]
Pretty sure it works fine. 
Please provide a sample project that demos this issue.

**Comment by Ronakgadhia** [comment]
I have imported successfully dependency. But I can not convert below Java function to kotlin. Could you please help?

AuthorizationRequest.Builder authRequestBuilder =
            new AuthorizationRequest.Builder(
                serviceConfig, 
                mConfiguration.getClientId(), 
                ResponseTypeValues.CODE, 
                mConfiguration.getRedirectUri());

**Comment by agologan** [comment]
```kotlin
val authRequestBuilder = AuthorizationRequest.Builder(
    serviceConfig,
    mConfiguration.getClientId(),
    ResponseTypeValues.CODE,
    mConfiguration.getRedirectUri()
)
```

**Comment by Ronakgadhia** [comment]
I have already tried but it gives an error.

https://ibb.co/2Y9BDtq

**Comment by agologan** [comment]
From the picture `com.microsoft.identity.common.internal...` you are inferring the incorrect class.
Check your imports. You should have `import net.openid.appauth.AuthorizationRequest`

**Comment by Ronakgadhia** [comment]
Ok. Thanks. It works.
val authRequestBuilder:net.openid.appauth.AuthorizationRequest.Builder = net.openid.appauth.AuthorizationRequest.Builder(
                serviceConfig,
                "",
                ResponseTypeValues.ID_TOKEN,
                Uri.parse("")
        )

**Comment by agologan** [comment]
Glad to be of help.
