### ISSUE TITLE
Unable to complete authorization as there is no interactive call in progress. This can be due to closing the app while the authorization in process.

### ISSUE THREAD

**Issue by ChetnaNakum** [openid/AppAuth-Android#704]
It gives below error when press on signin button.

**Unable to complete authorization as there is no interactive call in progress. This can be due to closing the app while the authorization in process.**

**Comment by agologan** [comment]
I'm sorry but can you be more specific/provide a bit of context.

**Comment by Ronakgadhia** [comment]
I opens -> Microsoft login page -> Enter email id & password -> press sigin button -> It gives an above error.
 
 
 val serviceConfig= AuthorizationServiceConfiguration(
                Uri.parse("https://login.microsoftonline.com/common/oauth2/v2.0/authorize"),
                Uri.parse("https://login.microsoftonline.com/common/oauth2/v2.0/token")
        )
        val authRequestBuilder:net.openid.appauth.AuthorizationRequest.Builder = net.openid.appauth.AuthorizationRequest.Builder(
                serviceConfig,
                "xyz_client_id",
                ResponseTypeValues.ID_TOKEN,
                Uri.parse("redirect_uri")
        )
        authRequestBuilder.setScopes("openid", "email", "profile")

        val authRequest: net.openid.appauth.AuthorizationRequest = authRequestBuilder.build()

        val authService = AuthorizationService(this@LoginActivity)
        val authIntent: Intent = authService.getAuthorizationRequestIntent(authRequest)

        startActivityForResult(authIntent, 1234)
        
        ======================================================================
OnActivity Result


if (resultCode == RESULT_CANCELED) {
            displayAuthCancelled();
        } else {
            /*Intent intent = new Intent(this, TokenActivity.class);
            intent.putExtras(data.getExtras());
            startActivity(intent);*/

            AuthorizationResponse resp = AuthorizationResponse.fromIntent(data);
            AuthorizationException ex = AuthorizationException.fromIntent(data);
            AuthorizationService authService = new AuthorizationService(this);

            switch (requestCode) {
                case 1234:
                    authService.performTokenRequest(
                        resp.createTokenExchangeRequest(),
                        new AuthorizationService.TokenResponseCallback() {
                            @Override public void onTokenRequestCompleted(
                                TokenResponse resp, AuthorizationException ex) {
                                if (resp != null) {
                                    System.out.println("@@@@@@@@@@@@@@@@@@ Id token "+resp.idToken);
                                } else {
                                    // authorization failed, check ex for more details
                                    System.out.println("GetToken failed:" + ex.toJsonString());
                                }
                            }
                        });
                    break;
                default:
                    System.out.println("Unknown return code: " + requestCode);
            }

        }
        
        ======================================================================
        Manifest
        
         <activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data
                    android:scheme="https"
                    android:host="msauth"
                    android:path="//${applicationId}/hashkey" />
            </intent-filter>
        </activity>

**Comment by agologan** [comment]
I'm assuming the error you're receiving is from the Azure/MSAL service.
If this issue happens every time it may be a configuration issue on the service which you maybe could address with tech support.
If it only happens some times, reading some other MSAL topics on https://github.com/AzureAD clearing the cache might resolve it as your session could be corrupted.

**Comment by Ronakgadhia** [comment]
I have cleared cache of browsers. But It does not work.

**Comment by agologan** [comment]
I'm sorry to hear that.
Please get in touch with your MSAL tech support since I do not know what the error means in the scope of authorization.

**Comment by Ronakgadhia** [comment]
Below 2 log I have found. Could you please check and let me know ?

```
 W/BrowserAuthorizationFragment:  [2021-05-31 13:12:14 - {"thread_id":"1","correlation_id":"UNSET"}] Calling activity class is NULL. Unable to create intent for response. Android 24

 W/BrowserTabActivity:  [2021-05-31 13:12:14 - {"thread_id":"1","correlation_id":"UNSET"}] Received NULL response intent. Unable to complete authorization. Android 24
```

**Comment by agologan** [comment]
That looks to be from https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/BrowserTabActivity.java are you sure you're using AppAuth for authentication?

**Comment by Ronakgadhia** [comment]
Yes I am using AppAuth for authentication (Microsoft openID connect ). The strange thing is that I have put above code in this demo and commented other things. It works fine. But It gives an error when I put above code in different project. Any thing I remain to put in my project ? Do you have any hint OR idea about it ? Thank you in advance.

**Comment by agologan** [comment]
I'm sorry but it seems you need to do some debugging to figure out where you went wrong in your second project.
While we try to help, providing coding and debugging support for your projects is not the aim of this group of maintainers.

Closing this issue as you've stipulated you have it working in your first project.
But feel free to open a new issue with a specific library problem if you find one.
