### ISSUE TITLE
Multi instance in Redirect URI

### ISSUE THREAD

**Issue by mehrdaddolatkhah** [openid/AppAuth-Android#705]
Hello guys

I have an issue when trying to use the deep link and open application. in this case, I have a multi-instance of my app with the same name and package name. I want to just one instance. (when I touch in one of the instances redirect happen but when touching the other one nothing happen)

every thing works perfectly good and only I have this issue.
I saw these issues too:
https://github.com/openid/AppAuth-Android/issues/329
https://github.com/openid/AppAuth-Android/issues/481
https://github.com/openid/AppAuth-Android/issues/491

and this is my code inside manifest:

```
<activity
            android:name=".util.deeplink.appAuth.RedirectUriReceiverActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="test"
                    android:host="ops" />
            </intent-filter>
        </activity>

```

**Comment by agologan** [comment]
I'm sorry but could you explain further what it means to have multiple instances, with the same name and package name?
Also what does touching on instance mean, is this selecting one app in the disambiguation dialog (the one that lists app)?

**Comment by mehrdaddolatkhah** [comment]
we found the solution. we have to just add 
```
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace"/>
```

be side our custom class:

```
<activity
            android:name=".util.deeplink.appAuth.RedirectUriReceiverActivity"
            android:windowSoftInputMode="stateAlwaysHidden">
```
into manifest file
