### ISSUE TITLE
Can't build unit tests after upgrade to AGP 4.2

### ISSUE THREAD

**Issue by klusi** [openid/AppAuth-Android#707]
Android Studio 4.2.1
AGP 4.2.1
Gradle 6.7.1
AppAuth 0.8.1.1

After upgrade to AGP 4.2.1 I'm getting error 
`
Manifest merger failed : Attribute data@scheme at manifestMerger17575735412594745234.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.
`
when I'm trying build unit tests. For normal build it's working. 
I have multi-module project and in my app module, there is AndroidManifest.xml:

```
<activity
    android:name="net.openid.appauth.RedirectUriReceiverActivity"
    tools:node="replace">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
            android:host="identity"
            android:scheme="xxx" />
    </intent-filter>
</activity>

```

In AppAuth module, there is test/AndroidManifest.xml:

```
<activity
    android:name="net.openid.appauth.RedirectUriReceiverActivity"
    tools:node="replace" />
```

And in build.gradle (app) I have:
```
unitTestVariants.all {
    it.mergedFlavor.manifestPlaceholders += [
            appAuthRedirectScheme: "xxx"
    ]
}
```

It worked fine until the upgrade. Probably "unitTestVariants" stopped working? Is there any alternative way?

**Comment by agologan** [comment]
We're using a similar [AndroidManifest.xml](https://github.com/openid/AppAuth-Android/blob/master/library/javatests/AndroidManifest.xml) which works alright, are you sure yours is similar?
Also make sure you're failing your unit `test` target and not `androidTest`.

**Comment by eminuluyol** [comment]
I have the same issue after updating AGp to 4.2.2 when I downgrade it, it works fine again.

**Comment by eminuluyol** [comment]
I have one library-module.gradle that is applied in every feature module. There manifestPlaceholder is defined:

`
android {

    compileSdkVersion project.compileSdkVersion
    buildToolsVersion project.buildToolsVersion

    defaultConfig {
        manifestPlaceholders = [
            'appAuthRedirectScheme': 'SchemeHere'
        ]
    }
}
`

Then in every module it is applied  like this:

`
apply from: "$rootDir/gradle/library-module.gradle"

`

It used to work perfectly after migrating to AGP 4.2.2 it stopped working and I am getting this manifest merger error.

**Comment by agologan** [comment]
@eminuluyol I'm sorry but I'm not sure what's your expectation here?
Is it failing for you? is it working? have you tried defining a testing manifest? can you provide the actual logs?

**Comment by MichalKlusak** [comment]
I solved it by having empty replacement in every module that has dependency on AppAuth library:

```
<activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace" />
```

so unit tests don't have to see appAuthRedirectScheme constant and only in my app module I have full replacement:
```
<activity
    android:name="net.openid.appauth.RedirectUriReceiverActivity"
    tools:node="replace">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
            android:host="identity"
            android:scheme="xxx" />
    </intent-filter>
</activity>

```

**Comment by vramasam** [comment]
HI @MichalKlusak 

Please tell my understanding is correct here.

If we add this code in the UnitTest
<activity
    android:name="net.openid.appauth.RedirectUriReceiverActivity"
    tools:node="replace">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
            android:host="identity"
            android:scheme="xxx" />
    </intent-filter>
</activity>

Then we wont skip this issue?

**Comment by vramasam** [comment]
Hello @MichalKlusak 

Please tell my understanding is correct.

If we add the below code snippet we can skip this error /build/intermediates/tmp/manifest/test/debug/tempFile1ProcessTestManifest13574892463324541007.xml Error:
        Attribute data@scheme at tempFile1ProcessTestManifest13574892463324541007.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.
`<activity
    android:name="net.openid.appauth.RedirectUriReceiverActivity"
    tools:node="replace">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
            android:host="identity"
            android:scheme="xxx" />
    </intent-filter>
</activity>`

I have tried it didn't worked for me. Please let me know If I missed something here

**Comment by agologan** [comment]
@vramasam you need to add an `AndroidManifest.xml` to `<module>/src/test` or `<module>/src/androidTest` depending on your usage. (https://github.com/openid/AppAuth-Android/issues/707#issuecomment-854387220)
The activity definition can be empty as exemplified by @MichalKlusak .

**Comment by vramasam** [comment]
Okay @agologan  Thank you for the response. 

I have tried the same. It didn't work for me. I am trying with AGP 7.x.x . May be because of that

**Comment by MichalKlusak** [comment]
@agologan  I didn't even need to add it to tests. In `<module>/src/AndroidManifest.xml` it is enough. test and AndroidTest use it as fallback. 
@vramasam The point is that we want every module except the main module (app module) don't see appAuthRedirectScheme so when we have for example this module hierarchy
```
                                   app
                                    |
                           ______________________________________
                            |                        |         |
                            A                        B         C
                            |                        |         
                       _____________              AppAuth
                       |           |
                       D           E
                                   |
                                AppAuth

```
we have to add empty replacement to modules B and E so every module above them (for example A) get empty RedirectUriReceiverActivity in manifest merger and only in app module add AndroidManifest with final android:host and android:scheme.

**Comment by agologan** [comment]
Seems reasonable and it really depends on how each of us structure their projects.

**Comment by agologan** [comment]
_Closing this as there has been no response from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you require further assistance 👍_
