### ISSUE TITLE
If authentification is successfull : How to launch a new activity 

### ISSUE THREAD

**Issue by osvaldo14** [openid/AppAuth-Android#708]
### Configuration
- Version: 0.X.Y
- Integration: Java
- Identity provider: KeyCloack

### Description
I do not understand how do I launch a new activity if the Authentification was successfull : 

When I receive the token from a valid authentification, I want to retrieve an information from the token (like the username) and compare it with an "if" statement and then launch a new activity. The problem is : Where do I implement this ?

(I started from the demo app with an adaptation for my current application)

I'm sure, I'm missing something simple, but I do not understand ^^'

**Comment by agologan** [comment]
I can understand why it's not immediately obvious as the demo app takes the authorization response and passes it to the TokenActivity at [LoginActivity.java#L180](https://github.com/openid/AppAuth-Android/blob/9aca8c0d9c8a188b34be46133d2b9ac312bf55d9/app/java/net/openid/appauthdemo/LoginActivity.java#L180)
The TokenActivity then reads the information from the response bundle and decides how to proceed [TokenActivity.java#L131](https://github.com/openid/AppAuth-Android/blob/9aca8c0d9c8a188b34be46133d2b9ac312bf55d9/app/java/net/openid/appauthdemo/TokenActivity.java#L131)

In your case you don't need the extra activity and can incorporate whatever logic you need after `onActivityResult()` which may include doing a `fetchUserInfo()` request and when you're satisfied store the AuthState and proceed.

**Comment by osvaldo14** [comment]
Thank you for your answer. I gave it a try today, but unfortunately when I try to fetchUserInfo(), the JSON object is always null

JSONObject userInfo = mUserInfoJson.get(); return null when it's done around TokenActivity.java#L131

```
if (response != null && response.authorizationCode != null) {
            // authorization code exchange is required
            mStateManager.updateAfterAuthorization(response, ex);
            exchangeAuthorizationCode(response);
            //CheckUserValidity try to fetchUserInfo() then compare result with other value
            checkUserValidity(); 
        } else if (ex != null) {
            displayNotAuthorized("Authorization flow failed: " + ex.getMessage());
        } else {
            displayNotAuthorized("No authorization state retained - reauthorization required");
        }
```


CheckUserValidity :
```
private void checkUserValidity(){
        fetchUserInfo();
        JSONObject userInfo = mUserInfoJson.get(); //Always null
        if (userInfo != null) { 
            try {
                String initiales = "???";
                if (userInfo.has("preferred_username")) {
                    userName= userInfo.getString("preferred_username");
                    if(!userName.equals("StringToCompareWith")){
                        signOut();
                    }else {
                        Intent intent = new Intent(this, OtherActivity.class);
                        startActivity(intent);
                        finish();
                    }
                }
            } catch (JSONException ex) {
                Log.e(TAG, "Failed to read userinfo JSON", ex);
            }
        }
    }
```


Do I miss something on getting user infos like that ? 
Maybe can I retrieve preferred_username from user infos directly inside LoginActivity ?

**Comment by agologan** [comment]
Yes you are missing something, `fetchUserInfo()` in the demo is not synchronous.
It executes the request async by calling `mExecutor.submit()` and returns to the main thread after completion with `runOnUiThread`

Also, please remember that is just a demo and is not meant to be taken as: "we recommend this pattern". Do whatever is best for your app.

**Comment by agologan** [comment]
_Closing this as there has been no response from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you require further assistance 👍_
