### ISSUE TITLE
Consent Page getting reloaded for the first time

### ISSUE THREAD

**Issue by Guhan1201** [openid/AppAuth-Android#709]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [ ] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [ ] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.X.Y
- Integration: (native(Java/Kotlin), Xamarin, ReactNative, etc)
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

### Issue Description

  when user gives the username and password and get validated in the token point page and then move the consent page, if user tap on the android back button consent page getting reloaded. in second time is working as expected.

**Comment by agologan** [comment]
Please provide more context, as we don't know what consent you are referring to.
Think about describing exact steps to reproduce the issue, telling us which is the provider your are working with and what version of lib you have integrated.

_The checklist in the issue template is meant to help us collect a minimum amount of information about the issue and should not be skipped and is also not meant to be exhaustive._

**Comment by agologan** [comment]
_Closing this as there has been no response to our request for more information from the OP in a reasonable amount of time. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍_
