### ISSUE TITLE
[Curity] Login Page is called again in WebView just before authorization

### ISSUE THREAD

**Issue by mschmiedel** [openid/AppAuth-Android#710]
### Checklist:

- [ X ] I am using the latest release
- [ X ] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [ X ] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [ X ] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [ X ] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [ X ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.9.0
- Integration: (Android native - Kotlin)
- Identity provider: (Curity)

If we test our OAUTH2 login flow with a tool like postman, we see the following (relevant) requests:

1a GET /authentication/login (login page) -> 200
2a POST /authentication/login (post with credentials) -> 200
3a POST /oauth-authorize?client_id=foobar -> 302
4a POST /oauth-token -> 200 (as many times as necessary with the refresh token flow)

In our Android app we see an error page after successful login (after 2a), this error page disappears after <1s and then everything works as expected (refresh-token flow is ok after that). 

If we test it with your demo app, we can debug and see the following requests in the webview:

1b GET /authentication/login (login page) -> 200
2b POST /authentication/login (post with credentials) -> 200
3b POST /oauth-authorize?client_id=foobar -> (canceled status in Chrome)
4b GET /authentication/login (login page) -> 400 (bad request)

After that the Webview is closed and from then everything works as expected. Even the redirect to the activity (net.openid.appauthdemo:/oauth2redirect) is working, our app uses the same pattern.

So the bug report is: why is AppAuth doing further calls in the browser that are not expected (4b), and why is the call 3b being marked as canceled by the browser? We only see this 400 errors when default browser on Android is set to Chrome. On Firefox it seems to work properly.

**Comment by agologan** [comment]
I think there's a misunderstanding here:
Between sending the authorization request to the browser and receiving the authorization code back via the redirect_uri AppAuth doesn't do anything. All the requests and redirects you see in browser are made by the identity provider.
Ref: https://datatracker.ietf.org/doc/html/rfc8252#section-4.1

Please get in touch with Curity to clarify the behavior and let us know of the outcome.

**Comment by mschmiedel** [comment]
@agologan, there is no redirect from the Auth Provider to the login page at any time. In fact, trying it out with postman, in Step 3a we get the proper redirect to the configured activity as expected. If there was something wrong there, the flow would not work at all.

I am rather suspecting that at some point you might be intercepting the response from the auth endpoint and stopping the browser at that point (why is chrome debugger showing the auth request that redirects to the activity as canceled?). Maybe chrome is trying then to return to the last known page, which is the login page, but a get to that page might show a "bad request" because the identity provider finds out that the user is already authenticated? 

On the other hand, when configuring Firefox as default browser we never find the "400" requests in the access logs of the identity server...

We will be debugging with the test app today and see if we can nail it down.

**Comment by agologan** [comment]
Please understand AppAuth uses an external user-agent and cannot tamper with requests happening in that target browser.
That is why it's very important that the custom scheme or App Link is configured correctly otherwise we'd never get the authorization code back.

Furthermore you can look at the doc in [AuthorizationManagementActivity](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationManagementActivity.java) to understand the flow of data in the scope of your app.

You also need to be clearer in your statements about differentiating between the various actors: your app, the identity provider (Curity) and your service. e.g. when you state login page, is it referring to your Android app's login activity which initiates the login flow or the login page in the browser? as for the login page in the browser are you refering to Curity's HTML Form Authenticator or are you delegating authentication further to another service?

**Comment by agologan** [comment]
_Closing this as there has been no response from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you require further assistance 👍_
