### ISSUE TITLE
exactly one of authResponse or authException should be non-null

### ISSUE THREAD

**Issue by gary-doolin** [openid/AppAuth-Android#711]
### Configuration
- Version: 0.8.1
- Integration: kotlin
- Identity provider: keycloak

### Description
I have just released the app auth integration in our app to the wild.  I am experiencing the reports of `java.lang.IllegalArgumentException: exactly one of authResponse or authException should be non-null`
I have dug into the code and can see the auth state shouldn't be updated if both are null.  That is an easy fix.  My question is what could the reason be for this happening?

Any help is greatly appreciated

**Comment by agologan** [comment]
The function throwing that Exception is `AuthState#update`. 
The function is meant to be called by the developer after extracting `AuthorizationResponse` and `AuthorizationException` from the returned intent. 
These are added to the bundle via the `AuthorizationManagementActivity#extractResponseData` which will add one or the other.
In case of user cancellation you still get an `AuthorizationException` and a resultCode.

Can only suggest to check how you're calling `AuthState#update` and if it's possibly being called in a scenario other than the one described.

**Comment by gary-doolin** [comment]
@agologan thanks for coming back to me.  That is where I am updating the auth state after extracting from the intent.  I had no safe guards however in place for both being null.. here is my updated code:

```
 fun fetchRequestToken(data: Intent?, requestListener: TokenRequestListener, requestCode: Int? = null, service: AuthorizationService?, context: Context) {
            data?.let {
                val successResponse = AuthorizationResponse.fromIntent(it)
                val exceptionResponse = AuthorizationException.fromIntent(it)

                if (responseOrExceptionIsNotNull(successResponse, exceptionResponse)) {
                    AuthStateManager.updateAfterAuthorisation(
                        successResponse,
                        exceptionResponse,
                        context
                    )
                }

                if (successResponseIsComplete(successResponse)) {
                    requestToken(successResponse, requestListener, requestCode, service, context)
                    AuthStateManager.updateAfterAuthorisation(
                        successResponse,
                        exceptionResponse,
                        context
                    )
                } else {
                    if (exceptionResponse?.code == FLOW_CANCELLED_CODE) return
                    requestListener.onTokenRequestError(exceptionResponse)
                }
            }
        }
```
I'm not sure as to why it may happen that both of them are null.  If I understand you correctly, they should never both be null?

**Comment by agologan** [comment]
We don't expect both being null as seen from this old commit 7089089ab6a5950da773d68168e2683da523bfd5
Is it possible the intent here is not exactly the one delivered by the lib?

_To help debug this further you could also add a log line in the failure case to attach to the report._

**Comment by jsparidaans** [comment]
I resolved a similar issue today using the following:

### Add redirect activity to manifest
```xml
        <activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>

                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>

                <data android:scheme="com.example.package"/>
            </intent-filter>
        </activity>
```

### Add an intent action to your own receiving activity
```xml
        <activity
            android:name="com.example.package.presentation.ui.home.HomeActivity"
            android:exported="true"
            android:label="@string/title_activity_home"
            android:theme="@style/Theme.Example.NoActionBar">
            <intent-filter>
                <action android:name="com.example.package.HANDLE_AUTH_RESPONSE" />

                <category android:name="android.intent.category.DEFAULT" />

            </intent-filter>
        </activity>
```

dont forget to set the intent filter's action on you success intent

```kotlin
        val authSuccessIntent = PendingIntent.getActivity(
            context,
            0,
            Intent(context, HomeActivity::class.java).setAction("com.example.migate.HANDLE_AUTH_RESPONSE"), 0
        )
```

**Comment by agologan** [comment]
@jsparidaans not sure how your comment relates to OPs inquiry.
Could you please explain?

**Comment by jsparidaans** [comment]
@agologan Sure! Before I added the things I said above, I would get the same error, saying that either `AuthorizationResponse` or `AuthorizationException` should be non-null. I checked in the debugger, and sure enough both were indeed `null`. 

After some googling I noticed that in an unrelated project someone had added the `net.openid.appauth.RedirectUriReceiverActivity`  `<activity>`-tag to their manifest without actually implementing that activity in their own app. That's when I decided to try and add an action to the `authSuccessIntent` and receive that action in my own activity. 

That was my approach to a, perhaps not completely the same, but similar issue that OP encountered.

**Comment by agologan** [comment]
_Closing this as there has been no response from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you require further assistance 👍_
