### ISSUE TITLE
BrowserDescriptor null for some users

### ISSUE THREAD

**Issue by developering** [openid/AppAuth-Android#716]
### Configuration
- Version: 0.9.1
- Integration: native(Java/Kotlin)
- Identity provider: Auth0

### Description
@agologan I noticed the changes that you made in these commits:
https://github.com/openid/AppAuth-Android/commit/d4fde4462126fa0f5c183509dc9775d189d8e11b
https://github.com/openid/AppAuth-Android/commit/e047a5e453e2ffa5559365c54bceb4b1bd8aff96

We had started to have an issue where the BrowserDescriptor was null for some users, but could not figure out why it was happening. I was about to submit a bug here when I noticed that you had just made those changes. They appear to have fixed the issue, so thank you for that!

My question is...do you know why this started breaking? Did something change in the Android OS that triggered this? We've been seeing the issue on Samsung, Moto, Google, etc. Also seeing it on Android 8-11. We were at a loss for why it started happening, and why it only affected specific users. Just curious how you know to make that change and what might have caused it.

**Comment by Android3005** [comment]
I am currently using the **appAuth version: 0.7.1** and facing the same above mentioned issue on **9-11 Android** versions. So @developering just wanted to check if upgrading to 0.9.1 is fixing the BrowserDescriptor null issue for you.

**Comment by agologan** [comment]
I'm assuming you're referring to `mBrowser` being `null` in `AuthorizationService`.
If you read through issue #521 you'll notice the browser selector was returning incorrect results when having Opera (maybe other browsers too) set as default since at least Android 7.0.

@Android3005 I highly encourage you upgrade the lib version as there are many other fixes since `0.7.1`.

**Comment by developering** [comment]
@Android3005 We updated to `v0.9.1` and it fixed the issue for us. I don't fully understand what happened, but we started seeing a spike in `ActivityNotFoundException` errors in our logs. We hadn't pushed any other changes, so we don't know why it started happening so much.

That said, `v0.9.1` completely took care of the issue for us. 

Thank you, @agologan!

**Comment by 1your** [comment]
Hiii sir
