### ISSUE TITLE
BrowserSelector.getAllBrowsers(context) returns empty since android update

### ISSUE THREAD

**Issue by bsautner** [openid/AppAuth-Android#718]
### Configuration
- Version: 0.7.1
- Integration: native Kotlin
- Identity provider: Comcast

### Description

We are seeing an increase of errors from our production app and determined an increasing number of users are getting an empty list of available browsers when we call `BrowserSelector.getAllBrowsers(context)`.  We found upgrading our client to 0.9.1 fixes the problem.   I'm wondering if anyone knows what would be different in 0.9.1 that would resolve this and if any recent Google updates would permanently break 0.7.1?

**Comment by agologan** [comment]
`0.7.1` browser list is empty in Android 11+ due to https://developer.android.com/training/package-visibility
Topic has been discussed here: #648 and has been resolved since `0.8.0`.
