### ISSUE TITLE
Getting ActivityNotFoundException even device has chrome browser installed and set as default. What could be potential reasons?

### ISSUE THREAD

**Issue by mohdaquib** [openid/AppAuth-Android#719]
### Configuration
- Version: 0.7.1
- Integration: Kotlin
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

**Comment by agologan** [comment]
https://github.com/openid/AppAuth-Android/issues?q=ActivityNotFoundException many reasons.
Update your lib to `v0.9.1` test and report back with as much information as possible.
