### ISSUE TITLE
Use Instagram login with AppAuth

### ISSUE THREAD

**Issue by vluongo** [openid/AppAuth-Android#720]
I'm trying to use this library to get an access token from Instagram. I'm using [this example](https://github.com/howtodoandroid/Android-Example/tree/master/MyAppAuth) as a base. It logs you with Google APIs and it works fine, so I thought I'd start from there. But I can't seem to make it work.
The authorization URL I'm using is https://api.instagram.com/oauth/authorize, while the token endpoint is https://api.instagram.com/oauth/access_token.
The example uses a custom schema URL, having the redirect in its manifest like so:
```xml
<activity 
  android:name="net.openid.appauth.RedirectUriReceiverActivity"
  tools:node="replace">
  <intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="com.google.codelabs.appauth"/>
  </intent-filter>
</activity>
``` 
and com.google.codelabs.appauth:/oauth2callback as the redirect URL in its code. When I tried to set this exact URL in the configuration of my Instagram app, it would automatically add https at the beginning of it, so I assumed Instagram didn't accept custom schemes (or am I wrong? Is there some configuration I'm missing?). Just in case, I did try running the code keeping the manifest and redirect URL intact, and with that https://com.google.codelabs... URL in the Instagram configuration, and when the custom tab opens, I get an error (it only says "oops, an error occurred", so it's not exactly helpful).
So I assumed I needed to try with an HTTPS redirect URL. I changed the manifest like this:
```xml
<activity
  android:name="net.openid.appauth.RedirectUriReceiverActivity"
  tools:node="replace">
  <intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="https"
      android:host="example.com" android:path="/oauth2redirect"/>
    </intent-filter>
</activity>
```
with https://example.com/oauth2redirect as my redirect URL in code and in Instagram. I get the same "oops, an error occurred", though, and I have no idea what to do. Obviously this URL isn't real, I'm not sure if that's the problem or part of it.
I'm sure I simply haven't configured something correctly, probably on the Instagram app side of things, but I don't know what. I added the "Instagram basic visualization API" product, set the redirect URL there, and on the main app basic configuration, I added "website" as platform with "https://example.com" as my website (I tried the Android option, but since it requires the Google Play package, hash key, and other stuff, I assume that's not meant for what I'm trying to do).
Does anyone have any suggestions?

**Comment by agologan** [comment]
In order to login "via Instagram" you actually need to login using Facebook. (https://developers.facebook.com/docs/instagram-api/overview)
I won't go into exact details because Facebook has decent documentation on their website, but you have to create an app in their developer portal and then either use their SDK (which I recommend to make it easier on yourself) or use AppAuth following the instructions in their Advanced section (https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/).

_Closing this for now. Feel free to create a new issue if you have question about this library and redirect other Facebook-specific questions to their developer support service._
