### ISSUE TITLE
After mfa call, browser get stuck and do not redirect to app

### ISSUE THREAD

**Issue by poke-fcr** [openid/AppAuth-Android#722]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [x] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.X.Y
- Integration: (native(Java/Kotlin), Xamarin, ReactNative, etc)
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

### Issue Description

The app is working fine when i login without mfa, or login with mfa method as otp (text sms). But when user is require to do mfa via phone call, after mfa the browser gets stuck and app is not launched back.

**Comment by agologan** [comment]
Please provide which version of the lib you're using, which OS and which browser.
Please also go into further detail explaining what the browser "gets stuck" means, as it sounds like a browser issue and not a lib issue, but maybe it isn't.

**Comment by carstenhag** [comment]
Sounds like #135 to me.

**Comment by anandayyanar3450** [comment]
I have configured the latest library ie "net.openid.appauth:0.10.0" . On initialisation from the android app , a custom tab is opened after verifying the user credentials and gets an  mfa call and after which the library is not getting redirected to the app and also app is in the background

**Comment by agologan** [comment]
@anandayyanar3450 please open a new ticket explaining the issue step by step.

I read your item as login in the custom tab, enter phone verification code again in the tab at which point it should redirect back to the app but it doesn't. If that's the case it's probably a problem with the redirect as there are many other struggling getting their custom scheme/app links working.

_Closing this as there has been no response to our request for more information from the OP in a reasonable amount of time. The OP may [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if they still experience this problem and can provide further information 👍_
