### ISSUE TITLE
Display Browser logs

### ISSUE THREAD

**Issue by Najam94** [openid/AppAuth-Android#729]
### Configuration
- Version: 0.10.0
- Integration: (native(Java/Kotlin))
- Identity provider: (AppAuth)

### Description
I'm trying to created an account and stuck on **"please wait while we process your information"**. How can i get browser error logs to debug the issue?

**Comment by agologan** [comment]
Assuming you're using Chrome and custom tabs just open `chrome://inspect`.

**Comment by agologan** [comment]
Closing this as there has been no response from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you need further assistance 👍
