### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by mlendl** [openid/AppAuth-Android#731]
I am trying to perform a token request, but it throws:

java.lang.IllegalStateException: grant type not specified and cannot be inferred
        at net.openid.appauth.TokenRequest$Builder.inferGrantType(TokenRequest.java:476)
        at net.openid.appauth.TokenRequest$Builder.build(TokenRequest.java:435)

this is my code:

        AuthorizationServiceConfiguration serviceConfig = new AuthorizationServiceConfiguration(
                Uri.parse(Config.IDENTITY_SERVER_URL),
                Uri.parse(Config.IDENTITY_SERVER_TOKEN_URL));

        AuthorizationService authService = new AuthorizationService(this);
        ClientAuthentication clientAuth = new ClientSecretBasic("my_secret");
        TokenRequest tokenRequest = new TokenRequest.Builder(serviceConfig, "my_id")
                .setScope("my_scope")
                .build();
        authService.performTokenRequest(tokenRequest, clientAuth, (response, ex) -> {
            if (ex != null) {
                ex.printStackTrace();
                return;
            }
        });

What's wrong?
Thanks very much

**Comment by agologan** [comment]
The error is quite explicit, you haven't set the `grantType`
Guessing you want `.setGrantType(GrantTypeValues.AUTHORIZATION_CODE)`

**Comment by agologan** [comment]
_Closing this as there has been no response from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you require further assistance 👍_
