### ISSUE TITLE
Is there a way to pass a custom header to `authorize` endpoint?

### ISSUE THREAD

**Issue by liriarte** [openid/AppAuth-Android#740]
### Configuration
- Version: 0.8.1
- Integration: Native (Java/Kotlin)
- Identity provider: Auth0

### Description
Is there a way to pass a custom header to `authorize` endpoint? I've also found [this issue](https://github.com/openid/AppAuth-iOS/issues/590) with the iOS version.

**Comment by agologan** [comment]
No. Authorization happens out of process as explained by the diagram in the header here:  [AuthorizationManagementActivity.java](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationManagementActivity.java)
You can however pass in URL parameters using `AuthorizationRequest.Builder.setAdditionalParameters()`
