### ISSUE TITLE
IdToken validation lambda

### ISSUE THREAD

**Issue by Eightyplus** [openid/AppAuth-Android#741]
Hi, I was trying to to the newest App Auth, but our idToken validation fails because our server gives a wrong issuer (actually a scope and not a URL). 

They won't change it now, maybe not in the near future. 🤦 

### Feature Request

I see that there is a `setSkipIssuerHttpsCheck`, which is to narrow for my case. How about implementing an interface that does the validation instead of the code in `IdToken.validate`

I can implement the feature my self 👍 

#### Motivation

I would like to update to newest version of AppAuth, but I'm not able to do so. 

#### Description

```
public interface IdTokenValidation {
   public boolean validate(idToken: IdToken);
}

IdTokenValidation validator = (idToken: IdToken) -> {
      ....
     return true
} 

AppAuthConfiguration appAuthConfig = new AppAuthConfiguration.Builder()
    .setIdTokenValidation(validator)
    .build()
```

**Comment by agologan** [comment]
While I understand the frustration, going off spec is not something I'd like to encourage.
There are ways around it though such as modifying or creating your own correct discovery document until your provider can fix the issue.

**Comment by Eightyplus** [comment]
So debating this with our platform team this is not going to be fixed. The issuer is "URN" based, which is also suppose to be valid (or used to?).

I would like to update the package, do you think "hacking" the discovery document is a good idea?

`skipIssuerHttpsCheck` is already a "hack" in my opinion.

**Comment by agologan** [comment]
I'm sorry but I don't understand. The spec is clear:

> The issuer returned by discovery MUST exactly match the value of iss in the ID Token.
Ref: https://openid.net/specs/openid-connect-core-1_0.html#IssuerIdentifier

Correcting your input data but providing a correct discovery document seems reasonable to me.

As for `skipIssuerHttpsCheck` that is a hack for testing in development environments that don't have SSL enabled yet and I should probably add a warning so they don't forget to disable it when going live.

**Comment by agologan** [comment]
Closing this again. Feel free to reply if you have something else to add.
If I wasn't explicit enough the current answer is still: **no**, we don't want to add something like this.
