### ISSUE TITLE
Open ID issues on Android Native. Authorisation code failure. Invalid Client ID

### ISSUE THREAD

**Issue by mohsinaliopt** [openid/AppAuth-Android#752]
### Checklist:

- [ x] I am using the latest release
- [ x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [ x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [ x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x ] I am either using a custom URI scheme or `https` with [App Links](https://developer.android.com/training/app-links) for client redirect.
- [ x] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.10.0
- Integration: (native(Java))
- Identity provider: (Microsoft)

### Issue Description

Open ID issues on Android Native. Says Authorization code failure results with Invalid Client ID. I have tried the same client ID and credentials, endpoints with a sample iOS app; it works perfectly, same works for the web application.

I have Used the sample: https://github.com/openid/AppAuth-Android and https://github.com/hadiidbouk/AppAuthIdentityServer4

but results are the same, help/feedback is appreciated. thanks in advance.

**Comment by agologan** [comment]
Since you've tested this using the sample please provide your `auth_config.json` to better understand your configuration.

**Comment by mohsinaliopt** [comment]
> Since you've tested this using the sample please provide your `auth_config.json` to better understand your configuration.

ClientName = "AndroidIdpClient",
ClientId = "AndroidIdpClient",
ProtocolType = "oidc",
Description = "AndroidIdpClient",
AlwaysIncludeUserClaimsInIdToken = true,
AllowOfflineAccess = true,
AbsoluteRefreshTokenLifetime = 31536000, //365 days
AccessTokenLifetime = 31536000, //365 days
AuthorizationCodeLifetime = 300,
IdentityTokenLifetime = 300,
RequireConsent = false,
RequirePkce = true,

**Comment by dg76** [comment]
I had the same problem and it turned out it was caused by the time on the device being incorrectly set (it was a simulator and accidentally the clock went forward two hours). After I set the correct time on the device, the "Invalid Client ID" error vanished. You can find further information here:

https://github.com/openid/AppAuth-Android/issues/733

**Comment by softsan** [comment]
@mohsinaliopt Did you find any solution, i too have client_secret and getting the same Invalid_client error

**Comment by mohsinaliopt** [comment]
Yes. I was able to resolve this issue. 
I hardcoded the string values everywhere they were used. Rather than using R.string or a final interface member string. Just hardcode the values where needed.

**Comment by softsan** [comment]
@mohsinaliopt - How did you use client_secret in the code?
