### ISSUE TITLE
ChromeCustomTab crash when I click in password input

### ISSUE THREAD

**Issue by JorgeDiazP** [openid/AppAuth-Android#754]
### Checklist:
- [ x] I am using the latest release
- [ x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [ x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [ x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [ x] I am either using a custom URI scheme or `https` with [App Links](https://developer.android.com/training/app-links) for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.10.0
- Integration: (native(Java))
- Identity provider: (?)

### Issue Description
Hi everyone!

I have an app that uses AppAuth for login and in the form, when the user clicks in the password input, browser is closed.
This problem has been reproduced in 94.0.4606.80 Chrome version only and I don't know if a fix might be necessary, or if it would be a chrome problem.

I think that this Chrome version is only available for Android 10 and 11 versions.

Any help would be appreciated.

Thanks!.

**Comment by adyeardley** [comment]
Happening with our application also, the workaround was to get users to click the 3 dots and 'open in chrome', which then allowed them to log in.

Hoping to be resolved soon!

**Comment by nirmalrevarcenturylink** [comment]
Yes many people are facing same issue.

https://stackoverflow.com/questions/69540444/android-app-crashing-on-password-field-for-appauth-custom-tab-intent-on-chrome-b/69540492#69540492

**Comment by Sanjay-Katagihallimath** [comment]
Chrome team is working to fix the above issue.

https://bugs.chromium.org/p/chromium/issues/detail?id=1258311
