### ISSUE TITLE
IdToken getClaims

### ISSUE THREAD

**Issue by dIeGoLi** [openid/AppAuth-Android#759]
### Feature Request
The [IdToken](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/IdToken.java) class is currently private. It would be nice to easily read claims from id token. 
#### Motivation
Making it easy to read id token claims.

#### Description
IdToken class should be public. It already contains json parsing logic. The class should offer a method getClaims() which returns a `List<Claim>` where claim represents a string key and string value. Claim Value arrays could be "flattened" and be returned as multiple claims.

#### Alternatives or Workarounds
Do the json parsing yourself by copying code from IdToken class. :)

**Comment by agologan** [comment]
Thanks for @dkiro 's contribution, we now have support for reading custom claims.
You can read those using `AuthState#getParsedIdToken().additionalClaims`

Closing this request but let me know if this solution works for you.

**Comment by dIeGoLi** [comment]
That looks nice. Thanks! 👍
