### ISSUE TITLE
Aut app

### ISSUE THREAD

**Issue by oakoak4059** [openid/AppAuth-Android#761]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with [App Links](https://developer.android.com/training/app-links) for client redirect.
- [x] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.X.Y
- Integration: (native(Java/Kotlin), Xamarin, ReactNative, etc)
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

**Comment by oakoak4059** [comment]
Ok

**Comment by agologan** [comment]
Closing. Please open an issue with proper description if you need help with anything.
