### ISSUE TITLE
app-link based redirect not linking back to app as expected

### ISSUE THREAD

**Issue by Maushundb** [openid/AppAuth-Android#766]
### Configuration
- Version: 6.40.
- Integration: ReactNative
- Identity provider: Coinbase

### Description
I'm attempting to integrate with Coinbase OAuth (skipping the code exchange, just looking for the `code` parameter). 

Everything appears to work as intended until the flow needs to redirect back to my application. At this point, the user clicks Authorize:

<img src="https://user-images.githubusercontent.com/4198511/142956346-e3e9c3c0-45c9-4e58-a1d5-a67c4127d6cb.png" width="300" height="600">

And instead of redirecting back to my application, it just opens up the url in the webview:

<img src="https://user-images.githubusercontent.com/4198511/142956365-0efaca2b-e53d-4bfb-9060-e77b6cbf0d88.png" width="300" height="600">

My understanding is that it needs to destroy the webview, parse out the URL params, and redirect back to the app as per https://javadoc.io/doc/net.openid/appauth/0.6.1/net/openid/appauth/RedirectUriReceiverActivity.html

Here's my setup:

`main/AndroidManifest.xml`:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="com.monarchmoney.mobile">
        ...
        <application
            android:name=".MainApplication"
            android:label="@string/app_name"
            android:icon="@mipmap/ic_launcher"
            android:roundIcon="@mipmap/ic_launcher_round"
            android:allowBackup="false"
            android:usesCleartextTraffic="true"
            android:theme="@style/AppTheme">
            ...

            <activity
                android:name="net.openid.appauth.RedirectUriReceiverActivity"
                tools:node="replace">
                 <intent-filter>
                    <action android:name="android.intent.action.VIEW"/>
                    <category android:name="android.intent.category.DEFAULT"/>
                    <category android:name="android.intent.category.BROWSABLE"/>
                    <data android:scheme="https"/>
                    <data android:scheme="http"/>
                    <data android:host="app.monarchmoney.com"/>
                    <data android:pathPrefix="/oauth"/>                
                </intent-filter>
            </activity>
        </application>
        ...
</manifest>
```

and config:

```
const COINBASE_OAUTH_CONFIG = {
  clientId: COINBASE_CLIENT_ID,
  redirectUrl: https://app.monarchmoney.com/oauth,
  scopes: COINBASE_SCOPES,
  serviceConfiguration: {
    authorizationEndpoint: COINBASE_AUTH_URL,
    tokenEndpoint: '',
  },
  skipCodeExchange: true,
  additionalParameters: { account: 'all' },
};
```

we're **NOT** setting `appAuthRedirectScheme` since it's my understanding that using the RedirectUriReceiverActivity is what you do instead of that if you want to use https app-links. I've tried it both ways and neither seems to work. 

If it helps, we also have a prod AndriodManifest override for our other app-links:

`prod/AndriodManifest.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.monarchmoney.mobile">
    <application
            android:name=".MainApplication"
            android:label="@string/app_name"
            android:icon="@mipmap/ic_launcher"
            android:roundIcon="@mipmap/ic_launcher_round"
            android:allowBackup="false"
            android:theme="@style/AppTheme">
        <activity
                android:name=".MainActivity"
                android:label="@string/app_name"
                android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
                android:launchMode="singleTask"
                android:windowSoftInputMode="adjustResize">

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>

                <data android:scheme="https"/>
                <data android:scheme="http"/>
                <data android:host="app.monarchmoney.com"/>
                <data android:pathPrefix="/links"/>
            </intent-filter>
        </activity>
    </application>
</manifest>

```

### Some notes:
- Using an `http` redirect uri seems to work (but is insecure) with this exact setup. Makes me think that we have something maybe setup wrong with the app-link schema ever so slightly
- The redirect DOES work when triggered from adb: `adb shell am start -a android.intent.action.VIEW -d "https://app.monarchmoney.com/oauth?code=597&state=foo"` appears to successfully redirect to the app for some reason. 
- Our website does host `assetLinks.json` for all known packages: https://app.monarchmoney.com/.well-known/assetlinks.json

Any help would be appreciated!

**Comment by agologan** [comment]
Your setup looks fine to me.
So I'm a bit at a loss here.
Assuming the redirects happen correctly tapping the browser menu (3 dots) and selecting open in browser should open your app.

**Comment by Maushundb** [comment]
@agologan 

> Assuming the redirects happen correctly tapping the browser menu (3 dots) and selecting open in browser should open your app.

Yeah that's not happening, I just see an "Open in Chrome" option and it just opens the same page in mobile Chrome when I click it.

**Comment by agologan** [comment]
Having tested this today it seems my expected behavior changed on Android 12.
Tested this on a lower version and "Open in Chrome" will pop a disambiguation dialog the first time you try to open a link there is another activity registered for the same URI match. (assuming App Links are not working)

Looking at your config again it seems you're missing `autoVerify` on the intent-filter for the `/oauth` path. 
Moreover it seems on Android 12 there is manual verification you can perform: https://developer.android.com/training/app-links/verify-site-associations#manual-verification

**Comment by markusrydh** [comment]
To me, it seems that your assetlinks.json is not actually json, but rather a javascript object? No quotes around fields, single quotes around strings, bad trailing commas, semicolon etc.

**Comment by agologan** [comment]
Great catch @markusrydh . 
_Resolving this issue for now since the OP has been inactive for so long._
