### ISSUE TITLE
java.lang.RuntimeException: Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by mayumipal** [openid/AppAuth-Android#768]
### Configuration
- Version: '0.10.0'
- Integration: (native(Kotlin)
- Identity provider: (Auth0)
- compileSdkVersion: 31
- targetSdkVersion: 31

### Description
hi, for some android devices (specially Android version 8.1.0, 9, 12)crash with this error. Result state= -1(RESULT_OK) "data" also not null, data contain "authorizationCode".

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1811784904, result=-1, data=Intent { dat=com.abc.v3.4df:/oauth2redirect?code=QdQk5NJq8zTKWbKjX-V31efagh62nnQgL3J06q0v8M0&amp;scope=openid profile tenant_code employee_code webapi offline_access&amp;state=W0iaArQHtx2IdpVhb0vM1Q&amp;session_state=Ehnxm1IKypA4-tfbGjJlj5rg2DBhV1-Kng46hu9pqFs.hOLT6ft_Ba0cTomMFd1fKw (has extras) }}
```

Can u provide me some ways to prevent it?

**Comment by agologan** [comment]
Seems related to this one: https://github.com/openid/AppAuth-Android/issues/746
Haven't had time to check it though.

**Comment by mayumipal** [comment]
I used AuthorizationRequest without Pending Intent

``
  val intent = mAuthService!!.getAuthorizationRequestIntent(
                mAuthRequest.get()!!,
                mAuthIntent.get()!!
            )
            startForResult.launch(intent)
``

**Comment by agologan** [comment]
That's fine but there's not enough information here to understand what happened.
There aren't any reproduction steps or even a stack trace.
You need to debug it a bit and provide further context.

**Comment by mayumipal** [comment]
Still I can't reproduce this issue in my side. My app is used by over 3000 clients, This issue occurred after I changed compile and target SDK version to 31. But not from all divices. 
Below I have attached the log I received from my issue tracker.

``
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1796253077, result=-1, data=Intent { dat=com.myapps.v3.3i8slmp:/oauth2redirect?code=_j2NMg1e983IJTDuDxgNtt2qw4mRH2XZ8PIL0rN6_cE&amp;scope=openid profile tenant_code employee_code webapi offline_access&amp;state=TYo8tpwAgtgbcZjl1j1F_A&amp;session_state=P0C9NV-GzbfoRXl-N_Oqv-sr53liXCdvzo4eqST4VSU.xM_ZZBLE_fZ_4VV2AzhmqA (has extras) }} to activity {com.myapps.v3/com.myapps.v3.auth.ui.activity.LoginActivity}: java.lang.NullPointerException
1 at android.app.ActivityThread.deliverResults(ActivityThread.java:4533)
2 at android.app.ActivityThread.handleSendResult(ActivityThread.java:4577)
3 at android.app.ActivityThread.-wrap22(Unknown Source:0)
4 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1789)
5 at android.os.Handler.dispatchMessage(Handler.java:106)
6 at android.os.Looper.loop(Looper.java:164)
7 at android.app.ActivityThread.main(ActivityThread.java:7025)
8 at java.lang.reflect.Method.invoke(Native Method)
9 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
10 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
11Caused by: java.lang.NullPointerException
12 at x8.a.c(:17)
13 at androidx.activity.result.ActivityResultRegistry.a(:1)
14 at androidx.activity.ComponentActivity.onActivityResult(Unknown Source:2)
15 at androidx.fragment.app.r.onActivityResult(Unknown Source:5)
16 at android.app.Activity.dispatchActivityResult(Activity.java:7672)
17 at android.app.ActivityThread.deliverResults(ActivityThread.java:4529)
18 ... 9 more
``

**Comment by agologan** [comment]
> to activity {com.myapps.v3/com.myapps.v3.auth.ui.activity.LoginActivity}

That is your own activity not the library.
Easy way to debug this is to mock the intent in your app and start it.

**Comment by ercan** [comment]
The reason was because I was doing this:
```
        onResult = { activityResult ->
            activityResult.data?.let {
                val authResponse = AuthorizationResponse.fromIntent(it)
                val request = authResponse!!.createTokenExchangeRequest()
```
Applying a null check on the authResponse object fixed the issue

**Comment by roshansrashtasoft** [comment]
![Screenshot 2023-11-17 at 3 14 44 PM](https://github.com/openid/AppAuth-Android/assets/97586645/2faad362-cf87-4cee-9978-5683f355061d)

Any solution ?

**Comment by appdevelopersurya** [comment]
complete solution for this problem any one can response setup by step process for these location permission error.
