### ISSUE TITLE
Taking time to call this method "handleCodeExchangeResponse"

### ISSUE THREAD

**Issue by MuhammadUsmanShaikh** [openid/AppAuth-Android#771]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [ ] I am either using a custom URI scheme or `https` with [App Links](https://developer.android.com/training/app-links) for client redirect.
- [x] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.10.0
- Integration: (native(Java/Kotlin))
- Identity provider: (Auth0)

### Issue Description
This method "handleCodeExchangeResponse" is taking too much time to call and process further after hitting the redirect URL.

It's taking random delays (2 to 10 minutes) not every time, we have faced this issue twice in a week.

we are using this version: "net.openid:appauth:0.10.0"

**Comment by agologan** [comment]
_Need to preface this that `handleCodeExchangeResponse` is part of the demo app and the code there is just an example and shouldn't just be adopted in your production application._

Looking at the TokenActivity after returning from the webview the demo app continues with a token request, so there's an expected delay. Now why this token request takes that long to complete really depends on your configuration and network conditions but I'd expected most configurations would time out in 60s.

Ref: https://github.com/openid/AppAuth-Android/blob/master/app/java/net/openid/appauthdemo/TokenActivity.java#L274

**Comment by MuhammadUsmanShaikh** [comment]
@agologan 

we have been faced this issue 2 to 3 times for the last 4 months, if we have any issue in the implementation of app auth on the android side and configuration then it will occur most of the time. we are not clear about it.

In the first line, you mention that method is part of the demo app not for production application kindly explain it.

**Comment by MuhammadUsmanShaikh** [comment]
@agologan we are waiting for your response.

**Comment by agologan** [comment]
> we have been faced this issue 2 to 3 times for the last 4 months, if we have any issue in the implementation of app auth on the android side and configuration then it will occur most of the time. we are not clear about it.

While I did try to offer context and explain your experience, you failed to debug and offer a counter argument why you think the library is at fault here. Please debug your own implementation and come back with enough context so a member of the community might help you.

> In the first line, you mention that method is part of the demo app not for production application kindly explain it.

Not sure what to explain here. Code in the /app directory is part of the demo app as explained in the README https://github.com/openid/AppAuth-Android/tree/master/app 
I would expect developers to look at that code for guidance on using the library, and build their own integration appropriate to their project's needs.

> we are waiting for your response.

Please be considerate of our relationship, as two members of an open-source community.
