### ISSUE TITLE
Custom tabs, app links and https scheme for Google Identity

### ISSUE THREAD

**Issue by stephanedupont** [openid/AppAuth-Android#784]
I'm trying to implement Google Sign-In for devices that doesn't have Google Play Services.

If I understand correctly:

- Custom Tabs are required to use with this library, as specified in the readme:
_The library follows the best practices set out in RFC 8252 - OAuth 2.0 for Native Apps, including using Custom Tabs for authorization requests. For this reason, WebView is explicitly not supported due to usability and security reasons._

- Custom tabs are not handling app links that starts with http/https correctly in most cases, so it's advised to use a custom scheme, see:
[https://stackoverflow.com/questions/51244910/android-app-links-not-working-with-chrome-custom-tabs](https://stackoverflow.com/questions/51244910/android-app-links-not-working-with-chrome-custom-tabs)
[https://bugs.chromium.org/p/chromium/issues/detail?id=581324](https://bugs.chromium.org/p/chromium/issues/detail?id=581324)
[https://bugs.chromium.org/p/chromium/issues/detail?id=1034872](https://bugs.chromium.org/p/chromium/issues/detail?id=1034872)

- Google Oauth Web Client doesn't allow for custom scheme, only http/https schemes. So I have to use something like https://mydomain.com/callback

... so how am I supposed to achieve this?

Currently, after the auth process, the https://mydomain.com/callback callback is opened in the custom tab as a webpage. If I click on the three dot menu icon and click open in browser, then it works, Android asks me if I want to open the link with my app or a browser.

Any help or advice on this would be greatly appreciated :)

**Comment by agologan** [comment]
> Google Oauth Web Client doesn't allow for custom scheme, only http/https schemes. So I have to use something like https://mydomain.com/callback

Don't think you've read the documentation fully. This is the part that you need: https://developers.google.com/identity/protocols/oauth2/native-app#step-2:-send-a-request-to-googles-oauth-2.0-server

Here's my sample config I just tested (with the id swapped out):
```
{
  "client_id": "123.apps.googleusercontent.com",
  "redirect_uri": "com.googleusercontent.apps.123:/oauth2redirect",
  "end_session_redirect_uri": "com.googleusercontent.apps.123:/oauth2redirect",
  "authorization_scope": "openid email profile",
  "discovery_uri": "https://accounts.google.com/.well-known/openid-configuration",
  "https_required": true
}
```

As for Custom Tabs and App Links, most issues stem from App Links requiring user interaction before redirect https://github.com/openid/AppAuth-Android/issues/679#issuecomment-824091995 which some identity providers have already fixed by adding an extra account confirmation step if the user is already logged in.

**Comment by stephanedupont** [comment]
Thank you for your message.

> Don't think you've read the documentation fully. This is the part that you need: https://developers.google.com/identity/protocols/oauth2/native-app#step-2:-send-a-request-to-googles-oauth-2.0-server
> 
> Here's my sample config I just tested (with the id swapped out):
> 
> ```
> {
>   "client_id": "123.apps.googleusercontent.com",
>   "redirect_uri": "com.googleusercontent.apps.123:/oauth2redirect",
>   "end_session_redirect_uri": "com.googleusercontent.apps.123:/oauth2redirect",
>   "authorization_scope": "openid email profile",
>   "discovery_uri": "https://accounts.google.com/.well-known/openid-configuration",
>   "https_required": true
> }
> ```

Thank you, that looks promising. But what type of credentials do you use then?
- Android: it doesn't seem that I can set a redirect_uri if I choose Android
- Web app: it doesn't seem that I can add a redirect_uri with a custom scheme. Only http/https allowed.

What is the appropriate choice to be able to use AppAuth-Android library in an app for users that doesn't have Google Play Services on their device?

> As for Custom Tabs and App Links, most issues stem from App Links requiring user interaction before redirect [#679 (comment)](https://github.com/openid/AppAuth-Android/issues/679#issuecomment-824091995) which some identity providers have already fixed by adding an extra account confirmation step if the user is already logged in.

No, it's not the case. If the app has not been explicitly set as default for an intent (i.e. in most cases), custom tabs are always handling http/https request. (Also, there is user interaction before the redirect in my case.)

**Comment by stephanedupont** [comment]
... oh, or actually is com.googleuser.content.apps.123 is not a custom scheme that needs to be set on Google Console?
... and in that case, can I use an Android type Oauth 2.0 client?
... and do I have to declare handling the intent com.googleuser.content.apps.123 in the manifest?

Thank you!

**Comment by agologan** [comment]
> Thank you, that looks promising. But what type of credentials do you use then?
> - Android: it doesn't seem that I can set a redirect_uri if I choose Android
> - Web app: it doesn't seem that I can add a redirect_uri with a custom scheme. Only http/https allowed.

Android - the **redirect_uri** is automatically derived from your configuration, you don't specify it manually and it's either your domain or your google app uri in reverse domain notation as explained in the doc I linked.

> ... and do I have to declare handling the intent com.googleuser.content.apps.123 in the manifest?

You can declare your intent filter as explained in the README or I just used:
```
manifestPlaceholders = [
  'appAuthRedirectScheme': 'com.googleusercontent.apps.123'
]
```

> What is the appropriate choice to be able to use AppAuth-Android library?

Custom scheme is always easier to work with.

> No, it's not the case. If the app has not been explicitly set as default for an intent (i.e. in most cases), custom tabs are always handling http/https request. (Also, there is user interaction before the redirect in my case.)

This happens if your App Links are not configured/loaded correctly. This is beside the point of this thread now but you can look at the improvements done to App Link verification in Android 12 https://developer.android.com/training/app-links/verify-site-associations#manual-verification

**Comment by stephanedupont** [comment]
Thank you very much!

Thanks to you I managed to make it work (even if I don't understand how exactly I'm supposed to translate your configuration to Java - I didn't find how to specify end_session_redirect_uri or https_required in Java so I just didn't set them).

**Comment by agologan** [comment]
That's the configuration schema used in our demo app: https://github.com/openid/AppAuth-Android/tree/master/app
