### ISSUE TITLE
Question: Custom UI without using browser to authorize?

### ISSUE THREAD

**Issue by alwa** [openid/AppAuth-Android#785]
From the readme:

"Authorizing the user, via a browser, in order to obtain an authorization code"

I would like to fully customize the UI forms needed to complete the authorization/authentication requests and not have to launch a browser to display server side html. Is this possible? 

### Configuration
- Version: 0.X.Y
- Integration: native, Kotlin
- Identity provider: KeyCloak

**Comment by agologan** [comment]
Short answer: **No**.

The long answer is more then I could comfortably fit in this reply and there are much better articles and books out there written by my peers explaining why. 
Suffice it to say that OAuth 2.0 and by extension OpenID Connect enables identity verification without exposing the user's credentials to the app. This improves security and enables several architectural advantages.
If you have the time I recommend skimming [RFC8252: OAuth 2.0 for Native Apps
](https://www.rfc-editor.org/rfc/rfc8252.txt) which although talks about using webviews vs an external browser touches on many aspects of your question.
