### ISSUE TITLE
Android Logout/EndSession Keycloak

### ISSUE THREAD

**Issue by Jevgenijus** [openid/AppAuth-Android#790]
### Configuration
- Version: 0.10.0
- Integration: native Java
- Identity provider: KeyCloack
- Samsung Galaxy Tab A 2021

### Description
Im trying to use the code from example app to end session 
  Intent endSessionIntent = mAuthService.getEndSessionRequestIntent(
                new EndSessionRequest.Builder(config)
                        .setIdTokenHint(currentState.getIdToken())
                        .setPostLogoutRedirectUri(mConfiguration.getEndSessionRedirectUri())
                        .build());
        startActivityForResult(endSessionIntent, TokenActivity.END_SESSION_REQUEST_CODE);
        
But i keep getting invalid redirect uri error. What am i doing wrong?
        
![image](https://user-images.githubusercontent.com/4412622/147634642-7b022e69-0f19-4c9f-85aa-51f722991a3e.png)

**Comment by agologan** [comment]
I know this sounds obvious but have you checked your `endSessionRedirectUri` is a `Valid Redirect URIs` in your Keycloak client configuration? This is assuming you want to use a different URI compared to your authorization one. You could just use the same value.

**Comment by alwa** [comment]
@Jevgenijus I recently had the same issue (https://github.com/openid/AppAuth-Android/issues/799). My advice: Evaluate the "Uri" (string value) passed to `setPostLogoutRedirectUri()` and compare it to the whitelist, as suggested by @agologan 

In my case I had misunderstood how `Uri.Builder` worked and produced a Uri that looked like this in string format:

"scheme:/path"

**Comment by Jevgenijus** [comment]
Hi thnx this was the issue for me too.

**Comment by ayoubAnbara** [comment]
Can you please explain the solution? Because I have the same issue
