### ISSUE TITLE
How to read config.json file dynamically.

### ISSUE THREAD

**Issue by raza-xerus** [openid/AppAuth-Android#800]
### Configuration
- Version: 0.11.1
- Integration: (native(Java))
- Identity provider: ( KeyCloak)

### Description
Hi Team,
I am using AppAuth-android library for authentication and authorization with identity provider KeyCloak.
its working fine for one client.but my requirement is configure multiple client.I didn't get any solution for that.
So i need help for solve this issue.
and Also i want to know that from where this configuration.java file executed while Application running.
Is it possible to read config file dynamically?
And if it is possible then how to do it.

**Comment by agologan** [comment]
Judging by the fact you're referring to `config.json` and `Configuration.java` I'm guessing you're talking about the **demo** app.
I don't recommend just reusing that code directly as it is there to exemplify how you may begin integrating the library.

Whether or not you choose to use that code this not an appropriate place to ask general Android/programming questions. It's up for you to decide how to solve the various challenges of your product, we  may only assist with items regarding the library itself.
