### ISSUE TITLE
EndSessionRequest makes a GET Request but want a POST

### ISSUE THREAD

**Issue by jyot103095** [openid/AppAuth-Android#801]
### Configuration
- Version: 0.11.1
- Integration: native Kotlin
- Identity provider: Custom provider

### Description
Hi, I'm trying to use an `EndSessionRequest` to revoke an access token, before I force a user to log back in with `prompt: login`. The issue that I'm running into is when I perform this request, my backend is receiving a GET request at the end session endpoint rather than a POST. I'm not sure if my understanding is correct, but looking at the source code it seems like an AsynTask is used for requests that don't need a browser like a registration request and a token request, but not end session request. Is this intentional? If so, am I able to change the HTTP method that's used for an EndSessionRequest?

**Comment by agologan** [comment]
It's supposed to be a GET request and be done in browser via redirection.
Upon succesful logout the SSO session should be invalidated.

Ref: https://openid.net/specs/openid-connect-rpinitiated-1_0.html

**Comment by jyot103095** [comment]
That also says it can be a POST request. So could this be considered a feature request maybe?
