### ISSUE TITLE
I couldn't understand how should set host ,path and scheme in manifest. Please tell me what each of these should be?  

### ISSUE THREAD

**Issue by nazaninbalasi** [openid/AppAuth-Android#810]
### Configuration
- Version: 0.X.Y
- Integration: (native(Java/Kotlin), Xamarin, ReactNative, etc)
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

**Comment by agologan** [comment]
Think our [Readme.md ](https://github.com/openid/AppAuth-Android#readme) is pretty explicit.
If you have a redirect of `https://app.example.com/oauth2redirect` the config should be:
```        
<data android:scheme="https"
  android:host="app.example.com"
  android:path="/oauth2redirect"/>
```
For more information you can read: https://developer.android.com/guide/topics/manifest/data-element
Or https://developer.android.com/training/app-links/deep-linking
