### ISSUE TITLE
Is Sample App vulnerable to MITRE, CWE-926 - "Improper Export of Android Application Components"?

### ISSUE THREAD

**Issue by alwa** [openid/AppAuth-Android#811]
In https://github.com/openid/AppAuth-Android/blob/master/app/AndroidManifest.xml `net.openid.appauth.RedirectUriReceiverActivity` is exported but there is no permission set.

This causes static code analyzers to detect "vulnerabilities":
- https://cwe.mitre.org/data/definitions/926.html
- https://developer.android.com/guide/topics/providers/content-provider-creating#Permissions

Should app integrators care about this warning? If so, and if we do implement permissions, what should be the [sensitivity level](https://developer.android.com/guide/topics/manifest/permission-element#plevel)?

**Comment by agologan** [comment]
See #551 and let us know if you have any further questions or concerns.
