### ISSUE TITLE
A complete walkthrough

### ISSUE THREAD

**Issue by idc77** [openid/AppAuth-Android#815]
### Configuration
- Version: 0.11.1
- Integration: native(Kotlin)
- Identity provider: (KeyCloak)

### Description

I'm missing a complete walkthrough through the setup and configuration process.

Since I'm trying to use AppAuth-Android with Jetpack Composables and this only works with Kotlin I'm having some difficulties.
Also the readme is incomplete and the demo project has errors an converting a project from Java to Kotlin produces even more errors.

The very 1st  thing I've done is create a composables activity project and created my main view there.

Now I've added `implementation 'net.openid:appauth:0.11.1'` to `build.gradle`.
Trying to run I'm getting this error:
```
Manifest merger failed : Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.
```
AndroidManifest.xml
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="de.icod.iloveu">
    <uses-permission android:name="android.permission.INTERNET" />

    <application android:allowBackup="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:theme="@style/Theme.Iloveu">
        <activity android:name=".MainActivity" android:exported="true" android:label="@string/app_name"
            android:theme="@style/Theme.Iloveu.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

There is no mention in the readme about having to modify the AndroidManifest.xml beforehand. Only a vague
```
android.defaultConfig.manifestPlaceholders = [
  'appAuthRedirectScheme': 'com.example.app'
]
```
Where do you even paste this? This doesn't look like it's xml.

I'm sure there will be more landmines to step on.

Can you please provide a complete walkthrough?

**Comment by idc77** [comment]
I managed to "solve" this 1st issue as best as I could.

new AndroidManifest.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="de.icod.iloveu" xmlns:tools="http://schemas.android.com/tools">
    <uses-permission android:name="android.permission.INTERNET" />

    <application android:allowBackup="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:theme="@style/Theme.Iloveu">
        <activity android:name=".MainActivity" android:exported="true" android:label="@string/app_name"
            android:theme="@style/Theme.Iloveu.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="de.icod.iloveu"/>
            </intent-filter>
        </activity>
    </application>

</manifest>
```

**Comment by idc77** [comment]
I found https://gluu.org/docs/gluu-server/integration/native-apps/appauth-android/
but it's just saying to clone this repo and edit `res/raw/auth_config.json`

**Comment by idc77** [comment]
Can you provide a minimum necessary example using Jetpack Compose with "login-required" which checks if the user is authenticated, if not start the auth dance and finally return to the main view?

**Comment by agologan** [comment]
We assume engineers have some familiarity with Android.
I agree it's not as straightforward as it could be, and have long been wanting to write a more Kotlin-friendly demo.

As for `appAuthRedirectScheme` it goes in your build.gradle as seen in the demo:
https://github.com/openid/AppAuth-Android/blob/master/app/build.gradle#L15
or you can override the intent-filter as you have and as explained in the README.

**Comment by idc77** [comment]
Closed doors in open source Java/Kotlin.
This is what I find in the Java and/or Kotlin world.
Unlike Go.
Disappointing but not unexpected.
Instead of resolving issues and answering questions they get closed.
People have changed.  Passive aggressiveness is the norm nowadays.
