### ISSUE TITLE
Non-persist/ Temporary session cookies is persisted even after app close and reinstall

### ISSUE THREAD

**Issue by lclrobert2020** [openid/AppAuth-Android#816]
### Configuration
- Version: latest
- Integration:  Java Android
- Identity provider: Keycloak

### Description
I am using the demo app provided in this github.
The Chrome Custom Tab seems to keep the Non-persist/ Temporary session cookies even after app is close and app is reinstalled.

On Desktop browser, it works perfectly and when the browser is closed, the session cookies are gone and it required login again.

When I login via the keycloak server using AppAuth, I DIDN'T enable the Remember Me function so that the SSO session cookies is not persistence cookies (https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/login-settings/remember-me.adoc) . But the Custom Tab keeps the session cookies and use it so that it skips the login page even after app reinstalled, even when the session cookies are not persistence cookie.

When I go to my system and force close the CHROME application on my phone, the session cookies are then gone and the app required login again after reinstall.

Is there a way to stop the chrome custom tab to cache these non persistence cookies ?

**Comment by agologan** [comment]
Unfortunately this is a question best suited for the Chrome developer team.
There is no configuration afaik to control that behavior.
Please reach out to them and let us know if there's something we can tweak in the lib for you.
