### ISSUE TITLE
Activity didn't handle redirect.

### ISSUE THREAD

**Issue by DioDread** [openid/AppAuth-Android#83]
I'llconfigure my Activity Manifest with net.openid.appauth.RedirectUriReceiverActivity according with guide. But after authorization is complete and callback page is shown in system browser onCreate isn't called. And there is no possibility to check data recevied from oAuth. Can it be caused by such error - "E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa214d070" which i see in logs after auth initial request is perfromed? Thank you

**Comment by iainmcgin** [comment]
Hi @DioDread, I don't believe the error message you mention is related. Is the redirect URI you are using a custom scheme (e.g. com.example.myapp:/oauth2redirect) or an https URL (e.g. https://myapp.example.com/oauth2redirect)? If it is an https URL, launching your app depends on your system browser correctly querying the system for handlers of that URL, allowing the user to choose the app to open it with, or for the browser to support app linking.

You can test if your intent-filter is correct using adb:

```
adb shell am start -W -a android.intent.action.VIEW -c android.intent.category.DEFAULT -d REDIRECT_URI
```

Running that command (substituting `REDIRECT_URI` appropriately) will open the default app for that URL, or show you a picker if there is more than one. Is your app listed as an option for this?

**Comment by DioDread** [comment]
Hello and thank you for reply. Maybe I didn't get something about scheme. Is that some key which I need to configure, or it's just URL format? My redirect uri has https.

**Comment by sdotlittlenail** [comment]
Hi folks,

based on your [demo app](https://github.com/openid/AppAuth-Android/tree/master/app), I adapted the idp_configs.xml.

Now it is possible to view the MainActivity screen and I can login to Google with my own account within a custom browser tab.

But how can I view the TokenActivity? When I close the custom browser tab, I switch back to the MainActivity with no possibility to view user or token information.

Btw: I am suffering the same problems when I am following this [tutorial](https://codelabs.developers.google.com/codelabs/appauth-android-codelab/index.html?index=..%2F..%2Fio2016#0) (LinearLayout for user data is never updated after successful login in custom browser tab)

**Comment by Abdallah4021** [comment]
@a-tsvil  

HI, @a-tsvil 

you said: "UPD2 I've added scheme with android:host and it's wirking fine now"
i want to ask how did u add the scheme to your app. 
because i am facing the same problem.

**Comment by shishirshettygit** [comment]
> @a-tsvil
> 
> HI, @a-tsvil
> 
> you said: "UPD2 I've added scheme with android:host and it's wirking fine now"
> i want to ask how did u add the scheme to your app.
> because i am facing the same problem.
I am guess here:


<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="org.mskcc.mymsk"
                    android:path="/oauthredirect"
                    android:scheme="http" />
            </intent-filter>
        </activity>
