### ISSUE TITLE
TokenResponseCallback

### ISSUE THREAD

**Issue by mahendradabiaplite** [openid/AppAuth-Android#839]
AuthorizationException with error code 9 and null error field. anyone can help me what does mean by code 9 ?

**Comment by CompileConnected** [comment]
This is not a bug.

it's  Indicates that a received ID token is invalid

for further more information please google it,
if you stumble any more code, please check in here
https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationException.java

find your code and google it

**Comment by agologan** [comment]
Marking as resolve per @CompileConnected 's answer.
Thanks for the assist.
