### ISSUE TITLE
AuthorizationException: {"type":0,"code":3,"errorDescription":"Network error"}

### ISSUE THREAD

**Issue by ritusuman10** [openid/AppAuth-Android#859]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with [App Links](https://developer.android.com/training/app-links) for client redirect.
- [x] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.11.1
- Integration: Java
- Identity provider: Auth0

### Issue Description
i am getting AuthorizationException after login while getting token from mAuthService.performTokenRequest.
here is the error :

AuthorizationException: {"type":0,"code":3,"errorDescription":"Network error"}

**Comment by agologan** [comment]
Sorry, but you need to do your own debugging to figure this out.
There's not enough information provide any sort of assistance.

**Comment by ritusuman10** [comment]
could you please help me to find out the root cause for this

**Comment by ritusuman10** [comment]
Hi
i debug my code and found out that doInBackground method inside  AuthorizationService class give exception i.e java.net.SocketTimeoutException: timeout.

**Comment by agologan** [comment]
Not sure what you're expectation is here. As far as I can tell from this thread, you get a typical network connection error which is surfaced in your app as an AuthorizationException.
It's up to you and your own app logic to determine what the app or the user needs to do in this case.

**Comment by agologan** [comment]
Need to create your own ConnectionBuilder per https://github.com/openid/AppAuth-Android#customizing-the-connection-builder-for-http-requests
The default one is here: https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/connectivity/DefaultConnectionBuilder.java

_Marking this as resolved for now. 
Feel free to reply if you need further help._

**Comment by deepakkanyan** [comment]
how I can set it while try to get The Token or refresh token,

I want to increase the timeout 10 second to 30 or 60 Sec.
