### ISSUE TITLE
performTokenRequest takes to much time

### ISSUE THREAD

**Issue by davcres** [openid/AppAuth-Android#872]
When this method is called the response late too much times most of the times.

``` 
public void performTokenRequest(@NonNull
                                TokenRequest request,
                                @NonNull
                                ClientAuthentication clientAuthentication,
                                @NonNull
                                AuthorizationService.TokenResponseCallback callback)
```

### Configuration
- Version: 0.11.1
- Integration: native Kotlin
- Identity provider: Auth0

**Comment by Moes81** [comment]
@davcres  Why do you think this is a bug in the library? I don't have any issues with this function since using this lib.

**Comment by agologan** [comment]
Please provide comparable measurements to support your case.
As it currently stands this is not an actionable item.
There probably isn't any issue with the lib itself, but I'll give you the benefit of the doubt.
