### ISSUE TITLE
Registration endpoint is optional

### ISSUE THREAD

**Issue by a0a0** [openid/AppAuth-Android#88]
Maybe you should replace the check at line
https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationServiceConfiguration.java#L169

with

JsonUtil.getUriIfDefined(json, KEY_REGISTRATION_ENDPOINT));

**Comment by WilliamDenniss** [comment]
Sounds correct. @rebeckag, can you review this?
