### ISSUE TITLE
[READ] Step 1: Are you in the right place?

### ISSUE THREAD

**Issue by Arifin-pixel** [openid/AppAuth-Android#918]
[READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in the code in this repository.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

For general technical questions, post a question on StackOverflow
with the firebase tag.

For general Firebase discussion, use the firebase-talk
google group.

For help troubleshooting your application that does not fall under one
of the above categories, reach out to the personalized
Firebase support channel.

[REQUIRED] Step 2: Describe your environment

Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1 (Build #AI-213.7172.25.2113.9123335, built on September 30, 2022)

Firebase Component: com.google.firebase:firebase-analytics-ktx,

Component version: 21.2.0

[REQUIRED] Step 3: Describe the problem

Hi,
we are getting the root blocking ANR issue on the release build, reported on the Firebase Crashlytics Dashboard.

Steps to reproduce: -- unable to reproduce the issue.

Please find the below logs and other details.

main (runnable):tid=1 systid=31432 at com.google.android.gms.internal.measurement.zzee.zzg(zzee.java:1) at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.getInstance(AnalyticsConnectorImpl.java:12) at com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar.lambda$getComponents$0(AnalyticsConnectorRegistrar.java:4) at com.google.firebase.analytics.connector.internal.zzb.create(zzb.java) at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:132) at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(ComponentRuntime.java:1132) at com.google.firebase.components.Lazy.get(Lazy.java:53) at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291) at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281) at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:594) at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:305) at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:269) at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:254) at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51) at android.content.ContentProvider.attachInfo(ContentProvider.java:2388) at android.content.ContentProvider.attachInfo(ContentProvider.java:2358) at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45) at android.app.ActivityThread.installProvider(ActivityThread.java:7841) at android.app.ActivityThread.installContentProviders(ActivityThread.java:7371) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7279) at android.app.ActivityThread.access$1700(ActivityThread.java:299) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:264) at android.app.ActivityThread.main(ActivityThread.java:8312) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by agologan** [comment]
I'm sorry but you're issue seems unrelated to this lib.
