### ISSUE TITLE
Whitelable error page (type=None, status=999)

### ISSUE THREAD

**Issue by Squall-Huang** [openid/AppAuth-Android#926]
> Whitelable error page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> There was an unexpected error (type=None, status=999).

After I logged in , my android emulator show above error.
I don't know where cause wrong?

**Comment by agologan** [comment]
It's no something we can help you with, you need to reach out to your Identity Provider and/or web-app developer.
