### ISSUE TITLE
Manifest merger failed : Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.???

### ISSUE THREAD

**Issue by aruny121** [openid/AppAuth-Android#927]
### Configuration
- Version: 0.X.Y
- Integration: (native(Java/Kotlin), Xamarin, ReactNative, etc)
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

**Comment by aruny121** [comment]
Hi I am facing the  issue 
Manifest merger failed : Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.

I know the solution for this is to add some code in build.gradle file , but my problem is i am trying to include this lib in AOSP 
Any solution if we can add the solution some other file (like in mk or bp file) . I cannot use gradle file . 
Please suggest

**Comment by agologan** [comment]
I don't know the specifics of your build system but if all else fails you can just redefine the activity with `tools:node="replace"` as seen in the example: https://github.com/openid/AppAuth-Android#capturing-the-authorization-redirect
