### ISSUE TITLE
ActivityNotFoundException one some phones

### ISSUE THREAD

**Issue by lccarlsson** [openid/AppAuth-Android#941]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with [App Links](https://developer.android.com/training/app-links) for client redirect.
- [-] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.11.1
- Integration: Native kotlin
- Identity provider: Google, Microsoft

### Issue Description
Hi. We're seeing some `ActivityNotFoundException` in our logs, when users are trying to launch the browser intent (`getAuthorizationRequestIntent`). We cannot fully figure out what is causing it since its only appearing on a small subset of our users. The previous threads I've looked at regarding the issue is from way older versions, and has had some mitigations. Not seen any recent threads about it so not sure if its still a known issue.

Two phones are from within the company, so we know what these are:
Galaxy S20 with Android 12, only using built in browser. Only reproducible when in work profile.
Galaxy Z with Android 11, using Chrome. 100% reproducible on this phone.

Any ideas what could be causing it?

**Comment by agologan** [comment]
There have been a few reports of this already in a variety of scenarios.
Can you tell me:
• for the work profile: does the user have a browser installed in the work profile itself?
• what is the exact browser (possibly version) the user is using in each case?

This will help narrow it down and cross-reference with other reports.
"Chrome" is not accurate enough since there are 3 versions today in Play Store (Stable, Beta, Dev).
Having the appId and version would be best especially if you're seeing 100% as we'll be able to reproduce and debug that specific combination.

**Comment by lccarlsson** [comment]
We asked the S20 user to install a browser (Firefox) while explicitly in the work profile, and it works after that. They can browse normally using their regular browser (don't actually know which one on this phone) while in the work profile, so the browser is accessible to the user but not our application. The Galaxy Z is using stable Chrome from Play Store.

We have this workaround, but it feels odd telling users who already have a browser that they need to install another browser as well.

**Comment by agologan** [comment]
It might not be a workaround, lots of users don't notice/know the difference between inside the work profile and outside of it until you point it out, and lots of corporate MDM configurations don't pre-install a browser.

This also has to do with the UX in the launcher. While the default Samsung launcher groups all the apps in a folder under the secured by Knox logo, others just dump everything in the same list without a clear delineation.

What ends up happening is things don't work unless the app developer had the foresight to handle the error that results with  a nice prompt to the user stating they might not have a browser installed.

**Comment by neokree** [comment]
I also found out this same issue for a Blackview BV4900 device in production. Seems like they didn't ship Android with a browser, after asking the customer to install Chrome everything worked correctly.

**Comment by agologan** [comment]
Marking the issue as resolved per the OP comment.
