### ISSUE TITLE
on logout it says session_not_active, logout is not working

### ISSUE THREAD

**Issue by bhavnamulani** [openid/AppAuth-Android#947]
Hi All,
I have implemented appauth and I can see login page with success, as I can get user info after login. 
I am facing issue with logout whenever I try to logout it says session_not_active.
Below is the code for logout I am using

  val authService = AuthorizationService(this)
                val endSessionRequest = EndSessionRequest.Builder(authServiceConfig)
                    .setPostLogoutRedirectUri(redirectUri)
                    .setIdTokenHint(authState.accessToken)
                    .build()

                val intent = authService.getEndSessionRequestIntent(endSessionRequest)
                getResultForLogout.launch(intent)
                
           Please help me out with this issue.

**Comment by agologan** [comment]
`id_token_hint` needs to be **authState.`idToken`** as the name suggests.
Ref: https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout
