### ISSUE TITLE
Is there any plan to build or migrate the library and its implementation in/to Kotlin?

### ISSUE THREAD

**Issue by sundeepkmallick** [openid/AppAuth-Android#954]
### Configuration
- Version: 0.11.1
- Integration: native(Kotlin)
- Identity provider: Any

### Description
Thank you very much for this amazing open source library. Looking into the current trend, is there any plan to build or migrate the library and its implementation in/to Kotlin in near future or is there any road map for it?

**Comment by agologan** [comment]
There have been similar questions in the past.
While I've tried to dedicate time to this, to maybe encourage new developers to contribute to it, it never materialized.
There are arguments for a kotlin version or even a kotlin multi-platform version but we don't have the availability to create that.

If there was a good kotlin alternative that gets enough traction from the community we'd be more then happy to recommend it in the docs.

**Comment by sundeepkmallick** [comment]
Sorry for the duplicate question, I searched and did not find somehow question on this topic (because of my poor search skill in GitHub), I raised. Please let me know if I can be any help of. Thank you for your quick answer.
