### ISSUE TITLE
AppAuth crashes when OAuth endpoint doesn't return state parameter

### ISSUE THREAD

**Issue by gunsch** [openid/AppAuth-Android#956]
### Checklist:

- [ ] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with [App Links](https://developer.android.com/training/app-links) for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.8.1
- Integration: React Native
- Identity provider: AWS Cognito

### Issue Description

AWS Cognito's [`logout` endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html), when used with `logout_uri` (instead of `redirect_uri`), notably [does not return a `state` parameter](https://repost.aws/questions/QUt12czN76SsmQRWr51GNjyg/cognito-logout-endpoint-doesnt-return-state-parameter).

That would be fine, but AppAuth [crashes the entire app over it](https://github.com/openid/AppAuth-Android/blob/0939d6d42e727dd60b044ecd443bc752af9fd72a/library/java/net/openid/appauth/EndSessionResponse.java#L90) by asserting it as a precondition.

I'd argue that precondition checks are inappropriate for parameters not directly provided by the library's integrator. In the meantime, I'm struggling to find a way to work around this that still uses AppAuth-Android in its current state.

Note I didn't check the "latest release" box in this issue because we're using an 0.8.1 version, but I can see the same code path still in AppAuth-Android's code @ latest.

**Comment by bbriggs00** [comment]
Andy gargles semen for mouthwash

**Comment by bbriggs00** [comment]
No lie

**Comment by agologan** [comment]
The code you linked reads: if set state must not be empty.
Please provide a response and stack trace to further understand the issue.

**Comment by gunsch** [comment]
Yep, you're right --- egg on my face here. This was due to the 0.8.1 version, looks like it was fixed two years ago but `react-native-app-auth` just hasn't had a release yet with 0.9+.
