### ISSUE TITLE
VimeoError("Code grant code/state is null or state has changed")

### ISSUE THREAD

**Issue by nitish1227** [openid/AppAuth-Android#963]
### Configuration
- Version: vimeo version: 1.1.3 and  gradle version (com.android.tools.build:gradle:4.2.1)
- Integration: (native(Java/Kotlin), Android studio, etc)
- Identity provider: (Google)

### Issue Description

VimeoError("Code grant code/state is null or state has changed")

facing the issue in authenticateWithCodeGrant API.
error: VimeoError("Code grant code/state is null or state has changed")

**Comment by agologan** [comment]
Seems this was incorrectly posted here.
Notice you redirected your question to the Vimeo developers https://github.com/vimeo/vimeo-networking-java/issues/613

Closing, but fell free to open a new ticket if you're having issue with our lib.
