### ISSUE TITLE
Android 14 AuthorizationServiceConfiguration.fetchFromUrl fails

### ISSUE THREAD

**Issue by RubenMH** [openid/AppAuth-Android#968]
### Configuration
- Version: 0.11.1
- Integration: Native - Kotlin

### Issue Description
Using a Google Pixel 6 with Android 14, in AuthorizationServiceConfiguration class, the method fetchFromUrl fails.
It calls to ConfigurationRetrievalAsyncTask where in `doInBackground` there are the following code.

````
HttpURLConnection conn = mConnectionBuilder.openConnection(mUri);
conn.setRequestMethod("GET");
conn.setDoInput(true);
conn.connect();
is = conn.getInputStream();
````

In `conn.connect();` the task stops. 

On other Android versions, I've tested with Android 13, Android 12 and Android 9 it works and continues.

There may be a bug in URLConnection Android class, but I want to share with you to prevent and check it in the future

**Comment by kelsonflint** [comment]
Android 14 is failing to process the redirection from the browser intent.
`net.openid.appauth.AuthorizationException : {"type":0,"code":1,"errorDescription":"User cancelled flow"}`

**Comment by agologan** [comment]
Tested this today on Beta3 and 4 and have seen no issues.

If you experience issue please provide some context (error message, stack trace, etc) and and I'll reopen the topic.
