### ISSUE TITLE
 400 invalid_request

### ISSUE THREAD

**Issue by JinYangZhou1225** [openid/AppAuth-Android#969]
### Configuration
demo
### Description

Return 400 invalid_request  when I modify.Who can help me ,realy thanks

   manifestPlaceholders = [
                'appAuthRedirectScheme': 'com.six.myapplication'
        ]
  <activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="https"
                  android:host="com.six.myapplication"
                />
            </intent-filter>
        </activity>
{
  "client_id": "xxxx.apps.googleusercontent.com",
  "redirect_uri": "https://com.six.myapplication",
  "end_session_redirect_uri": "https://com.six.myapplication",
  "authorization_scope": "openid email profile",
  "discovery_uri": "https://accounts.google.com/.well-known/openid-configuration",

  "authorization_endpoint_uri": "",
  "token_endpoint_uri": "",
  "registration_endpoint_uri": "",
  "user_info_endpoint_uri": "",
  "https_required": true
}

**Comment by agologan** [comment]
When using a custom redirect URI as shown in the examples the **redirect_uri** for a `appAuthRedirectScheme: 'com.six.myapplication'` would be something along the lines of: `com.six.myapplication://oauth2redirect`

If instead you want to use AppLinks and you own a specific domain please see our documentation on the topic.
