### ISSUE TITLE
ending the session as HTTP request

### ISSUE THREAD

**Issue by octavianionel-flyability** [openid/AppAuth-Android#970]
### Configuration
- Version: 0.11.1
- Integration: native(Java/Kotlin)
- Identity provider: Okta & KeyCloak

### Description
When doing endSession() I would like to do it in background (now I can see a redirect to the web browser and then the logout is done). Is it possible to do this in the background, using a HTTP request?

**Comment by agologan** [comment]
We don't support it or have a plan to do so but one could call the endpoint separately.
The standard does allow it: https://openid.net/specs/openid-connect-rpinitiated-1_0.html

Have yet to see an IdP that implements - Okta and KeyCloak both handle it with the standard redirect which brings transparency and gives the IdP the opportunity to clear cookies if necessary.
