### ISSUE TITLE
Library difficult to use/integrate

### ISSUE THREAD

**Issue by nycodes9** [openid/AppAuth-Android#98]
Apologize for the generic issue but would love to see the library and sample like other android specific  libraries from google open source like [google-services/signin](https://github.com/googlesamples/google-services/tree/master/android/signin)
or developer relations library like [easypermissions](https://github.com/googlesamples/easypermissions) (for non-official ones)

The talk and the premises addressed here are bleeding edge (custom tabs, PKCE etc.) but setting it up is a huge pain in the ass. 

Is adding this in  firebase authentication on the roadmap?

**Comment by iainmcgin** [comment]
Could you be more specific about the problems you are having? This repository contains a demo app, with instructions for configuring Google sign-in as an example IDP [here](https://github.com/openid/AppAuth-Android/blob/master/app/README.md). Beyond this, as the library is intended to work with any OAuth2 or OpenID Connect identity provider, we can only provide a general overview of how to use the library. The developer is still expected to understand how OAuth2 works.

As for Firebase Authentication, we have no immediate plans to integrate AppAuth into it as some generic mechanism to support OAuth2 / OpenID Connect providers.

**Comment by WilliamDenniss** [comment]
We have an [interactive codelab](https://codelabs.developers.google.com/codelabs/appauth-android-codelab/) that was originally created for Google I/O, have you tried it?

**Comment by WilliamDenniss** [comment]
Closing this for now. If you have actionable feedback on how to reduce complexity, please add your thoughts!

**Comment by nycodes9** [comment]
@WilliamDenniss Thanks, codelab was of good help. Quick feedback - on emulator (where custom chrome tabs are not available) the "net::cache" error on default browser is preventing from getting the access token. Kindly suggest.
Emulator config - API 23 6.0 Google APIs, x86_64
